# Trabajando con texto

In [ ]:
import polars as pl

## NOTA: El Dataset de NYC

El archivo `nyc.csv` es bastante grande (más de 500 MB), por lo que se ha comprimido como un archivo `.zip` en esta carpeta.

Necesitarás descomprimir el archivo CSV para que los siguientes ejemplos de código funcionen.

- En macOS, haz doble clic en el archivo `nyc.csv.zip`.
- En Windows, haz clic derecho en el archivo `nyc.csv.zip` y selecciona `Extraer todo`. Extrae el archivo en esta carpeta.

- El dataset `nyc.csv` es una colección de empleados del sector público en la ciudad de Nueva York.

In [ ]:
nyc = pl.read_csv("nyc.csv")
nyc.head(1)

shape: (1, 8)
┌──────────────┬───────────┬────────────┬──────────┬──────────┬──────────────┬─────────┬───────────┐
│ Agency Name  ┆ Last Name ┆ First Name ┆ Mid Init ┆ Borough  ┆ Title        ┆ Base    ┆ Pay Basis │
│ ---          ┆ ---       ┆ ---        ┆ ---      ┆ ---      ┆ ---          ┆ Salary  ┆ ---       │
│ str          ┆ str       ┆ str        ┆ str      ┆ str      ┆ str          ┆ ---     ┆ str       │
│              ┆           ┆            ┆          ┆          ┆              ┆ f64     ┆           │
╞══════════════╪═══════════╪════════════╪══════════╪══════════╪══════════════╪═════════╪═══════════╡
│ OFFICE OF    ┆ BEREZIN   ┆ MIKHAIL    ┆ null     ┆ BROOKLYN ┆ EMERGENCY    ┆ 86005.0 ┆ per Annum │
│ EMERGENCY    ┆           ┆            ┆          ┆          ┆ PREPAREDNESS ┆         ┆           │
│ MANAGEMEN…   ┆           ┆            ┆          ┆          ┆ MANAGER      ┆         ┆           │
└──────────────┴───────────┴────────────┴──────────┴──────────┴──────────────┴─────────┴───────────┘

- Veamos el conteo de valores nulos y el conteo de valores presentes.
- El atributo `shape` devuelve las dimensiones (alto, ancho) del `DataFrame`.
- El método `count` devuelve el número de valores presentes por columna.
- El método `null_count` devuelve el número de valores ausentes (`null`) por columna.

In [ ]:
nyc.shape

(6225611, 8)

In [ ]:
nyc.count()

shape: (1, 8)
┌─────────────┬───────────┬────────────┬──────────┬─────────┬─────────┬─────────────┬───────────┐
│ Agency Name ┆ Last Name ┆ First Name ┆ Mid Init ┆ Borough ┆ Title   ┆ Base Salary ┆ Pay Basis │
│ ---         ┆ ---       ┆ ---        ┆ ---      ┆ ---     ┆ ---     ┆ ---         ┆ ---       │
│ u32         ┆ u32       ┆ u32        ┆ u32      ┆ u32     ┆ u32     ┆ u32         ┆ u32       │
╞═════════════╪═══════════╪════════════╪══════════╪═════════╪═════════╪═════════════╪═══════════╡
│ 6225611     ┆ 6212030   ┆ 6212028    ┆ 3665572  ┆ 5719377 ┆ 6225447 ┆ 6225611     ┆ 6225611   │
└─────────────┴───────────┴────────────┴──────────┴─────────┴─────────┴─────────────┴───────────┘

In [ ]:
nyc.null_count()

shape: (1, 8)
┌─────────────┬───────────┬────────────┬──────────┬─────────┬───────┬─────────────┬───────────┐
│ Agency Name ┆ Last Name ┆ First Name ┆ Mid Init ┆ Borough ┆ Title ┆ Base Salary ┆ Pay Basis │
│ ---         ┆ ---       ┆ ---        ┆ ---      ┆ ---     ┆ ---   ┆ ---         ┆ ---       │
│ u32         ┆ u32       ┆ u32        ┆ u32      ┆ u32     ┆ u32   ┆ u32         ┆ u32       │
╞═════════════╪═══════════╪════════════╪══════════╪═════════╪═══════╪═════════════╪═══════════╡
│ 0           ┆ 13581     ┆ 13583      ┆ 2560039  ┆ 506234  ┆ 164   ┆ 0           ┆ 0         │
└─────────────┴───────────┴────────────┴──────────┴─────────┴───────┴─────────────┴───────────┘

### Lectura Adicional
- https://docs.pola.rs/api/python/stable/reference/api/polars.read_csv.html
- https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.shape.html
- https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.count.html
- https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.null_count.html

## Conversión de Mayúsculas/Minúsculas
- Polars agrupa métodos relacionados bajo un atributo/accesor (un espacio de nombres).
- Los métodos de cadenas de texto tienen un espacio de nombres dedicado `str`.

In [ ]:
nyc = pl.read_csv("nyc.csv")
nyc.head(2)

shape: (2, 8)
┌──────────────┬───────────┬────────────┬──────────┬──────────┬──────────────┬─────────┬───────────┐
│ Agency Name  ┆ Last Name ┆ First Name ┆ Mid Init ┆ Borough  ┆ Title        ┆ Base    ┆ Pay Basis │
│ ---          ┆ ---       ┆ ---        ┆ ---      ┆ ---      ┆ ---          ┆ Salary  ┆ ---       │
│ str          ┆ str       ┆ str        ┆ str      ┆ str      ┆ str          ┆ ---     ┆ str       │
│              ┆           ┆            ┆          ┆          ┆              ┆ f64     ┆           │
╞══════════════╪═══════════╪════════════╪══════════╪══════════╪══════════════╪═════════╪═══════════╡
│ OFFICE OF    ┆ BEREZIN   ┆ MIKHAIL    ┆ null     ┆ BROOKLYN ┆ EMERGENCY    ┆ 86005.0 ┆ per Annum │
│ EMERGENCY    ┆           ┆            ┆          ┆          ┆ PREPAREDNESS ┆         ┆           │
│ MANAGEMEN…   ┆           ┆            ┆          ┆          ┆ MANAGER      ┆         ┆           │
│ OFFICE OF    ┆ GEAGER    ┆ VERONICA   ┆ M        ┆ BROOKLYN ┆ EMERGENCY    ┆ 86005.0 ┆ per Annum │
│ EMERGENCY    ┆           ┆            ┆          ┆          ┆ PREPAREDNESS ┆         ┆           │
│ MANAGEMENT…  ┆           ┆            ┆          ┆          ┆ MANAGER      ┆         ┆           │
└──────────────┴───────────┴────────────┴──────────┴──────────┴──────────────┴─────────┴───────────┘

- El método `str.to_lowercase` convierte todos los caracteres a minúsculas.
- El método `str.to_uppercase` convierte todos los caracteres a mayúsculas.
- El método `str.to_titlecase` convierte todos los caracteres a formato título (primera letra de cada palabra en mayúscula).

In [ ]:
nyc.select(
    pl.col("Borough").str.to_lowercase(),
    pl.col("Pay Basis").str.to_uppercase(),
    pl.col("Agency Name").str.to_titlecase(),
)

shape: (6_225_611, 3)
┌───────────┬───────────┬─────────────────────────────────┐
│ Borough   ┆ Pay Basis ┆ Agency Name                     │
│ ---       ┆ ---       ┆ ---                             │
│ str       ┆ str       ┆ str                             │
╞═══════════╪═══════════╪═════════════════════════════════╡
│ brooklyn  ┆ PER ANNUM ┆  Office Of Emergency Managemen… │
│ brooklyn  ┆ PER ANNUM ┆ Office Of Emergency Management… │
│ brooklyn  ┆ PER ANNUM ┆   Office Of Emergency Manageme… │
│ brooklyn  ┆ PER ANNUM ┆ Office Of Emergency Management  │
│ brooklyn  ┆ PER ANNUM ┆ Office Of Emergency Management  │
│ …         ┆ …         ┆ …                               │
│ bronx     ┆ PER DAY   ┆ Nyc Housing Authority           │
│ manhattan ┆ PER DAY   ┆ Nyc Housing Authority           │
│ manhattan ┆ PER DAY   ┆ Nyc Housing Authority           │
│ manhattan ┆ PER ANNUM ┆ Nyc Housing Authority           │
│ manhattan ┆ PER ANNUM ┆ Nyc Housing Authority           │
└───────────┴───────────┴─────────────────────────────────┘

- Convertir todas las columnas de texto a formato título parece ideal para este dataset.
- Podemos pasar un tipo de dato de Polars a la función `pl.col` para apuntar a las columnas con ese tipo de dato.
- `with_columns` reemplazará elegantemente las columnas antiguas con las nuevas (si tienen el mismo nombre).

In [ ]:
nyc.with_columns(pl.col(pl.String).str.to_titlecase())

shape: (6_225_611, 8)
┌────────────┬───────────┬────────────┬──────────┬───────────┬────────────┬────────────┬───────────┐
│ Agency     ┆ Last Name ┆ First Name ┆ Mid Init ┆ Borough   ┆ Title      ┆ Base       ┆ Pay Basis │
│ Name       ┆ ---       ┆ ---        ┆ ---      ┆ ---       ┆ ---        ┆ Salary     ┆ ---       │
│ ---        ┆ str       ┆ str        ┆ str      ┆ str       ┆ str        ┆ ---        ┆ str       │
│ str        ┆           ┆            ┆          ┆           ┆            ┆ f64        ┆           │
╞════════════╪═══════════╪════════════╪══════════╪═══════════╪════════════╪════════════╪═══════════╡
│ Office Of  ┆ Berezin   ┆ Mikhail    ┆ null     ┆ Brooklyn  ┆ Emergency  ┆ 86005.0    ┆ Per Annum │
│ Emergency  ┆           ┆            ┆          ┆           ┆ Preparedne ┆            ┆           │
│ Managemen… ┆           ┆            ┆          ┆           ┆ ss Manager ┆            ┆           │
│ Office Of  ┆ Geager    ┆ Veronica   ┆ M        ┆ Brooklyn  ┆ Emergency  ┆ 86005.0    ┆ Per Annum │
│ Emergency  ┆           ┆            ┆          ┆           ┆ Preparedne ┆            ┆           │
│ Management ┆           ┆            ┆          ┆           ┆ ss Manager ┆            ┆           │
│ …          ┆           ┆            ┆          ┆           ┆            ┆            ┆           │
│ Office Of  ┆ Ramani    ┆ Shraddha   ┆ null     ┆ Brooklyn  ┆ Emergency  ┆ 86005.0    ┆ Per Annum │
│ Emergency  ┆           ┆            ┆          ┆           ┆ Preparedne ┆            ┆           │
│ Manageme…  ┆           ┆            ┆          ┆           ┆ ss Manager ┆            ┆           │
│ Office Of  ┆ Rotta     ┆ Jonathan   ┆ D        ┆ Brooklyn  ┆ Emergency  ┆ 86005.0    ┆ Per Annum │
│ Emergency  ┆           ┆            ┆          ┆           ┆ Preparedne ┆            ┆           │
│ Management ┆           ┆            ┆          ┆           ┆ ss Manager ┆            ┆           │
│ Office Of  ┆ Wilson Ii ┆ Robert     ┆ P        ┆ Brooklyn  ┆ Emergency  ┆ 86005.0    ┆ Per Annum │
│ Emergency  ┆           ┆            ┆          ┆           ┆ Preparedne ┆            ┆           │
│ Management ┆           ┆            ┆          ┆           ┆ ss Manager ┆            ┆           │
│ …          ┆ …         ┆ …          ┆ …        ┆ …         ┆ …          ┆ …          ┆ …         │
│ Nyc        ┆ Daley     ┆ Garfield   ┆ D        ┆ Bronx     ┆ Supervisor ┆ 488.25     ┆ Per Day   │
│ Housing    ┆           ┆            ┆          ┆           ┆ Electricia ┆            ┆           │
│ Authority  ┆           ┆            ┆          ┆           ┆ n          ┆            ┆           │
│ Nyc        ┆ Duncan    ┆ Alvin      ┆ A        ┆ Manhattan ┆ Supervisor ┆ 548.0      ┆ Per Day   │
│ Housing    ┆           ┆            ┆          ┆           ┆ Elevator   ┆            ┆           │
│ Authority  ┆           ┆            ┆          ┆           ┆ Mechanic   ┆            ┆           │
│ Nyc        ┆ Romero    ┆ Vincent    ┆ null     ┆ Manhattan ┆ Supervisor ┆ 548.0      ┆ Per Day   │
│ Housing    ┆           ┆            ┆          ┆           ┆ Elevator   ┆            ┆           │
│ Authority  ┆           ┆            ┆          ┆           ┆ Mechanic   ┆            ┆           │
│ Nyc        ┆ Porcelli  ┆ Anthony    ┆ null     ┆ Manhattan ┆ Administra ┆ 163741.0   ┆ Per Annum │
│ Housing    ┆           ┆            ┆          ┆           ┆ tive       ┆            ┆           │
│ Authority  ┆           ┆            ┆          ┆           ┆ Housing    ┆            ┆           │
│            ┆           ┆            ┆          ┆           ┆ Superin…   ┆            ┆           │
│ Nyc        ┆ Colon     ┆ Sibyl      ┆ null     ┆ Manhattan ┆ Administra ┆ 135000.0   ┆ Per Annum │
│ Housing    ┆           ┆            ┆          ┆           ┆ tive       ┆            ┆           │
│ Authority  ┆           ┆            ┆          ┆           ┆ Housing    ┆            ┆           │
│            ┆           ┆            ┆          ┆           ┆ Manager    ┆            ┆           │
└────────────┴───────────┴────────────┴──────────┴───────────┴────────────┴────────────┴───────────┘

### Lectura Adicional
- https://docs.pola.rs/user-guide/expressions/strings/#case-conversion
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.to_lowercase.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.to_uppercase.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.to_titlecase.html

## Eliminación de Espacios en Blanco

In [ ]:
nyc = pl.read_csv("nyc.csv")
nyc.head(2)

shape: (2, 8)
┌──────────────┬───────────┬────────────┬──────────┬──────────┬──────────────┬─────────┬───────────┐
│ Agency Name  ┆ Last Name ┆ First Name ┆ Mid Init ┆ Borough  ┆ Title        ┆ Base    ┆ Pay Basis │
│ ---          ┆ ---       ┆ ---        ┆ ---      ┆ ---      ┆ ---          ┆ Salary  ┆ ---       │
│ str          ┆ str       ┆ str        ┆ str      ┆ str      ┆ str          ┆ ---     ┆ str       │
│              ┆           ┆            ┆          ┆          ┆              ┆ f64     ┆           │
╞══════════════╪═══════════╪════════════╪══════════╪══════════╪══════════════╪═════════╪═══════════╡
│ OFFICE OF    ┆ BEREZIN   ┆ MIKHAIL    ┆ null     ┆ BROOKLYN ┆ EMERGENCY    ┆ 86005.0 ┆ per Annum │
│ EMERGENCY    ┆           ┆            ┆          ┆          ┆ PREPAREDNESS ┆         ┆           │
│ MANAGEMEN…   ┆           ┆            ┆          ┆          ┆ MANAGER      ┆         ┆           │
│ OFFICE OF    ┆ GEAGER    ┆ VERONICA   ┆ M        ┆ BROOKLYN ┆ EMERGENCY    ┆ 86005.0 ┆ per Annum │
│ EMERGENCY    ┆           ┆            ┆          ┆          ┆ PREPAREDNESS ┆         ┆           │
│ MANAGEMENT…  ┆           ┆            ┆          ┆          ┆ MANAGER      ┆         ┆           │
└──────────────┴───────────┴────────────┴──────────┴──────────┴──────────────┴─────────┴───────────┘

- El método `str.strip_chars` elimina los espacios en blanco del inicio y el final de la cadena.
- El método `str.strip_chars_start` elimina los espacios en blanco del inicio de la cadena.
- El método `str.strip_chars_end` elimina los espacios en blanco del final de la cadena.

In [ ]:
nyc.select(
    pl.col("Agency Name"),
    pl.col("Agency Name").str.strip_chars().alias("Agency Name without Whitespace"),
)

shape: (6_225_611, 2)
┌─────────────────────────────────┬────────────────────────────────┐
│ Agency Name                     ┆ Agency Name without Whitespace │
│ ---                             ┆ ---                            │
│ str                             ┆ str                            │
╞═════════════════════════════════╪════════════════════════════════╡
│  OFFICE OF EMERGENCY MANAGEMEN… ┆ OFFICE OF EMERGENCY MANAGEMENT │
│ OFFICE OF EMERGENCY MANAGEMENT… ┆ OFFICE OF EMERGENCY MANAGEMENT │
│   OFFICE OF EMERGENCY MANAGEME… ┆ OFFICE OF EMERGENCY MANAGEMENT │
│ OFFICE OF EMERGENCY MANAGEMENT  ┆ OFFICE OF EMERGENCY MANAGEMENT │
│ OFFICE OF EMERGENCY MANAGEMENT  ┆ OFFICE OF EMERGENCY MANAGEMENT │
│ …                               ┆ …                              │
│ NYC HOUSING AUTHORITY           ┆ NYC HOUSING AUTHORITY          │
│ NYC HOUSING AUTHORITY           ┆ NYC HOUSING AUTHORITY          │
│ NYC HOUSING AUTHORITY           ┆ NYC HOUSING AUTHORITY          │
│ NYC HOUSING AUTHORITY           ┆ NYC HOUSING AUTHORITY          │
│ NYC HOUSING AUTHORITY           ┆ NYC HOUSING AUTHORITY          │
└─────────────────────────────────┴────────────────────────────────┘

- Podemos encadenar múltiples métodos de cadena.
- Cada llamada a un método requiere el atributo `str`. El método se encuentra _dentro_ del espacio de nombres.
- Primero eliminemos los espacios en blanco de todas las columnas de texto, luego convirtamos sus valores a formato título.

In [ ]:
nyc.with_columns(pl.col(pl.String).str.strip_chars().str.to_titlecase())

shape: (6_225_611, 8)
┌────────────┬───────────┬────────────┬──────────┬───────────┬────────────┬────────────┬───────────┐
│ Agency     ┆ Last Name ┆ First Name ┆ Mid Init ┆ Borough   ┆ Title      ┆ Base       ┆ Pay Basis │
│ Name       ┆ ---       ┆ ---        ┆ ---      ┆ ---       ┆ ---        ┆ Salary     ┆ ---       │
│ ---        ┆ str       ┆ str        ┆ str      ┆ str       ┆ str        ┆ ---        ┆ str       │
│ str        ┆           ┆            ┆          ┆           ┆            ┆ f64        ┆           │
╞════════════╪═══════════╪════════════╪══════════╪═══════════╪════════════╪════════════╪═══════════╡
│ Office Of  ┆ Berezin   ┆ Mikhail    ┆ null     ┆ Brooklyn  ┆ Emergency  ┆ 86005.0    ┆ Per Annum │
│ Emergency  ┆           ┆            ┆          ┆           ┆ Preparedne ┆            ┆           │
│ Management ┆           ┆            ┆          ┆           ┆ ss Manager ┆            ┆           │
│ Office Of  ┆ Geager    ┆ Veronica   ┆ M        ┆ Brooklyn  ┆ Emergency  ┆ 86005.0    ┆ Per Annum │
│ Emergency  ┆           ┆            ┆          ┆           ┆ Preparedne ┆            ┆           │
│ Management ┆           ┆            ┆          ┆           ┆ ss Manager ┆            ┆           │
│ Office Of  ┆ Ramani    ┆ Shraddha   ┆ null     ┆ Brooklyn  ┆ Emergency  ┆ 86005.0    ┆ Per Annum │
│ Emergency  ┆           ┆            ┆          ┆           ┆ Preparedne ┆            ┆           │
│ Management ┆           ┆            ┆          ┆           ┆ ss Manager ┆            ┆           │
│ Office Of  ┆ Rotta     ┆ Jonathan   ┆ D        ┆ Brooklyn  ┆ Emergency  ┆ 86005.0    ┆ Per Annum │
│ Emergency  ┆           ┆            ┆          ┆           ┆ Preparedne ┆            ┆           │
│ Management ┆           ┆            ┆          ┆           ┆ ss Manager ┆            ┆           │
│ Office Of  ┆ Wilson Ii ┆ Robert     ┆ P        ┆ Brooklyn  ┆ Emergency  ┆ 86005.0    ┆ Per Annum │
│ Emergency  ┆           ┆            ┆          ┆           ┆ Preparedne ┆            ┆           │
│ Management ┆           ┆            ┆          ┆           ┆ ss Manager ┆            ┆           │
│ …          ┆ …         ┆ …          ┆ …        ┆ …         ┆ …          ┆ …          ┆ …         │
│ Nyc        ┆ Daley     ┆ Garfield   ┆ D        ┆ Bronx     ┆ Supervisor ┆ 488.25     ┆ Per Day   │
│ Housing    ┆           ┆            ┆          ┆           ┆ Electricia ┆            ┆           │
│ Authority  ┆           ┆            ┆          ┆           ┆ n          ┆            ┆           │
│ Nyc        ┆ Duncan    ┆ Alvin      ┆ A        ┆ Manhattan ┆ Supervisor ┆ 548.0      ┆ Per Day   │
│ Housing    ┆           ┆            ┆          ┆           ┆ Elevator   ┆            ┆           │
│ Authority  ┆           ┆            ┆          ┆           ┆ Mechanic   ┆            ┆           │
│ Nyc        ┆ Romero    ┆ Vincent    ┆ null     ┆ Manhattan ┆ Supervisor ┆ 548.0      ┆ Per Day   │
│ Housing    ┆           ┆            ┆          ┆           ┆ Elevator   ┆            ┆           │
│ Authority  ┆           ┆            ┆          ┆           ┆ Mechanic   ┆            ┆           │
│ Nyc        ┆ Porcelli  ┆ Anthony    ┆ null     ┆ Manhattan ┆ Administra ┆ 163741.0   ┆ Per Annum │
│ Housing    ┆           ┆            ┆          ┆           ┆ tive       ┆            ┆           │
│ Authority  ┆           ┆            ┆          ┆           ┆ Housing    ┆            ┆           │
│            ┆           ┆            ┆          ┆           ┆ Superin…   ┆            ┆           │
│ Nyc        ┆ Colon     ┆ Sibyl      ┆ null     ┆ Manhattan ┆ Administra ┆ 135000.0   ┆ Per Annum │
│ Housing    ┆           ┆            ┆          ┆           ┆ tive       ┆            ┆           │
│ Authority  ┆           ┆            ┆          ┆           ┆ Housing    ┆            ┆           │
│            ┆           ┆            ┆          ┆           ┆ Manager    ┆            ┆           │
└────────────┴───────────┴────────────┴──────────┴───────────┴────────────┴────────────┴───────────┘

### Lectura Adicional
- https://docs.pola.rs/user-guide/expressions/strings/#stripping-characters-from-the-ends
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.strip_chars.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.strip_chars_start.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.strip_chars_end.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.to_titlecase.html

## Eliminación de Prefijo y Sufijo

In [ ]:
nyc = pl.read_csv("nyc.csv").with_columns(
    pl.col(pl.String).str.strip_chars().str.to_titlecase()
)
nyc.head(2)

shape: (2, 8)
┌──────────────┬───────────┬────────────┬──────────┬──────────┬──────────────┬─────────┬───────────┐
│ Agency Name  ┆ Last Name ┆ First Name ┆ Mid Init ┆ Borough  ┆ Title        ┆ Base    ┆ Pay Basis │
│ ---          ┆ ---       ┆ ---        ┆ ---      ┆ ---      ┆ ---          ┆ Salary  ┆ ---       │
│ str          ┆ str       ┆ str        ┆ str      ┆ str      ┆ str          ┆ ---     ┆ str       │
│              ┆           ┆            ┆          ┆          ┆              ┆ f64     ┆           │
╞══════════════╪═══════════╪════════════╪══════════╪══════════╪══════════════╪═════════╪═══════════╡
│ Office Of    ┆ Berezin   ┆ Mikhail    ┆ null     ┆ Brooklyn ┆ Emergency    ┆ 86005.0 ┆ Per Annum │
│ Emergency    ┆           ┆            ┆          ┆          ┆ Preparedness ┆         ┆           │
│ Management   ┆           ┆            ┆          ┆          ┆ Manager      ┆         ┆           │
│ Office Of    ┆ Geager    ┆ Veronica   ┆ M        ┆ Brooklyn ┆ Emergency    ┆ 86005.0 ┆ Per Annum │
│ Emergency    ┆           ┆            ┆          ┆          ┆ Preparedness ┆         ┆           │
│ Management   ┆           ┆            ┆          ┆          ┆ Manager      ┆         ┆           │
└──────────────┴───────────┴────────────┴──────────┴──────────┴──────────────┴─────────┴───────────┘

- El método `str.strip_prefix` elimina una subcadena consistente del inicio de cada cadena.
- Polars eliminará el prefijo exactamente una vez.
- Por ejemplo, podemos eliminar `Office Of ` del inicio de cada cadena que incluya ese texto.

In [ ]:
nyc.select(
    pl.col("Agency Name"),
    pl.col("Agency Name").str.strip_prefix("Office Of ").alias("Agency"),
)

shape: (6_225_611, 2)
┌────────────────────────────────┬───────────────────────┐
│ Agency Name                    ┆ Agency                │
│ ---                            ┆ ---                   │
│ str                            ┆ str                   │
╞════════════════════════════════╪═══════════════════════╡
│ Office Of Emergency Management ┆ Emergency Management  │
│ Office Of Emergency Management ┆ Emergency Management  │
│ Office Of Emergency Management ┆ Emergency Management  │
│ Office Of Emergency Management ┆ Emergency Management  │
│ Office Of Emergency Management ┆ Emergency Management  │
│ …                              ┆ …                     │
│ Nyc Housing Authority          ┆ Nyc Housing Authority │
│ Nyc Housing Authority          ┆ Nyc Housing Authority │
│ Nyc Housing Authority          ┆ Nyc Housing Authority │
│ Nyc Housing Authority          ┆ Nyc Housing Authority │
│ Nyc Housing Authority          ┆ Nyc Housing Authority │
└────────────────────────────────┴───────────────────────┘

- El método complementario `str.strip_suffix` elimina una subcadena del final de cada cadena.

In [ ]:
nyc.select(
    pl.col("Agency Name"),
    pl.col("Agency Name")
    .str.strip_prefix("Office Of ")
    .str.strip_suffix(" Authority")
    .alias("Agency"),
)

shape: (6_225_611, 2)
┌────────────────────────────────┬──────────────────────┐
│ Agency Name                    ┆ Agency               │
│ ---                            ┆ ---                  │
│ str                            ┆ str                  │
╞════════════════════════════════╪══════════════════════╡
│ Office Of Emergency Management ┆ Emergency Management │
│ Office Of Emergency Management ┆ Emergency Management │
│ Office Of Emergency Management ┆ Emergency Management │
│ Office Of Emergency Management ┆ Emergency Management │
│ Office Of Emergency Management ┆ Emergency Management │
│ …                              ┆ …                    │
│ Nyc Housing Authority          ┆ Nyc Housing          │
│ Nyc Housing Authority          ┆ Nyc Housing          │
│ Nyc Housing Authority          ┆ Nyc Housing          │
│ Nyc Housing Authority          ┆ Nyc Housing          │
│ Nyc Housing Authority          ┆ Nyc Housing          │
└────────────────────────────────┴──────────────────────┘

### Lectura Adicional
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.strip_prefix.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.strip_suffix.html

## Segmentación de Cadenas (Slicing)

In [ ]:
nyc = pl.read_csv("nyc.csv").with_columns(
    pl.col(pl.String).str.strip_chars().str.to_titlecase()
)
nyc.head(2)

shape: (2, 8)
┌──────────────┬───────────┬────────────┬──────────┬──────────┬──────────────┬─────────┬───────────┐
│ Agency Name  ┆ Last Name ┆ First Name ┆ Mid Init ┆ Borough  ┆ Title        ┆ Base    ┆ Pay Basis │
│ ---          ┆ ---       ┆ ---        ┆ ---      ┆ ---      ┆ ---          ┆ Salary  ┆ ---       │
│ str          ┆ str       ┆ str        ┆ str      ┆ str      ┆ str          ┆ ---     ┆ str       │
│              ┆           ┆            ┆          ┆          ┆              ┆ f64     ┆           │
╞══════════════╪═══════════╪════════════╪══════════╪══════════╪══════════════╪═════════╪═══════════╡
│ Office Of    ┆ Berezin   ┆ Mikhail    ┆ null     ┆ Brooklyn ┆ Emergency    ┆ 86005.0 ┆ Per Annum │
│ Emergency    ┆           ┆            ┆          ┆          ┆ Preparedness ┆         ┆           │
│ Management   ┆           ┆            ┆          ┆          ┆ Manager      ┆         ┆           │
│ Office Of    ┆ Geager    ┆ Veronica   ┆ M        ┆ Brooklyn ┆ Emergency    ┆ 86005.0 ┆ Per Annum │
│ Emergency    ┆           ┆            ┆          ┆          ┆ Preparedness ┆         ┆           │
│ Management   ┆           ┆            ┆          ┆          ┆ Manager      ┆         ┆           │
└──────────────┴───────────┴────────────┴──────────┴──────────┴──────────────┴─────────┴───────────┘

- El método `str.slice` extrae una secuencia de caracteres de cada cadena.
- El primer argumento es el índice inicial, y el segundo argumento es el número de caracteres a extraer.
- Asignemos a cada municipio un código de 3 letras basado en sus primeras 3 letras.

In [ ]:
nyc.select(pl.col("Borough"), pl.col("Borough").str.slice(0, 3).alias("Code"))

shape: (6_225_611, 2)
┌───────────┬──────┐
│ Borough   ┆ Code │
│ ---       ┆ ---  │
│ str       ┆ str  │
╞═══════════╪══════╡
│ Brooklyn  ┆ Bro  │
│ Brooklyn  ┆ Bro  │
│ Brooklyn  ┆ Bro  │
│ Brooklyn  ┆ Bro  │
│ Brooklyn  ┆ Bro  │
│ …         ┆ …    │
│ Bronx     ┆ Bro  │
│ Manhattan ┆ Man  │
│ Manhattan ┆ Man  │
│ Manhattan ┆ Man  │
│ Manhattan ┆ Man  │
└───────────┴──────┘

- Si el segmento se extiende más allá del final de la cadena, Polars recogerá todos los caracteres.

In [ ]:
nyc.select(pl.col("Borough"), pl.col("Borough").str.slice(0, 100).alias("Code"))

shape: (6_225_611, 2)
┌───────────┬───────────┐
│ Borough   ┆ Code      │
│ ---       ┆ ---       │
│ str       ┆ str       │
╞═══════════╪═══════════╡
│ Brooklyn  ┆ Brooklyn  │
│ Brooklyn  ┆ Brooklyn  │
│ Brooklyn  ┆ Brooklyn  │
│ Brooklyn  ┆ Brooklyn  │
│ Brooklyn  ┆ Brooklyn  │
│ …         ┆ …         │
│ Bronx     ┆ Bronx     │
│ Manhattan ┆ Manhattan │
│ Manhattan ┆ Manhattan │
│ Manhattan ┆ Manhattan │
│ Manhattan ┆ Manhattan │
└───────────┴───────────┘

- Podemos comenzar en el medio de una cadena especificando un índice distinto de cero.

In [ ]:
nyc.select(pl.col("Borough"), pl.col("Borough").str.slice(2, 5).alias("Code"))

shape: (6_225_611, 2)
┌───────────┬───────┐
│ Borough   ┆ Code  │
│ ---       ┆ ---   │
│ str       ┆ str   │
╞═══════════╪═══════╡
│ Brooklyn  ┆ ookly │
│ Brooklyn  ┆ ookly │
│ Brooklyn  ┆ ookly │
│ Brooklyn  ┆ ookly │
│ Brooklyn  ┆ ookly │
│ …         ┆ …     │
│ Bronx     ┆ onx   │
│ Manhattan ┆ nhatt │
│ Manhattan ┆ nhatt │
│ Manhattan ┆ nhatt │
│ Manhattan ┆ nhatt │
└───────────┴───────┘

- El método `str.head` extrae caracteres desde el inicio de la cadena.
- El método `str.tail` extrae caracteres desde el final de la cadena.
- Al igual que con `str.slice`, si la cantidad solicitada se extiende más allá de la longitud de la cadena, Polars extraerá tantos caracteres como sea posible.

In [ ]:
nyc.select(
    pl.col("Borough"),
    pl.col("Borough").str.head(3).alias("Code"),
    pl.col("Borough").str.tail(4).alias("Code 2"),
)

shape: (6_225_611, 3)
┌───────────┬──────┬────────┐
│ Borough   ┆ Code ┆ Code 2 │
│ ---       ┆ ---  ┆ ---    │
│ str       ┆ str  ┆ str    │
╞═══════════╪══════╪════════╡
│ Brooklyn  ┆ Bro  ┆ klyn   │
│ Brooklyn  ┆ Bro  ┆ klyn   │
│ Brooklyn  ┆ Bro  ┆ klyn   │
│ Brooklyn  ┆ Bro  ┆ klyn   │
│ Brooklyn  ┆ Bro  ┆ klyn   │
│ …         ┆ …    ┆ …      │
│ Bronx     ┆ Bro  ┆ ronx   │
│ Manhattan ┆ Man  ┆ ttan   │
│ Manhattan ┆ Man  ┆ ttan   │
│ Manhattan ┆ Man  ┆ ttan   │
│ Manhattan ┆ Man  ┆ ttan   │
└───────────┴──────┴────────┘

### Lectura Adicional
- https://docs.pola.rs/user-guide/expressions/strings/#slicing
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.slice.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.head.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.tail.html

## Métodos de Filtrado

In [ ]:
nyc = pl.read_csv("nyc.csv").with_columns(
    pl.col(pl.String).str.strip_chars().str.to_titlecase()
)
nyc.head(2)

shape: (2, 8)
┌──────────────┬───────────┬────────────┬──────────┬──────────┬──────────────┬─────────┬───────────┐
│ Agency Name  ┆ Last Name ┆ First Name ┆ Mid Init ┆ Borough  ┆ Title        ┆ Base    ┆ Pay Basis │
│ ---          ┆ ---       ┆ ---        ┆ ---      ┆ ---      ┆ ---          ┆ Salary  ┆ ---       │
│ str          ┆ str       ┆ str        ┆ str      ┆ str      ┆ str          ┆ ---     ┆ str       │
│              ┆           ┆            ┆          ┆          ┆              ┆ f64     ┆           │
╞══════════════╪═══════════╪════════════╪══════════╪══════════╪══════════════╪═════════╪═══════════╡
│ Office Of    ┆ Berezin   ┆ Mikhail    ┆ null     ┆ Brooklyn ┆ Emergency    ┆ 86005.0 ┆ Per Annum │
│ Emergency    ┆           ┆            ┆          ┆          ┆ Preparedness ┆         ┆           │
│ Management   ┆           ┆            ┆          ┆          ┆ Manager      ┆         ┆           │
│ Office Of    ┆ Geager    ┆ Veronica   ┆ M        ┆ Brooklyn ┆ Emergency    ┆ 86005.0 ┆ Per Annum │
│ Emergency    ┆           ┆            ┆          ┆          ┆ Preparedness ┆         ┆           │
│ Management   ┆           ┆            ┆          ┆          ┆ Manager      ┆         ┆           │
└──────────────┴───────────┴────────────┴──────────┴──────────┴──────────────┴─────────┴───────────┘

- El método `str.contains` devuelve verdadero si una fila contiene una subcadena dada.

In [ ]:
nyc.filter(pl.col("Title").str.contains("Water"))

shape: (4_202, 8)
┌────────────┬────────────┬────────────┬──────────┬──────────┬────────────┬────────────┬───────────┐
│ Agency     ┆ Last Name  ┆ First Name ┆ Mid Init ┆ Borough  ┆ Title      ┆ Base       ┆ Pay Basis │
│ Name       ┆ ---        ┆ ---        ┆ ---      ┆ ---      ┆ ---        ┆ Salary     ┆ ---       │
│ ---        ┆ str        ┆ str        ┆ str      ┆ str      ┆ str        ┆ ---        ┆ str       │
│ str        ┆            ┆            ┆          ┆          ┆            ┆ f64        ┆           │
╞════════════╪════════════╪════════════╪══════════╪══════════╪════════════╪════════════╪═══════════╡
│ Dept Of    ┆ Delaney    ┆ Dennis     ┆ M        ┆ Queens   ┆ Superinten ┆ 170804.0   ┆ Per Annum │
│ Environmen ┆            ┆            ┆          ┆          ┆ dent Of    ┆            ┆           │
│ t          ┆            ┆            ┆          ┆          ┆ Water And  ┆            ┆           │
│ Protection ┆            ┆            ┆          ┆          ┆ Se…        ┆            ┆           │
│ Dept Of    ┆ Shirley    ┆ Winston    ┆ null     ┆ Queens   ┆ Assoc      ┆ 164800.0   ┆ Per Annum │
│ Environmen ┆            ┆            ┆          ┆          ┆ Water Use  ┆            ┆           │
│ t          ┆            ┆            ┆          ┆          ┆ Inspector- ┆            ┆           │
│ Protection ┆            ┆            ┆          ┆          ┆ Mgrl       ┆            ┆           │
│ Dept Of    ┆ Marchese   ┆ Anthony    ┆ null     ┆ Queens   ┆ Superinten ┆ 157960.0   ┆ Per Annum │
│ Environmen ┆            ┆            ┆          ┆          ┆ dent Of    ┆            ┆           │
│ t          ┆            ┆            ┆          ┆          ┆ Water And  ┆            ┆           │
│ Protection ┆            ┆            ┆          ┆          ┆ Se…        ┆            ┆           │
│ Dept Of    ┆ Villella   ┆ Paul       ┆ null     ┆ Queens   ┆ Superinten ┆ 157960.0   ┆ Per Annum │
│ Environmen ┆            ┆            ┆          ┆          ┆ dent Of    ┆            ┆           │
│ t          ┆            ┆            ┆          ┆          ┆ Water And  ┆            ┆           │
│ Protection ┆            ┆            ┆          ┆          ┆ Se…        ┆            ┆           │
│ Dept Of    ┆ Castiglion ┆ John       ┆ A        ┆ Queens   ┆ Superinten ┆ 146260.0   ┆ Per Annum │
│ Environmen ┆ e          ┆            ┆          ┆          ┆ dent Of    ┆            ┆           │
│ t          ┆            ┆            ┆          ┆          ┆ Water And  ┆            ┆           │
│ Protection ┆            ┆            ┆          ┆          ┆ Se…        ┆            ┆           │
│ …          ┆ …          ┆ …          ┆ …        ┆ …        ┆ …          ┆ …          ┆ …         │
│ Dept Of    ┆ Osterhout  ┆ Timothy    ┆ J        ┆ Sullivan ┆ Watershed  ┆ 67550.0    ┆ Per Annum │
│ Environmen ┆            ┆            ┆          ┆          ┆ Maintainer ┆            ┆           │
│ t          ┆            ┆            ┆          ┆          ┆            ┆            ┆           │
│ Protection ┆            ┆            ┆          ┆          ┆            ┆            ┆           │
│ Dept Of    ┆ Dipressi   ┆ Salvatore  ┆ null     ┆ Dutchess ┆ Watershed  ┆ 67550.0    ┆ Per Annum │
│ Environmen ┆            ┆            ┆          ┆          ┆ Maintainer ┆            ┆           │
│ t          ┆            ┆            ┆          ┆          ┆            ┆            ┆           │
│ Protection ┆            ┆            ┆          ┆          ┆            ┆            ┆           │
│ Dept Of    ┆ Valenchis  ┆ Leo        ┆ A        ┆ Ulster   ┆ Watershed  ┆ 61818.0    ┆ Per Annum │
│ Environmen ┆ Sr         ┆            ┆          ┆          ┆ Maintainer ┆            ┆           │
│ t          ┆            ┆            ┆          ┆          ┆            ┆            ┆           │
│ Protection ┆            ┆            ┆          ┆          ┆            ┆            ┆           │
│ Dept Of    ┆ Mccoy      ┆ Lonnie     ┆ R        ┆ Queens   ┆ Superinten ┆ 90.18      ┆ Per Hour  │
│ Environmen ┆            ┆            ┆          ┆          ┆ dent Of    ┆            ┆           │
│ t          ┆            ┆            ┆          ┆          ┆ Water And  ┆            ┆           │
│ Protection ┆            ┆            ┆          ┆          ┆ Se…        ┆            ┆           │
│ Dept Of    ┆ Rider Jr   ┆ Stephen    ┆ D        ┆ Ulster   ┆ Watershed  ┆ 63673.0    ┆ Per Annum │
│ Environmen ┆            ┆            ┆          ┆          ┆ Maintainer ┆            ┆           │
│ t          ┆            ┆            ┆          ┆          ┆            ┆            ┆           │
│ Protection ┆            ┆            ┆          ┆          ┆            ┆            ┆           │
└────────────┴────────────┴────────────┴──────────┴──────────┴────────────┴────────────┴───────────┘

- El método `str.contains_any` devuelve verdadero si el valor de la fila se encuentra dentro de un conjunto de valores posibles.

In [ ]:
nyc.filter(pl.col("Title").str.contains_any(["Water", "Fire"]))

shape: (112_163, 8)
┌────────────┬────────────┬────────────┬──────────┬───────────┬────────────┬───────────┬───────────┐
│ Agency     ┆ Last Name  ┆ First Name ┆ Mid Init ┆ Borough   ┆ Title      ┆ Base      ┆ Pay Basis │
│ Name       ┆ ---        ┆ ---        ┆ ---      ┆ ---       ┆ ---        ┆ Salary    ┆ ---       │
│ ---        ┆ str        ┆ str        ┆ str      ┆ str       ┆ str        ┆ ---       ┆ str       │
│ str        ┆            ┆            ┆          ┆           ┆            ┆ f64       ┆           │
╞════════════╪════════════╪════════════╪══════════╪═══════════╪════════════╪═══════════╪═══════════╡
│ Fire       ┆ Flynn      ┆ Daniel     ┆ E        ┆ Manhattan ┆ Supervisin ┆ 119596.0  ┆ Per Annum │
│ Department ┆            ┆            ┆          ┆           ┆ g Fire     ┆           ┆           │
│            ┆            ┆            ┆          ┆           ┆ Marshal    ┆           ┆           │
│ Fire       ┆ Kane       ┆ Thomas     ┆ G        ┆ Brooklyn  ┆ Chief Fire ┆ 235462.0  ┆ Per Annum │
│ Department ┆            ┆            ┆          ┆           ┆ Marshal    ┆           ┆           │
│ Fire       ┆ Prezant    ┆ David      ┆ J        ┆ Manhattan ┆ Fire       ┆ 232478.0  ┆ Per Annum │
│ Department ┆            ┆            ┆          ┆           ┆ Medical    ┆           ┆           │
│            ┆            ┆            ┆          ┆           ┆ Officer    ┆           ┆           │
│ Fire       ┆ Durkin     ┆ Michael    ┆ B        ┆ Brooklyn  ┆ Assistant  ┆ 215352.0  ┆ Per Annum │
│ Department ┆            ┆            ┆          ┆           ┆ Chief Fire ┆           ┆           │
│            ┆            ┆            ┆          ┆           ┆ Marshal    ┆           ┆           │
│ Fire       ┆ Krebs      ┆ Brian      ┆ M        ┆ Queens    ┆ Supervisin ┆ 119596.0  ┆ Per Annum │
│ Department ┆            ┆            ┆          ┆           ┆ g Fire     ┆           ┆           │
│            ┆            ┆            ┆          ┆           ┆ Marshal    ┆           ┆           │
│ …          ┆ …          ┆ …          ┆ …        ┆ …         ┆ …          ┆ …         ┆ …         │
│ Nyc        ┆ Yok        ┆ Rathjerry  ┆ null     ┆ Manhattan ┆ Associate  ┆ 78733.0   ┆ Per Annum │
│ Housing    ┆            ┆            ┆          ┆           ┆ Fire       ┆           ┆           │
│ Authority  ┆            ┆            ┆          ┆           ┆ Protection ┆           ┆           │
│            ┆            ┆            ┆          ┆           ┆ Insp…      ┆           ┆           │
│ Nyc        ┆ Jeanfranco ┆ Pierre     ┆ null     ┆ Manhattan ┆ Associate  ┆ 74984.0   ┆ Per Annum │
│ Housing    ┆ is         ┆            ┆          ┆           ┆ Fire       ┆           ┆           │
│ Authority  ┆            ┆            ┆          ┆           ┆ Protection ┆           ┆           │
│            ┆            ┆            ┆          ┆           ┆ Insp…      ┆           ┆           │
│ Nyc        ┆ Terranova  ┆ Joseph     ┆ null     ┆ Queens    ┆ Administra ┆ 166112.0  ┆ Per Annum │
│ Housing    ┆            ┆            ┆          ┆           ┆ tive Fire  ┆           ┆           │
│ Authority  ┆            ┆            ┆          ┆           ┆ Protection ┆           ┆           │
│            ┆            ┆            ┆          ┆           ┆ …          ┆           ┆           │
│ Nyc        ┆ Cortes     ┆ Johnny     ┆ S        ┆ Manhattan ┆ Administra ┆ 143926.0  ┆ Per Annum │
│ Housing    ┆            ┆            ┆          ┆           ┆ tive Fire  ┆           ┆           │
│ Authority  ┆            ┆            ┆          ┆           ┆ Protection ┆           ┆           │
│            ┆            ┆            ┆          ┆           ┆ …          ┆           ┆           │
│ Nyc        ┆ Williams   ┆ Donald     ┆ R        ┆ Manhattan ┆ Associate  ┆ 80340.0   ┆ Per Annum │
│ Housing    ┆            ┆            ┆          ┆           ┆ Fire       ┆           ┆           │
│ Authority  ┆            ┆            ┆          ┆           ┆ Protection ┆           ┆           │
│            ┆            ┆            ┆          ┆           ┆ Insp…      ┆           ┆           │
└────────────┴────────────┴────────────┴──────────┴───────────┴────────────┴───────────┴───────────┘

- El método `str.starts_with` verifica si una subcadena se encuentra al inicio de una cadena.
- El método `str.ends_with` verifica si una subcadena se encuentra al final de la cadena.

In [ ]:
nyc.filter(pl.col("Title").str.starts_with("Fire"))

nyc.filter(pl.col("Title").str.ends_with("Marshal"))

shape: (1_830, 8)
┌────────────┬────────────┬────────────┬──────────┬───────────┬────────────┬───────────┬───────────┐
│ Agency     ┆ Last Name  ┆ First Name ┆ Mid Init ┆ Borough   ┆ Title      ┆ Base      ┆ Pay Basis │
│ Name       ┆ ---        ┆ ---        ┆ ---      ┆ ---       ┆ ---        ┆ Salary    ┆ ---       │
│ ---        ┆ str        ┆ str        ┆ str      ┆ str       ┆ str        ┆ ---       ┆ str       │
│ str        ┆            ┆            ┆          ┆           ┆            ┆ f64       ┆           │
╞════════════╪════════════╪════════════╪══════════╪═══════════╪════════════╪═══════════╪═══════════╡
│ Fire       ┆ Flynn      ┆ Daniel     ┆ E        ┆ Manhattan ┆ Supervisin ┆ 119596.0  ┆ Per Annum │
│ Department ┆            ┆            ┆          ┆           ┆ g Fire     ┆           ┆           │
│            ┆            ┆            ┆          ┆           ┆ Marshal    ┆           ┆           │
│ Fire       ┆ Kane       ┆ Thomas     ┆ G        ┆ Brooklyn  ┆ Chief Fire ┆ 235462.0  ┆ Per Annum │
│ Department ┆            ┆            ┆          ┆           ┆ Marshal    ┆           ┆           │
│ Fire       ┆ Durkin     ┆ Michael    ┆ B        ┆ Brooklyn  ┆ Assistant  ┆ 215352.0  ┆ Per Annum │
│ Department ┆            ┆            ┆          ┆           ┆ Chief Fire ┆           ┆           │
│            ┆            ┆            ┆          ┆           ┆ Marshal    ┆           ┆           │
│ Fire       ┆ Krebs      ┆ Brian      ┆ M        ┆ Queens    ┆ Supervisin ┆ 119596.0  ┆ Per Annum │
│ Department ┆            ┆            ┆          ┆           ┆ g Fire     ┆           ┆           │
│            ┆            ┆            ┆          ┆           ┆ Marshal    ┆           ┆           │
│ Fire       ┆ Mccarthy   ┆ John       ┆ J        ┆ Brooklyn  ┆ Supervisin ┆ 119596.0  ┆ Per Annum │
│ Department ┆            ┆            ┆          ┆           ┆ g Fire     ┆           ┆           │
│            ┆            ┆            ┆          ┆           ┆ Marshal    ┆           ┆           │
│ …          ┆ …          ┆ …          ┆ …        ┆ …         ┆ …          ┆ …         ┆ …         │
│ Fire       ┆ Lindell    ┆ Peter      ┆ A        ┆ Brooklyn  ┆ Fire       ┆ 113781.0  ┆ Per Annum │
│ Department ┆            ┆            ┆          ┆           ┆ Marshal    ┆           ┆           │
│ Fire       ┆ Mazarakis  ┆ George     ┆ null     ┆ Brooklyn  ┆ Fire       ┆ 113781.0  ┆ Per Annum │
│ Department ┆ Jr.        ┆            ┆          ┆           ┆ Marshal    ┆           ┆           │
│ Fire       ┆ Coyle      ┆ Michael    ┆ D        ┆ Brooklyn  ┆ Fire       ┆ 113781.0  ┆ Per Annum │
│ Department ┆            ┆            ┆          ┆           ┆ Marshal    ┆           ┆           │
│ Fire       ┆ Xuereb     ┆ John       ┆ J        ┆ Brooklyn  ┆ Supervisin ┆ 142449.0  ┆ Per Annum │
│ Department ┆            ┆            ┆          ┆           ┆ g Fire     ┆           ┆           │
│            ┆            ┆            ┆          ┆           ┆ Marshal    ┆           ┆           │
│ Fire       ┆ Pasquarell ┆ Michael    ┆ null     ┆ Brooklyn  ┆ Fire       ┆ 113781.0  ┆ Per Annum │
│ Department ┆ o          ┆            ┆          ┆           ┆ Marshal    ┆           ┆           │
└────────────┴────────────┴────────────┴──────────┴───────────┴────────────┴───────────┴───────────┘

- La distinción entre mayúsculas y minúsculas puede ser un problema. No hay valores de fila que comiencen con "fire" en minúsculas.

In [ ]:
nyc.filter(pl.col("Title").str.starts_with("fire"))

shape: (0, 8)
┌─────────────┬───────────┬────────────┬──────────┬─────────┬───────┬─────────────┬───────────┐
│ Agency Name ┆ Last Name ┆ First Name ┆ Mid Init ┆ Borough ┆ Title ┆ Base Salary ┆ Pay Basis │
│ ---         ┆ ---       ┆ ---        ┆ ---      ┆ ---     ┆ ---   ┆ ---         ┆ ---       │
│ str         ┆ str       ┆ str        ┆ str      ┆ str     ┆ str   ┆ f64         ┆ str       │
╞═════════════╪═══════════╪════════════╪══════════╪═════════╪═══════╪═════════════╪═══════════╡
└─────────────┴───────────┴────────────┴──────────┴─────────┴───────┴─────────────┴───────────┘

- Una solución es normalizar el texto, convirtiendo todos los caracteres a un formato consistente.
- Por ejemplo, podemos convertir todos los caracteres a minúsculas y luego proporcionar una subcadena en minúsculas.
- Las expresiones regulares (patrones de búsqueda para texto) son una solución alternativa que cubriremos en la siguiente lección.

In [ ]:
nyc.filter(pl.col("Title").str.to_lowercase().str.starts_with("fire"))

nyc.filter(pl.col("Title").str.to_uppercase().str.starts_with("FIRE"))

shape: (104_487, 8)
┌────────────┬───────────┬────────────┬──────────┬───────────┬────────────┬────────────┬───────────┐
│ Agency     ┆ Last Name ┆ First Name ┆ Mid Init ┆ Borough   ┆ Title      ┆ Base       ┆ Pay Basis │
│ Name       ┆ ---       ┆ ---        ┆ ---      ┆ ---       ┆ ---        ┆ Salary     ┆ ---       │
│ ---        ┆ str       ┆ str        ┆ str      ┆ str       ┆ str        ┆ ---        ┆ str       │
│ str        ┆           ┆            ┆          ┆           ┆            ┆ f64        ┆           │
╞════════════╪═══════════╪════════════╪══════════╪═══════════╪════════════╪════════════╪═══════════╡
│ Fire       ┆ Prezant   ┆ David      ┆ J        ┆ Manhattan ┆ Fire       ┆ 232478.0   ┆ Per Annum │
│ Department ┆           ┆            ┆          ┆           ┆ Medical    ┆            ┆           │
│            ┆           ┆            ┆          ┆           ┆ Officer    ┆            ┆           │
│ Fire       ┆ Low       ┆ Jeffrey    ┆ K        ┆ Brooklyn  ┆ Fire       ┆ 193363.0   ┆ Per Annum │
│ Department ┆           ┆            ┆          ┆           ┆ Medical    ┆            ┆           │
│            ┆           ┆            ┆          ┆           ┆ Officer    ┆            ┆           │
│ Fire       ┆ Lindell   ┆ Peter      ┆ A        ┆ Brooklyn  ┆ Fire       ┆ 95527.0    ┆ Per Annum │
│ Department ┆           ┆            ┆          ┆           ┆ Marshal    ┆            ┆           │
│ Fire       ┆ Beecher   ┆ Shenecia   ┆ null     ┆ Brooklyn  ┆ Fire       ┆ 193363.0   ┆ Per Annum │
│ Department ┆           ┆            ┆          ┆           ┆ Medical    ┆            ┆           │
│            ┆           ┆            ┆          ┆           ┆ Officer    ┆            ┆           │
│ Fire       ┆ Hurwitz   ┆ Karen      ┆ L        ┆ Brooklyn  ┆ Fire       ┆ 193363.0   ┆ Per Annum │
│ Department ┆           ┆            ┆          ┆           ┆ Medical    ┆            ┆           │
│            ┆           ┆            ┆          ┆           ┆ Officer    ┆            ┆           │
│ …          ┆ …         ┆ …          ┆ …        ┆ …         ┆ …          ┆ …          ┆ …         │
│ Fire       ┆ Martin    ┆ Dane       ┆ null     ┆ Queens    ┆ Firefighte ┆ 105146.0   ┆ Per Annum │
│ Department ┆           ┆            ┆          ┆           ┆ r          ┆            ┆           │
│ Fire       ┆ Mcveety   ┆ Timothy    ┆ R        ┆ Manhattan ┆ Firefighte ┆ 105146.0   ┆ Per Annum │
│ Department ┆           ┆            ┆          ┆           ┆ r          ┆            ┆           │
│ Fire       ┆ Powers    ┆ Daniel     ┆ W        ┆ Brooklyn  ┆ Firefighte ┆ 101590.0   ┆ Per Annum │
│ Department ┆           ┆            ┆          ┆           ┆ r          ┆            ┆           │
│ Fire       ┆ Margaria  ┆ Thomas     ┆ M        ┆ Brooklyn  ┆ Firefighte ┆ 101590.0   ┆ Per Annum │
│ Department ┆           ┆            ┆          ┆           ┆ r          ┆            ┆           │
│ Fire       ┆ Clarke    ┆ Brian      ┆ P        ┆ Manhattan ┆ Firefighte ┆ 105146.0   ┆ Per Annum │
│ Department ┆           ┆            ┆          ┆           ┆ r          ┆            ┆           │
└────────────┴───────────┴────────────┴──────────┴───────────┴────────────┴────────────┴───────────┘

### Lectura Adicional
- https://docs.pola.rs/user-guide/expressions/strings/#check-for-the-existence-of-a-pattern
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.contains.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.contains_any.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.starts_with.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.ends_with.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.lowercase.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.to_uppercase.html

## Expresiones Regulares
- Una expresión regular es un patrón de búsqueda para texto.
- Una expresión regular usa símbolos para designar un patrón de coincidencia (cualquier dígito, un carácter, un espacio, etc).
- Las expresiones regulares pueden construir patrones de búsqueda más complejos (por ejemplo, "exactamente 2 dígitos seguidos de un espacio y cualquier carácter entre 'a' y 'e'").

In [ ]:
nyc = pl.read_csv("nyc.csv").with_columns(
    pl.col(pl.String).str.strip_chars().str.to_titlecase()
)
nyc.head(2)

shape: (2, 8)
┌──────────────┬───────────┬────────────┬──────────┬──────────┬──────────────┬─────────┬───────────┐
│ Agency Name  ┆ Last Name ┆ First Name ┆ Mid Init ┆ Borough  ┆ Title        ┆ Base    ┆ Pay Basis │
│ ---          ┆ ---       ┆ ---        ┆ ---      ┆ ---      ┆ ---          ┆ Salary  ┆ ---       │
│ str          ┆ str       ┆ str        ┆ str      ┆ str      ┆ str          ┆ ---     ┆ str       │
│              ┆           ┆            ┆          ┆          ┆              ┆ f64     ┆           │
╞══════════════╪═══════════╪════════════╪══════════╪══════════╪══════════════╪═════════╪═══════════╡
│ Office Of    ┆ Berezin   ┆ Mikhail    ┆ null     ┆ Brooklyn ┆ Emergency    ┆ 86005.0 ┆ Per Annum │
│ Emergency    ┆           ┆            ┆          ┆          ┆ Preparedness ┆         ┆           │
│ Management   ┆           ┆            ┆          ┆          ┆ Manager      ┆         ┆           │
│ Office Of    ┆ Geager    ┆ Veronica   ┆ M        ┆ Brooklyn ┆ Emergency    ┆ 86005.0 ┆ Per Annum │
│ Emergency    ┆           ┆            ┆          ┆          ┆ Preparedness ┆         ┆           │
│ Management   ┆           ┆            ┆          ┆          ┆ Manager      ┆         ┆           │
└──────────────┴───────────┴────────────┴──────────┴──────────┴──────────────┴─────────┴───────────┘

- La mayoría de los métodos de cadena bajo `str` admiten argumentos de expresiones regulares.
- Usa cadenas crudas (raw strings) para expresiones regulares. Una cadena cruda le dice a Python que interprete cada carácter literalmente.
- Por ejemplo, Python tratará `\n` como una barra invertida seguida de `n` en lugar de como un carácter de nueva línea.
- Las cadenas crudas previenen conflictos entre la sintaxis de expresiones regulares y los caracteres de escape de Python.
- El siguiente ejemplo usa regex para identificar cualquier cadena que contenga _algún_ dígito.

In [ ]:
nyc.filter(pl.col("Title").str.contains(r"\d")).select(
    pl.col("Title")
).to_series().to_list()[:10]

['Customer Information Representative Ma L 1549',
 'Customer Information Representative Ma L 1549',
 'Customer Information Representative Ma L 1549',
 'Customer Information Representative Ma L 1549',
 'Customer Information Representative Ma L 1549',
 'Customer Information Representative Ma L 1549',
 'Legal Secretarial Assistant - Al 1 Only',
 'Legal Secretarial Assistant - Al 1 Only',
 'Legal Secretarial Assistant - Al 1 Only',
 'Customer Information Representative Ma L 1549']

- El siguiente ejemplo encuentra las cadenas con al menos 2 espacios en blanco seguidos.

In [ ]:
nyc.filter(pl.col("Title").str.contains(r"\s{2,}")).select(
    pl.col("Title")
).to_series().to_list()[:10]

['Principal Administrative Associate -  Non Supvr',
 'Principal Administrative Associate -  Non Supvr',
 'Principal Administrative Associate -  Non Supvr',
 'Principal Administrative Associate -  Non Supvr',
 'Principal Administrative Associate -  Non Supvr',
 'Principal Administrative Associate -  Non Supvr',
 'Principal Administrative Associate -  Non Supvr',
 'Principal Administrative Associate -  Non Supvr',
 'Principal Administrative Associate -  Non Supvr',
 'Principal Administrative Associate -  Non Supvr']

### Lectura Adicional
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.contains.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.strip_chars.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.to_titlecase.html

## Grupos de Captura
- Un grupo de captura es una porción designada de la expresión regular.
- Polars puede extraer un valor coincidente a través del nombre de su grupo de captura.

In [ ]:
nyc = pl.read_csv("nyc.csv").with_columns(
    pl.col(pl.String).str.strip_chars().str.to_titlecase()
)
nyc.head(2)

shape: (2, 8)
┌──────────────┬───────────┬────────────┬──────────┬──────────┬──────────────┬─────────┬───────────┐
│ Agency Name  ┆ Last Name ┆ First Name ┆ Mid Init ┆ Borough  ┆ Title        ┆ Base    ┆ Pay Basis │
│ ---          ┆ ---       ┆ ---        ┆ ---      ┆ ---      ┆ ---          ┆ Salary  ┆ ---       │
│ str          ┆ str       ┆ str        ┆ str      ┆ str      ┆ str          ┆ ---     ┆ str       │
│              ┆           ┆            ┆          ┆          ┆              ┆ f64     ┆           │
╞══════════════╪═══════════╪════════════╪══════════╪══════════╪══════════════╪═════════╪═══════════╡
│ Office Of    ┆ Berezin   ┆ Mikhail    ┆ null     ┆ Brooklyn ┆ Emergency    ┆ 86005.0 ┆ Per Annum │
│ Emergency    ┆           ┆            ┆          ┆          ┆ Preparedness ┆         ┆           │
│ Management   ┆           ┆            ┆          ┆          ┆ Manager      ┆         ┆           │
│ Office Of    ┆ Geager    ┆ Veronica   ┆ M        ┆ Brooklyn ┆ Emergency    ┆ 86005.0 ┆ Per Annum │
│ Emergency    ┆           ┆            ┆          ┆          ┆ Preparedness ┆         ┆           │
│ Management   ┆           ┆            ┆          ┆          ┆ Manager      ┆         ┆           │
└──────────────┴───────────┴────────────┴──────────┴──────────┴──────────────┴─────────┴───────────┘

- El método `str.extract` extrae el contenido de un grupo de captura.
- Digamos que queremos identificar los varios _tipos_ de mecánicos que trabajan en la ciudad de Nueva York.
- Queremos extraer la _palabra_ antes de "mechanic" para las entradas en la columna `"Title"`.
- Definiremos esa palabra antes de "mechanic" como un grupo de captura.
- `(?i)` es un patrón que hace la búsqueda insensible a mayúsculas/minúsculas. Es un ejemplo de [inline flag](https://docs.python.org/3/library/re.html#flags).
- `\w+` es un patrón para "1 o más caracteres de palabra (`[A-Za-z0-9_]`)".
- El grupo de captura 0 será la coincidencia completa (los caracteres de palabra, el espacio y `mechanic`).

In [ ]:
nyc.select(
    pl.col("Title"),
    pl.col("Title")
    .str.extract(r"(?i)(\w+)\smechanic", group_index=0)
    .alias("mechanic_type"),
)

shape: (6_225_611, 2)
┌─────────────────────────────────┬───────────────────┐
│ Title                           ┆ mechanic_type     │
│ ---                             ┆ ---               │
│ str                             ┆ str               │
╞═════════════════════════════════╪═══════════════════╡
│ Emergency Preparedness Manager  ┆ null              │
│ Emergency Preparedness Manager  ┆ null              │
│ Emergency Preparedness Manager  ┆ null              │
│ Emergency Preparedness Manager  ┆ null              │
│ Emergency Preparedness Manager  ┆ null              │
│ …                               ┆ …                 │
│ Supervisor Electrician          ┆ null              │
│ Supervisor Elevator Mechanic    ┆ Elevator Mechanic │
│ Supervisor Elevator Mechanic    ┆ Elevator Mechanic │
│ Administrative Housing Superin… ┆ null              │
│ Administrative Housing Manager  ┆ null              │
└─────────────────────────────────┴───────────────────┘

- El índice 1 capturará el primer y único grupo de captura.
- El grupo de captura es el contenido correspondiente a `\w+` (uno o más caracteres) dentro de los paréntesis.

In [ ]:
nyc.select(
    pl.col("Title"),
    pl.col("Title")
    .str.extract(r"(?i)(\w+)\smechanic", group_index=1)
    .alias("mechanic_type"),
).filter(pl.col("mechanic_type").is_not_null())

shape: (25_338, 2)
┌──────────────────────────────┬───────────────┐
│ Title                        ┆ mechanic_type │
│ ---                          ┆ ---           │
│ str                          ┆ str           │
╞══════════════════════════════╪═══════════════╡
│ Radio Repair Mechanic        ┆ Repair        │
│ Radio Repair Mechanic        ┆ Repair        │
│ Radio Repair Mechanic        ┆ Repair        │
│ Radio Repair Mechanic        ┆ Repair        │
│ Radio Repair Mechanic        ┆ Repair        │
│ …                            ┆ …             │
│ Elevator Mechanic            ┆ Elevator      │
│ Elevator Mechanic            ┆ Elevator      │
│ Elevator Mechanic            ┆ Elevator      │
│ Supervisor Elevator Mechanic ┆ Elevator      │
│ Supervisor Elevator Mechanic ┆ Elevator      │
└──────────────────────────────┴───────────────┘

### Lectura Adicional
- https://docs.pola.rs/user-guide/expressions/strings/#regex-specification
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.extract.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.strip_chars.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.to_titlecase.html

## Reemplazo de Valores

In [ ]:
nyc = pl.read_csv("nyc.csv").with_columns(
    pl.col(pl.String).str.strip_chars().str.to_titlecase()
)
nyc.head(2)

shape: (2, 8)
┌──────────────┬───────────┬────────────┬──────────┬──────────┬──────────────┬─────────┬───────────┐
│ Agency Name  ┆ Last Name ┆ First Name ┆ Mid Init ┆ Borough  ┆ Title        ┆ Base    ┆ Pay Basis │
│ ---          ┆ ---       ┆ ---        ┆ ---      ┆ ---      ┆ ---          ┆ Salary  ┆ ---       │
│ str          ┆ str       ┆ str        ┆ str      ┆ str      ┆ str          ┆ ---     ┆ str       │
│              ┆           ┆            ┆          ┆          ┆              ┆ f64     ┆           │
╞══════════════╪═══════════╪════════════╪══════════╪══════════╪══════════════╪═════════╪═══════════╡
│ Office Of    ┆ Berezin   ┆ Mikhail    ┆ null     ┆ Brooklyn ┆ Emergency    ┆ 86005.0 ┆ Per Annum │
│ Emergency    ┆           ┆            ┆          ┆          ┆ Preparedness ┆         ┆           │
│ Management   ┆           ┆            ┆          ┆          ┆ Manager      ┆         ┆           │
│ Office Of    ┆ Geager    ┆ Veronica   ┆ M        ┆ Brooklyn ┆ Emergency    ┆ 86005.0 ┆ Per Annum │
│ Emergency    ┆           ┆            ┆          ┆          ┆ Preparedness ┆         ┆           │
│ Management   ┆           ┆            ┆          ┆          ┆ Manager      ┆         ┆           │
└──────────────┴───────────┴────────────┴──────────┴──────────┴──────────────┴─────────┴───────────┘

- El método `str.replace` reemplaza la primera ocurrencia de una cadena con otra cadena.

In [ ]:
nyc.select(
    pl.col("Agency Name"),
    pl.col("Agency Name")
    .str.replace("Office Of", "Department of")
    .alias("Agency Name 2"),
)

NameError: name 'nyc' is not defined

- El método `str.replace_all` reemplaza _todas_ las ocurrencias de la subcadena.

In [ ]:
nyc.select(
    pl.col("Agency Name"),
    pl.col("Agency Name").str.replace("Of", "!!").alias("replace"),
    pl.col("Agency Name").str.replace_all("Of", "!!").alias("replace_all"),
)

shape: (6_225_611, 3)
┌────────────────────────────────┬────────────────────────────────┬────────────────────────────────┐
│ Agency Name                    ┆ replace                        ┆ replace_all                    │
│ ---                            ┆ ---                            ┆ ---                            │
│ str                            ┆ str                            ┆ str                            │
╞════════════════════════════════╪════════════════════════════════╪════════════════════════════════╡
│ Office Of Emergency Management ┆ !!fice Of Emergency Management ┆ !!fice !! Emergency Management │
│ Office Of Emergency Management ┆ !!fice Of Emergency Management ┆ !!fice !! Emergency Management │
│ Office Of Emergency Management ┆ !!fice Of Emergency Management ┆ !!fice !! Emergency Management │
│ Office Of Emergency Management ┆ !!fice Of Emergency Management ┆ !!fice !! Emergency Management │
│ Office Of Emergency Management ┆ !!fice Of Emergency Management ┆ !!fice !! Emergency Management │
│ …                              ┆ …                              ┆ …                              │
│ Nyc Housing Authority          ┆ Nyc Housing Authority          ┆ Nyc Housing Authority          │
│ Nyc Housing Authority          ┆ Nyc Housing Authority          ┆ Nyc Housing Authority          │
│ Nyc Housing Authority          ┆ Nyc Housing Authority          ┆ Nyc Housing Authority          │
│ Nyc Housing Authority          ┆ Nyc Housing Authority          ┆ Nyc Housing Authority          │
│ Nyc Housing Authority          ┆ Nyc Housing Authority          ┆ Nyc Housing Authority          │
└────────────────────────────────┴────────────────────────────────┴────────────────────────────────┘

- Polars admite expresiones regulares como argumentos.

In [ ]:
nyc.select(
    pl.col("Agency Name"),
    pl.col("Agency Name").str.replace(r"(?i)em", "!!").alias("replace"),
    pl.col("Agency Name").str.replace_all(r"(?i)em", "!!").alias("replace_all"),
)

shape: (6_225_611, 3)
┌────────────────────────────────┬────────────────────────────────┬────────────────────────────────┐
│ Agency Name                    ┆ replace                        ┆ replace_all                    │
│ ---                            ┆ ---                            ┆ ---                            │
│ str                            ┆ str                            ┆ str                            │
╞════════════════════════════════╪════════════════════════════════╪════════════════════════════════╡
│ Office Of Emergency Management ┆ Office Of !!ergency Management ┆ Office Of !!ergency Manag!!ent │
│ Office Of Emergency Management ┆ Office Of !!ergency Management ┆ Office Of !!ergency Manag!!ent │
│ Office Of Emergency Management ┆ Office Of !!ergency Management ┆ Office Of !!ergency Manag!!ent │
│ Office Of Emergency Management ┆ Office Of !!ergency Management ┆ Office Of !!ergency Manag!!ent │
│ Office Of Emergency Management ┆ Office Of !!ergency Management ┆ Office Of !!ergency Manag!!ent │
│ …                              ┆ …                              ┆ …                              │
│ Nyc Housing Authority          ┆ Nyc Housing Authority          ┆ Nyc Housing Authority          │
│ Nyc Housing Authority          ┆ Nyc Housing Authority          ┆ Nyc Housing Authority          │
│ Nyc Housing Authority          ┆ Nyc Housing Authority          ┆ Nyc Housing Authority          │
│ Nyc Housing Authority          ┆ Nyc Housing Authority          ┆ Nyc Housing Authority          │
│ Nyc Housing Authority          ┆ Nyc Housing Authority          ┆ Nyc Housing Authority          │
└────────────────────────────────┴────────────────────────────────┴────────────────────────────────┘

### Lectura Adicional
- https://docs.pola.rs/user-guide/expressions/strings/#replace-a-pattern
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.replace.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.replace_all.html

---
# Ejercicios

## Ejercicio 1
Carga el dataset `nyc.csv` y normaliza todas las columnas de texto: elimina los espacios en blanco al inicio y al final, y convierte los valores a formato título. Luego, filtra las filas donde el `Borough` sea `"Manhattan"` y muestra las primeras 5 filas.

## Ejercicio 2
Usando el dataset normalizado, crea una nueva columna llamada `"Agency Code"` que contenga los primeros 5 caracteres de la columna `"Agency Name"` en mayúsculas. Muestra solo las columnas `"Agency Name"` y `"Agency Code"` (sin duplicados).

## Ejercicio 3
Filtra los empleados cuyo `"Title"` comience con `"Police"` o termine con `"Officer"`. Muestra las columnas `"First Name"`, `"Last Name"` y `"Title"` de las primeras 10 filas.

## Ejercicio 4
Usa una expresión regular para extraer la primera palabra del `"Title"` de cada empleado. Crea una columna llamada `"Primera Palabra"` con el resultado. Filtra las filas donde `"Primera Palabra"` no sea nula y muestra los valores únicos ordenados alfabéticamente (primeras 20 filas).

## Ejercicio 5
En la columna `"Agency Name"`, reemplaza todas las ocurrencias de `"Of"` por `"De"` y elimina el prefijo `"Department De "` del resultado. Muestra los valores únicos de la columna resultante, ordenados alfabéticamente (primeras 15 filas).