# DataFrames III - Filtrado
- **Filtrar** significa seleccionar un subconjunto de filas de un `DataFrame` que cumplan una condición.

In [ ]:
import polars as pl

## Presentación del Conjunto de Datos
- El CSV `coffee_sales` almacena transacciones de una cafetería ficticia.
- Polars importará la columna `time_of_purchase` como cadenas de texto.
- Usa el parámetro `try_parse_dates` para convertir columnas de texto en fechas/horas.

In [ ]:
coffees = pl.read_csv("coffee_sales.csv", try_parse_dates=True).sort("time_of_purchase")
coffees.head(5)

shape: (5, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true  ┆ Christopher ┆ 3.1   │
│ 01:53:30           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 20   ┆ true  ┆ Christopher ┆ 4.29  │
│ 02:39:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Downtown     ┆ Mocha       ┆ Almond    ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.85  │
│ 07:52:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Midtown West ┆ null        ┆ Soy       ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.05  │
│ 10:02:41           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ SoHo         ┆ Flat White  ┆ Oat       ┆ 12   ┆ false ┆ Danielle    ┆ 3.74  │
│ 15:07:27           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

## El Método filter
- El método `filter` extrae un subconjunto de filas del `DataFrame` que cumplan una condición.
- El método `filter` acepta una expresión booleana (una que produce una columna de booleanos).
- El método `filter` conservará las filas con valor `true` y excluirá las filas con valor `false`.
- Polars soporta los operadores de comparación estándar como `==`, `!=`, `>`, `<`, entre otros.
- Las comparaciones booleanas con `null` se evaluarán como `null`.

In [ ]:
coffees = pl.read_csv("coffee_sales.csv", try_parse_dates=True).sort("time_of_purchase")
coffees.head(2)

shape: (2, 8)
┌─────────────────────┬──────────────┬─────────────┬───────────┬──────┬──────┬─────────────┬───────┐
│ time_of_purchase    ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced ┆ barista     ┆ price │
│ ---                 ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---  ┆ ---         ┆ ---   │
│ datetime[μs]        ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool ┆ str         ┆ f64   │
╞═════════════════════╪══════════════╪═════════════╪═══════════╪══════╪══════╪═════════════╪═══════╡
│ 2025-01-01 01:53:30 ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true ┆ Christopher ┆ 3.1   │
│ 2025-01-01 02:39:54 ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 20   ┆ true ┆ Christopher ┆ 4.29  │
└─────────────────────┴──────────────┴─────────────┴───────────┴──────┴──────┴─────────────┴───────┘

- El operador `==` compara la igualdad de cada valor de fila con una constante.
- El método `eq` es equivalente a `==`.

In [ ]:
5 == 10

False

In [ ]:
# coffees.select(
#     pl.col("coffee_name"),
#     (pl.col("coffee_name") == "Flat White").alias("is_flat_white"),
#     pl.col("coffee_name").eq("Flat White").alias("is_flat_white_eq"),
# )

# is_flat_white = pl.col("coffee_name").eq("Flat White").alias("is_flat_white_eq")

- Pasa la expresión booleana al método `filter`.

In [ ]:
# coffees.filter(pl.col("coffee_name") == "Flat White")
# coffees.filter(pl.col("coffee_name").eq("Flat White"))
coffees.filter(is_flat_white)

shape: (155, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 20   ┆ true  ┆ Christopher ┆ 4.29  │
│ 02:39:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ SoHo         ┆ Flat White  ┆ Oat       ┆ 12   ┆ false ┆ Danielle    ┆ 3.74  │
│ 15:07:27           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 12   ┆ true  ┆ Joshua      ┆ 2.6   │
│ 01:50:26           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-03         ┆ Midtown West ┆ Flat White  ┆ Soy       ┆ 12   ┆ true  ┆ Anthony     ┆ 3.69  │
│ 10:57:47           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-07         ┆ Downtown     ┆ Flat White  ┆ 2%        ┆ 16   ┆ false ┆ Jill        ┆ 5.08  │
│ 23:54:11           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-01         ┆ Midtown West ┆ Flat White  ┆ Oat       ┆ 16   ┆ false ┆ Erica       ┆ 6.21  │
│ 03:42:07           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-02         ┆ Downtown     ┆ Flat White  ┆ Oat       ┆ 12   ┆ false ┆ Erica       ┆ 5.76  │
│ 13:54:05           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ East Village ┆ Flat White  ┆ Coconut   ┆ 16   ┆ false ┆ Angel       ┆ 5.23  │
│ 11:23:23           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ SoHo         ┆ Flat White  ┆ Oat       ┆ 20   ┆ false ┆ Danielle    ┆ 3.47  │
│ 14:36:47           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ East Village ┆ Flat White  ┆ Oat       ┆ 20   ┆ false ┆ Erica       ┆ 4.75  │
│ 14:51:19           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

In [ ]:
# coffees.filter(pl.col("location") == "SoHo")
# coffees.filter(pl.col("location").eq("Soho"))

shape: (0, 8)
┌──────────────────┬──────────┬─────────────┬───────────┬──────┬──────┬─────────┬───────┐
│ time_of_purchase ┆ location ┆ coffee_name ┆ milk_type ┆ size ┆ iced ┆ barista ┆ price │
│ ---              ┆ ---      ┆ ---         ┆ ---       ┆ ---  ┆ ---  ┆ ---     ┆ ---   │
│ datetime[μs]     ┆ str      ┆ str         ┆ str       ┆ i64  ┆ bool ┆ str     ┆ f64   │
╞══════════════════╪══════════╪═════════════╪═══════════╪══════╪══════╪═════════╪═══════╡
└──────────────────┴──────────┴─────────────┴───────────┴──────┴──────┴─────────┴───────┘

### Lectura Adicional
- https://docs.pola.rs/user-guide/getting-started/#filter
- https://docs.pola.rs/user-guide/concepts/expressions-and-contexts/#filter
- https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.filter.html

## Filtrado con Operadores Relacionales

In [ ]:
coffees = pl.read_csv("coffee_sales.csv", try_parse_dates=True).sort("time_of_purchase")
coffees.head(2)

shape: (2, 8)
┌─────────────────────┬──────────────┬─────────────┬───────────┬──────┬──────┬─────────────┬───────┐
│ time_of_purchase    ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced ┆ barista     ┆ price │
│ ---                 ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---  ┆ ---         ┆ ---   │
│ datetime[μs]        ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool ┆ str         ┆ f64   │
╞═════════════════════╪══════════════╪═════════════╪═══════════╪══════╪══════╪═════════════╪═══════╡
│ 2025-01-01 01:53:30 ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true ┆ Christopher ┆ 3.1   │
│ 2025-01-01 02:39:54 ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 20   ┆ true ┆ Christopher ┆ 4.29  │
└─────────────────────┴──────────────┴─────────────┴───────────┴──────┴──────┴─────────────┴───────┘

- El operador `!=` compara la desigualdad de cada valor de columna con una constante.
- El método `ne` es el método equivalente.

In [ ]:
coffees.filter(pl.col("milk_type") != "Oat")
# coffees.filter(pl.col("milk_type").ne("Oat"))

shape: (840, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true  ┆ Christopher ┆ 3.1   │
│ 01:53:30           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Downtown     ┆ Mocha       ┆ Almond    ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.85  │
│ 07:52:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Midtown West ┆ null        ┆ Soy       ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.05  │
│ 10:02:41           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Midtown West ┆ Americano   ┆ 2%        ┆ 20   ┆ false ┆ Erica       ┆ 4.83  │
│ 16:31:26           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ East Village ┆ Espresso    ┆ 2%        ┆ 20   ┆ true  ┆ Joshua      ┆ 4.79  │
│ 03:28:39           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-07         ┆ Midtown West ┆ Espresso    ┆ Almond    ┆ 12   ┆ true  ┆ Joshua      ┆ 4.54  │
│ 04:13:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-07         ┆ East Village ┆ Americano   ┆ Coconut   ┆ 12   ┆ false ┆ Angel       ┆ 4.82  │
│ 10:28:12           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Espresso    ┆ Almond    ┆ 16   ┆ false ┆ Danielle    ┆ 5.17  │
│ 06:12:20           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Latte       ┆ Almond    ┆ 12   ┆ false ┆ Danielle    ┆ 2.87  │
│ 10:56:38           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ Uptown       ┆ Espresso    ┆ Almond    ┆ 20   ┆ false ┆ Joshua      ┆ 3.45  │
│ 13:34:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

- Polars soporta los operadores matemáticos estándar para comparaciones:
    - `<` o `lt` para menor que
    - `<=` o `le` para menor o igual que
    - `>` o `gt` para mayor que
    - `>=` o `ge` para mayor o igual que

In [ ]:
coffees.filter(pl.col("price") > 5)
# coffees.filter(pl.col("price").gt(5))

# coffees.filter(pl.col("price") < 5)
# coffees.filter(pl.col("price").lt(5))

# coffees.filter(pl.col("price") >= 5)
# coffees.filter(pl.col("price").ge(5))

# coffees.filter(pl.col("price") <= 5)
# coffees.filter(pl.col("price").le(5))

shape: (383, 8)
┌─────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬──────────┬───────┐
│ time_of_purchase    ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista  ┆ price │
│ ---                 ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---      ┆ ---   │
│ datetime[μs]        ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str      ┆ f64   │
╞═════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪══════════╪═══════╡
│ 2025-01-01 07:52:54 ┆ Downtown     ┆ Mocha       ┆ Almond    ┆ 12   ┆ false ┆ Jeffrey  ┆ 5.85  │
│ 2025-01-01 10:02:41 ┆ Midtown West ┆ null        ┆ Soy       ┆ 12   ┆ false ┆ Jeffrey  ┆ 5.05  │
│ 2025-01-02 06:17:11 ┆ SoHo         ┆ Mocha       ┆ Coconut   ┆ 20   ┆ true  ┆ Joshua   ┆ 5.67  │
│ 2025-01-02 09:30:42 ┆ East Village ┆ Macchiato   ┆ Whole     ┆ 12   ┆ false ┆ Robert   ┆ 6.24  │
│ 2025-01-02 19:24:47 ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 12   ┆ false ┆ Jill     ┆ 5.69  │
│ …                   ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …        ┆ …     │
│ 2025-06-06 11:23:23 ┆ East Village ┆ Flat White  ┆ Coconut   ┆ 16   ┆ false ┆ Angel    ┆ 5.23  │
│ 2025-06-06 17:29:25 ┆ Midtown West ┆ Americano   ┆ 2%        ┆ 12   ┆ false ┆ Jeffrey  ┆ 5.96  │
│ 2025-06-06 21:39:23 ┆ Downtown     ┆ Macchiato   ┆ Whole     ┆ 12   ┆ false ┆ Robert   ┆ 6.26  │
│ 2025-06-07 10:21:56 ┆ Downtown     ┆ Macchiato   ┆ Oat       ┆ 20   ┆ false ┆ Danielle ┆ 6.49  │
│ 2025-06-08 06:12:20 ┆ East Village ┆ Espresso    ┆ Almond    ┆ 16   ┆ false ┆ Danielle ┆ 5.17  │
└─────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴──────────┴───────┘

### Lectura Adicional
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.eq.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.ne.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.lt.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.le.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.gt.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.ge.html

## Filtrado con Valores Faltantes
- El método `filter` excluye los valores `null` por defecto.
- Polars tiene una familia de métodos de comparación que terminan en `_missing` que incluyen valores nulos.
- Por ejemplo, el método `eq_missing` compara la igualdad de un `null` con el argumento.

In [ ]:
coffees = pl.read_csv("coffee_sales.csv", try_parse_dates=True).sort("time_of_purchase")
coffees.head(2)

shape: (2, 8)
┌─────────────────────┬──────────────┬─────────────┬───────────┬──────┬──────┬─────────────┬───────┐
│ time_of_purchase    ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced ┆ barista     ┆ price │
│ ---                 ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---  ┆ ---         ┆ ---   │
│ datetime[μs]        ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool ┆ str         ┆ f64   │
╞═════════════════════╪══════════════╪═════════════╪═══════════╪══════╪══════╪═════════════╪═══════╡
│ 2025-01-01 01:53:30 ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true ┆ Christopher ┆ 3.1   │
│ 2025-01-01 02:39:54 ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 20   ┆ true ┆ Christopher ┆ 4.29  │
└─────────────────────┴──────────────┴─────────────┴───────────┴──────┴──────┴─────────────┴───────┘

In [ ]:
coffees.null_count()

shape: (1, 8)
┌──────────────────┬──────────┬─────────────┬───────────┬──────┬──────┬─────────┬───────┐
│ time_of_purchase ┆ location ┆ coffee_name ┆ milk_type ┆ size ┆ iced ┆ barista ┆ price │
│ ---              ┆ ---      ┆ ---         ┆ ---       ┆ ---  ┆ ---  ┆ ---     ┆ ---   │
│ u32              ┆ u32      ┆ u32         ┆ u32       ┆ u32  ┆ u32  ┆ u32     ┆ u32   │
╞══════════════════╪══════════╪═════════════╪═══════════╪══════╪══════╪═════════╪═══════╡
│ 0                ┆ 0        ┆ 6           ┆ 0         ┆ 0    ┆ 0    ┆ 0       ┆ 0     │
└──────────────────┴──────────┴─────────────┴───────────┴──────┴──────┴─────────┴───────┘

In [ ]:
coffees.filter(pl.col("coffee_name").ne("Mocha"))

shape: (860, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true  ┆ Christopher ┆ 3.1   │
│ 01:53:30           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 20   ┆ true  ┆ Christopher ┆ 4.29  │
│ 02:39:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ SoHo         ┆ Flat White  ┆ Oat       ┆ 12   ┆ false ┆ Danielle    ┆ 3.74  │
│ 15:07:27           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Midtown West ┆ Americano   ┆ 2%        ┆ 20   ┆ false ┆ Erica       ┆ 4.83  │
│ 16:31:26           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 12   ┆ true  ┆ Joshua      ┆ 2.6   │
│ 01:50:26           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-07         ┆ Downtown     ┆ Macchiato   ┆ Oat       ┆ 20   ┆ false ┆ Danielle    ┆ 6.49  │
│ 10:21:56           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-07         ┆ East Village ┆ Americano   ┆ Coconut   ┆ 12   ┆ false ┆ Angel       ┆ 4.82  │
│ 10:28:12           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Espresso    ┆ Almond    ┆ 16   ┆ false ┆ Danielle    ┆ 5.17  │
│ 06:12:20           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Latte       ┆ Almond    ┆ 12   ┆ false ┆ Danielle    ┆ 2.87  │
│ 10:56:38           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ Uptown       ┆ Espresso    ┆ Almond    ┆ 20   ┆ false ┆ Joshua      ┆ 3.45  │
│ 13:34:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

In [ ]:
# Conserva todo lo que no sea explícitamente "Mocha", incluyendo los valores faltantes.
coffees.filter(pl.col("coffee_name").ne_missing("Mocha"))

shape: (866, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true  ┆ Christopher ┆ 3.1   │
│ 01:53:30           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 20   ┆ true  ┆ Christopher ┆ 4.29  │
│ 02:39:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Midtown West ┆ null        ┆ Soy       ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.05  │
│ 10:02:41           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ SoHo         ┆ Flat White  ┆ Oat       ┆ 12   ┆ false ┆ Danielle    ┆ 3.74  │
│ 15:07:27           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Midtown West ┆ Americano   ┆ 2%        ┆ 20   ┆ false ┆ Erica       ┆ 4.83  │
│ 16:31:26           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-07         ┆ Downtown     ┆ Macchiato   ┆ Oat       ┆ 20   ┆ false ┆ Danielle    ┆ 6.49  │
│ 10:21:56           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-07         ┆ East Village ┆ Americano   ┆ Coconut   ┆ 12   ┆ false ┆ Angel       ┆ 4.82  │
│ 10:28:12           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Espresso    ┆ Almond    ┆ 16   ┆ false ┆ Danielle    ┆ 5.17  │
│ 06:12:20           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Latte       ┆ Almond    ┆ 12   ┆ false ┆ Danielle    ┆ 2.87  │
│ 10:56:38           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ Uptown       ┆ Espresso    ┆ Almond    ┆ 20   ┆ false ┆ Joshua      ┆ 3.45  │
│ 13:34:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

- Podemos pasar `None` para comparar la igualdad con valores `null`/faltantes...

In [ ]:
# coffees.filter(pl.col("coffee_name").eq(None))
coffees.filter(pl.col("coffee_name").eq_missing(None))

shape: (6, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Midtown West ┆ null        ┆ Soy       ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.05  │
│ 10:02:41           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-07         ┆ Downtown     ┆ null        ┆ Oat       ┆ 16   ┆ false ┆ Christopher ┆ 3.92  │
│ 00:36:36           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-29         ┆ Downtown     ┆ null        ┆ Oat       ┆ 16   ┆ true  ┆ Jill        ┆ 6.09  │
│ 15:43:56           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-02-22         ┆ SoHo         ┆ null        ┆ 2%        ┆ 20   ┆ true  ┆ Robert      ┆ 2.72  │
│ 23:58:14           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-04-09         ┆ Downtown     ┆ null        ┆ Whole     ┆ 16   ┆ true  ┆ Angel       ┆ 2.8   │
│ 22:00:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-05-10         ┆ SoHo         ┆ null        ┆ 2%        ┆ 20   ┆ false ┆ Erica       ┆ 4.4   │
│ 16:28:05           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

- ...pero la solución más idiomática es el método `is_null`.
- El método `is_null` devuelve una `Series` booleana donde `true` representa un valor faltante.

In [ ]:
coffees.filter(pl.col("coffee_name").is_null())

shape: (6, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Midtown West ┆ null        ┆ Soy       ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.05  │
│ 10:02:41           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-07         ┆ Downtown     ┆ null        ┆ Oat       ┆ 16   ┆ false ┆ Christopher ┆ 3.92  │
│ 00:36:36           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-29         ┆ Downtown     ┆ null        ┆ Oat       ┆ 16   ┆ true  ┆ Jill        ┆ 6.09  │
│ 15:43:56           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-02-22         ┆ SoHo         ┆ null        ┆ 2%        ┆ 20   ┆ true  ┆ Robert      ┆ 2.72  │
│ 23:58:14           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-04-09         ┆ Downtown     ┆ null        ┆ Whole     ┆ 16   ┆ true  ┆ Angel       ┆ 2.8   │
│ 22:00:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-05-10         ┆ SoHo         ┆ null        ┆ 2%        ┆ 20   ┆ false ┆ Erica       ┆ 4.4   │
│ 16:28:05           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

In [ ]:
coffees.filter(pl.col("coffee_name").ne_missing(None))

shape: (994, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true  ┆ Christopher ┆ 3.1   │
│ 01:53:30           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 20   ┆ true  ┆ Christopher ┆ 4.29  │
│ 02:39:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Downtown     ┆ Mocha       ┆ Almond    ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.85  │
│ 07:52:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ SoHo         ┆ Flat White  ┆ Oat       ┆ 12   ┆ false ┆ Danielle    ┆ 3.74  │
│ 15:07:27           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Midtown West ┆ Americano   ┆ 2%        ┆ 20   ┆ false ┆ Erica       ┆ 4.83  │
│ 16:31:26           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-07         ┆ Downtown     ┆ Macchiato   ┆ Oat       ┆ 20   ┆ false ┆ Danielle    ┆ 6.49  │
│ 10:21:56           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-07         ┆ East Village ┆ Americano   ┆ Coconut   ┆ 12   ┆ false ┆ Angel       ┆ 4.82  │
│ 10:28:12           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Espresso    ┆ Almond    ┆ 16   ┆ false ┆ Danielle    ┆ 5.17  │
│ 06:12:20           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Latte       ┆ Almond    ┆ 12   ┆ false ┆ Danielle    ┆ 2.87  │
│ 10:56:38           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ Uptown       ┆ Espresso    ┆ Almond    ┆ 20   ┆ false ┆ Joshua      ┆ 3.45  │
│ 13:34:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

In [ ]:
coffees.filter(pl.col("coffee_name").is_not_null())

shape: (994, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true  ┆ Christopher ┆ 3.1   │
│ 01:53:30           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 20   ┆ true  ┆ Christopher ┆ 4.29  │
│ 02:39:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Downtown     ┆ Mocha       ┆ Almond    ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.85  │
│ 07:52:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ SoHo         ┆ Flat White  ┆ Oat       ┆ 12   ┆ false ┆ Danielle    ┆ 3.74  │
│ 15:07:27           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Midtown West ┆ Americano   ┆ 2%        ┆ 20   ┆ false ┆ Erica       ┆ 4.83  │
│ 16:31:26           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-07         ┆ Downtown     ┆ Macchiato   ┆ Oat       ┆ 20   ┆ false ┆ Danielle    ┆ 6.49  │
│ 10:21:56           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-07         ┆ East Village ┆ Americano   ┆ Coconut   ┆ 12   ┆ false ┆ Angel       ┆ 4.82  │
│ 10:28:12           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Espresso    ┆ Almond    ┆ 16   ┆ false ┆ Danielle    ┆ 5.17  │
│ 06:12:20           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Latte       ┆ Almond    ┆ 12   ┆ false ┆ Danielle    ┆ 2.87  │
│ 10:56:38           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ Uptown       ┆ Espresso    ┆ Almond    ┆ 20   ┆ false ┆ Joshua      ┆ 3.45  │
│ 13:34:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

### Lectura Adicional
- https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.null_count.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.ne_missing.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.eq_missing.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.is_null.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.is_not_null.html

## Filtrado con Columnas Booleanas
- Polars imprime sus booleanos en minúsculas (`true`, `false`).
- Los booleanos de Python tienen la primera letra en mayúscula (`True`, `False`).
- _Podríamos_ comparar cada valor de una columna booleana con `True`.
- Pero un enfoque más limpio es pasar la columna booleana directamente al método `filter`.

In [ ]:
coffees = pl.read_csv("coffee_sales.csv", try_parse_dates=True).sort("time_of_purchase")
coffees.head()

shape: (5, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true  ┆ Christopher ┆ 3.1   │
│ 01:53:30           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 20   ┆ true  ┆ Christopher ┆ 4.29  │
│ 02:39:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Downtown     ┆ Mocha       ┆ Almond    ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.85  │
│ 07:52:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Midtown West ┆ null        ┆ Soy       ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.05  │
│ 10:02:41           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ SoHo         ┆ Flat White  ┆ Oat       ┆ 12   ┆ false ┆ Danielle    ┆ 3.74  │
│ 15:07:27           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

In [ ]:
# coffees.filter(pl.col("iced") == True)
# coffees.filter(pl.col("iced").eq(True))

coffees.filter(pl.col("iced"))

shape: (464, 8)
┌─────────────────────┬──────────────┬─────────────┬───────────┬──────┬──────┬─────────────┬───────┐
│ time_of_purchase    ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced ┆ barista     ┆ price │
│ ---                 ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---  ┆ ---         ┆ ---   │
│ datetime[μs]        ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool ┆ str         ┆ f64   │
╞═════════════════════╪══════════════╪═════════════╪═══════════╪══════╪══════╪═════════════╪═══════╡
│ 2025-01-01 01:53:30 ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true ┆ Christopher ┆ 3.1   │
│ 2025-01-01 02:39:54 ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 20   ┆ true ┆ Christopher ┆ 4.29  │
│ 2025-01-02 01:50:26 ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 12   ┆ true ┆ Joshua      ┆ 2.6   │
│ 2025-01-02 03:28:39 ┆ East Village ┆ Espresso    ┆ 2%        ┆ 20   ┆ true ┆ Joshua      ┆ 4.79  │
│ 2025-01-02 06:17:11 ┆ SoHo         ┆ Mocha       ┆ Coconut   ┆ 20   ┆ true ┆ Joshua      ┆ 5.67  │
│ …                   ┆ …            ┆ …           ┆ …         ┆ …    ┆ …    ┆ …           ┆ …     │
│ 2025-06-05 07:39:21 ┆ Midtown West ┆ Americano   ┆ Coconut   ┆ 12   ┆ true ┆ Anthony     ┆ 4.79  │
│ 2025-06-06 10:01:56 ┆ Uptown       ┆ Americano   ┆ 2%        ┆ 16   ┆ true ┆ Jill        ┆ 5.59  │
│ 2025-06-06 19:12:31 ┆ SoHo         ┆ Latte       ┆ Coconut   ┆ 16   ┆ true ┆ Erica       ┆ 4.96  │
│ 2025-06-06 22:28:52 ┆ Uptown       ┆ Cappuccino  ┆ Soy       ┆ 16   ┆ true ┆ Danielle    ┆ 3.33  │
│ 2025-06-07 04:13:09 ┆ Midtown West ┆ Espresso    ┆ Almond    ┆ 12   ┆ true ┆ Joshua      ┆ 4.54  │
└─────────────────────┴──────────────┴─────────────┴───────────┴──────┴──────┴─────────────┴───────┘

## Aplicando Lógica AND
- El operador `&` aplica lógica AND entre dos expresiones booleanas.
- Ambas condiciones deben cumplirse para que la evaluación sea verdadera.
- La lógica AND (`&`) se llama "conjunción" en matemáticas.

In [ ]:
coffees = pl.read_csv("coffee_sales.csv", try_parse_dates=True).sort("time_of_purchase")
coffees.head(2)

shape: (2, 8)
┌─────────────────────┬──────────────┬─────────────┬───────────┬──────┬──────┬─────────────┬───────┐
│ time_of_purchase    ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced ┆ barista     ┆ price │
│ ---                 ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---  ┆ ---         ┆ ---   │
│ datetime[μs]        ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool ┆ str         ┆ f64   │
╞═════════════════════╪══════════════╪═════════════╪═══════════╪══════╪══════╪═════════════╪═══════╡
│ 2025-01-01 01:53:30 ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true ┆ Christopher ┆ 3.1   │
│ 2025-01-01 02:39:54 ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 20   ┆ true ┆ Christopher ┆ 4.29  │
└─────────────────────┴──────────────┴─────────────┴───────────┴──────┴──────┴─────────────┴───────┘

- Envuelve cada expresión en paréntesis para aislarla. De lo contrario, Polars se confundirá.
- El siguiente ejemplo extrae las filas con `milk_type` "Soy" y `size` mayor que 18.

In [ ]:
coffees.filter((pl.col("milk_type") == "Soy") & (pl.col("size") > 18))

shape: (52, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true  ┆ Christopher ┆ 3.1   │
│ 01:53:30           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-04         ┆ Midtown West ┆ Espresso    ┆ Soy       ┆ 20   ┆ false ┆ Patricia    ┆ 5.79  │
│ 18:19:57           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-04         ┆ Uptown       ┆ Espresso    ┆ Soy       ┆ 20   ┆ false ┆ Joshua      ┆ 2.76  │
│ 18:46:05           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-10         ┆ East Village ┆ Americano   ┆ Soy       ┆ 20   ┆ false ┆ Jill        ┆ 4.87  │
│ 19:45:31           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-14         ┆ SoHo         ┆ Flat White  ┆ Soy       ┆ 20   ┆ true  ┆ Christopher ┆ 2.75  │
│ 18:13:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-05-20         ┆ Downtown     ┆ Macchiato   ┆ Soy       ┆ 20   ┆ true  ┆ Jeffrey     ┆ 5.93  │
│ 16:47:12           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-05-25         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true  ┆ Jeffrey     ┆ 6.3   │
│ 20:18:39           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-05-26         ┆ Downtown     ┆ Espresso    ┆ Soy       ┆ 20   ┆ true  ┆ Christopher ┆ 6.49  │
│ 12:49:07           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-05-29         ┆ Downtown     ┆ Americano   ┆ Soy       ┆ 20   ┆ true  ┆ Christopher ┆ 4.16  │
│ 17:02:49           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-04         ┆ Uptown       ┆ Espresso    ┆ Soy       ┆ 20   ┆ true  ┆ Jeffrey     ┆ 5.73  │
│ 10:34:43           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

- Los métodos permiten omitir los paréntesis.
- Alternativamente, asigna las expresiones a variables.

In [ ]:
# coffees.filter(pl.col("milk_type").eq("Soy") & pl.col("size").gt(18))

with_soy_milk = pl.col("milk_type") == "Soy"
with_size_greater_than_18 = pl.col("size") > 18
coffees.filter(with_soy_milk & with_size_greater_than_18)

shape: (52, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true  ┆ Christopher ┆ 3.1   │
│ 01:53:30           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-04         ┆ Midtown West ┆ Espresso    ┆ Soy       ┆ 20   ┆ false ┆ Patricia    ┆ 5.79  │
│ 18:19:57           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-04         ┆ Uptown       ┆ Espresso    ┆ Soy       ┆ 20   ┆ false ┆ Joshua      ┆ 2.76  │
│ 18:46:05           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-10         ┆ East Village ┆ Americano   ┆ Soy       ┆ 20   ┆ false ┆ Jill        ┆ 4.87  │
│ 19:45:31           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-14         ┆ SoHo         ┆ Flat White  ┆ Soy       ┆ 20   ┆ true  ┆ Christopher ┆ 2.75  │
│ 18:13:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-05-20         ┆ Downtown     ┆ Macchiato   ┆ Soy       ┆ 20   ┆ true  ┆ Jeffrey     ┆ 5.93  │
│ 16:47:12           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-05-25         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true  ┆ Jeffrey     ┆ 6.3   │
│ 20:18:39           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-05-26         ┆ Downtown     ┆ Espresso    ┆ Soy       ┆ 20   ┆ true  ┆ Christopher ┆ 6.49  │
│ 12:49:07           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-05-29         ┆ Downtown     ┆ Americano   ┆ Soy       ┆ 20   ┆ true  ┆ Christopher ┆ 4.16  │
│ 17:02:49           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-04         ┆ Uptown       ┆ Espresso    ┆ Soy       ┆ 20   ┆ true  ┆ Jeffrey     ┆ 5.73  │
│ 10:34:43           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

- El método `filter` soporta cualquier número de expresiones.

In [ ]:
# coffees.filter((pl.col("milk_type") == "Soy") & (pl.col("size") > 18) & pl.col("iced"))

coffees.filter(pl.col("milk_type").eq("Soy") & pl.col("size").gt(18) & pl.col("iced"))

shape: (24, 8)
┌─────────────────────┬──────────────┬─────────────┬───────────┬──────┬──────┬─────────────┬───────┐
│ time_of_purchase    ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced ┆ barista     ┆ price │
│ ---                 ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---  ┆ ---         ┆ ---   │
│ datetime[μs]        ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool ┆ str         ┆ f64   │
╞═════════════════════╪══════════════╪═════════════╪═══════════╪══════╪══════╪═════════════╪═══════╡
│ 2025-01-01 01:53:30 ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true ┆ Christopher ┆ 3.1   │
│ 2025-01-14 18:13:09 ┆ SoHo         ┆ Flat White  ┆ Soy       ┆ 20   ┆ true ┆ Christopher ┆ 2.75  │
│ 2025-01-21 15:54:37 ┆ Downtown     ┆ Cappuccino  ┆ Soy       ┆ 20   ┆ true ┆ Erica       ┆ 6.16  │
│ 2025-02-17 16:05:25 ┆ Uptown       ┆ Latte       ┆ Soy       ┆ 20   ┆ true ┆ Jill        ┆ 2.59  │
│ 2025-02-25 08:08:15 ┆ SoHo         ┆ Flat White  ┆ Soy       ┆ 20   ┆ true ┆ Danielle    ┆ 6.31  │
│ …                   ┆ …            ┆ …           ┆ …         ┆ …    ┆ …    ┆ …           ┆ …     │
│ 2025-05-20 16:47:12 ┆ Downtown     ┆ Macchiato   ┆ Soy       ┆ 20   ┆ true ┆ Jeffrey     ┆ 5.93  │
│ 2025-05-25 20:18:39 ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true ┆ Jeffrey     ┆ 6.3   │
│ 2025-05-26 12:49:07 ┆ Downtown     ┆ Espresso    ┆ Soy       ┆ 20   ┆ true ┆ Christopher ┆ 6.49  │
│ 2025-05-29 17:02:49 ┆ Downtown     ┆ Americano   ┆ Soy       ┆ 20   ┆ true ┆ Christopher ┆ 4.16  │
│ 2025-06-04 10:34:43 ┆ Uptown       ┆ Espresso    ┆ Soy       ┆ 20   ┆ true ┆ Jeffrey     ┆ 5.73  │
└─────────────────────┴──────────────┴─────────────┴───────────┴──────┴──────┴─────────────┴───────┘

### Lectura Adicional
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.and_.html

## Aplicando Lógica OR
- El operador `|` aplica lógica OR entre dos expresiones booleanas.
- Al menos una condición debe ser verdadera para que la evaluación final sea verdadera.

In [ ]:
coffees = pl.read_csv("coffee_sales.csv", try_parse_dates=True).sort("time_of_purchase")
coffees.head(2)

shape: (2, 8)
┌─────────────────────┬──────────────┬─────────────┬───────────┬──────┬──────┬─────────────┬───────┐
│ time_of_purchase    ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced ┆ barista     ┆ price │
│ ---                 ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---  ┆ ---         ┆ ---   │
│ datetime[μs]        ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool ┆ str         ┆ f64   │
╞═════════════════════╪══════════════╪═════════════╪═══════════╪══════╪══════╪═════════════╪═══════╡
│ 2025-01-01 01:53:30 ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true ┆ Christopher ┆ 3.1   │
│ 2025-01-01 02:39:54 ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 20   ┆ true ┆ Christopher ┆ 4.29  │
└─────────────────────┴──────────────┴─────────────┴───────────┴──────┴──────┴─────────────┴───────┘

- El siguiente ejemplo filtra las filas donde `price` es menor o igual a 3 o `location` es igual a "Downtown".

In [ ]:
coffees.filter((pl.col("price") <= 3) | (pl.col("location") == "Downtown"))

shape: (307, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Downtown     ┆ Mocha       ┆ Almond    ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.85  │
│ 07:52:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 12   ┆ true  ┆ Joshua      ┆ 2.6   │
│ 01:50:26           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Downtown     ┆ Latte       ┆ Soy       ┆ 16   ┆ false ┆ Anthony     ┆ 2.53  │
│ 21:03:50           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-03         ┆ SoHo         ┆ Macchiato   ┆ Oat       ┆ 12   ┆ true  ┆ Christopher ┆ 2.9   │
│ 05:30:19           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-04         ┆ Uptown       ┆ Espresso    ┆ Soy       ┆ 20   ┆ false ┆ Joshua      ┆ 2.76  │
│ 18:46:05           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-05         ┆ Downtown     ┆ Macchiato   ┆ 2%        ┆ 12   ┆ false ┆ Robert      ┆ 5.49  │
│ 18:41:12           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ Downtown     ┆ Americano   ┆ Coconut   ┆ 12   ┆ false ┆ Jeffrey     ┆ 2.8   │
│ 07:47:07           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ Downtown     ┆ Macchiato   ┆ Whole     ┆ 12   ┆ false ┆ Robert      ┆ 6.26  │
│ 21:39:23           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-07         ┆ Downtown     ┆ Macchiato   ┆ Oat       ┆ 20   ┆ false ┆ Danielle    ┆ 6.49  │
│ 10:21:56           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Latte       ┆ Almond    ┆ 12   ┆ false ┆ Danielle    ┆ 2.87  │
│ 10:56:38           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

- El método `le` es equivalente al símbolo `<=`.
- Los métodos permiten omitir los paréntesis.

In [ ]:
coffees.filter(pl.col("price").le(3) | pl.col("location").eq("Downtown"))

shape: (307, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Downtown     ┆ Mocha       ┆ Almond    ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.85  │
│ 07:52:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 12   ┆ true  ┆ Joshua      ┆ 2.6   │
│ 01:50:26           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Downtown     ┆ Latte       ┆ Soy       ┆ 16   ┆ false ┆ Anthony     ┆ 2.53  │
│ 21:03:50           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-03         ┆ SoHo         ┆ Macchiato   ┆ Oat       ┆ 12   ┆ true  ┆ Christopher ┆ 2.9   │
│ 05:30:19           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-04         ┆ Uptown       ┆ Espresso    ┆ Soy       ┆ 20   ┆ false ┆ Joshua      ┆ 2.76  │
│ 18:46:05           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-05         ┆ Downtown     ┆ Macchiato   ┆ 2%        ┆ 12   ┆ false ┆ Robert      ┆ 5.49  │
│ 18:41:12           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ Downtown     ┆ Americano   ┆ Coconut   ┆ 12   ┆ false ┆ Jeffrey     ┆ 2.8   │
│ 07:47:07           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ Downtown     ┆ Macchiato   ┆ Whole     ┆ 12   ┆ false ┆ Robert      ┆ 6.26  │
│ 21:39:23           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-07         ┆ Downtown     ┆ Macchiato   ┆ Oat       ┆ 20   ┆ false ┆ Danielle    ┆ 6.49  │
│ 10:21:56           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Latte       ┆ Almond    ┆ 12   ┆ false ┆ Danielle    ┆ 2.87  │
│ 10:56:38           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

- Para simplificar el código, asigna las expresiones a variables descriptivas.

In [ ]:
cheap_coffee = pl.col("price") <= 3
in_downtown = pl.col("location") == "Downtown"
coffees.filter(cheap_coffee | in_downtown)

shape: (307, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Downtown     ┆ Mocha       ┆ Almond    ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.85  │
│ 07:52:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 12   ┆ true  ┆ Joshua      ┆ 2.6   │
│ 01:50:26           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Downtown     ┆ Latte       ┆ Soy       ┆ 16   ┆ false ┆ Anthony     ┆ 2.53  │
│ 21:03:50           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-03         ┆ SoHo         ┆ Macchiato   ┆ Oat       ┆ 12   ┆ true  ┆ Christopher ┆ 2.9   │
│ 05:30:19           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-04         ┆ Uptown       ┆ Espresso    ┆ Soy       ┆ 20   ┆ false ┆ Joshua      ┆ 2.76  │
│ 18:46:05           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-05         ┆ Downtown     ┆ Macchiato   ┆ 2%        ┆ 12   ┆ false ┆ Robert      ┆ 5.49  │
│ 18:41:12           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ Downtown     ┆ Americano   ┆ Coconut   ┆ 12   ┆ false ┆ Jeffrey     ┆ 2.8   │
│ 07:47:07           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ Downtown     ┆ Macchiato   ┆ Whole     ┆ 12   ┆ false ┆ Robert      ┆ 6.26  │
│ 21:39:23           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-07         ┆ Downtown     ┆ Macchiato   ┆ Oat       ┆ 20   ┆ false ┆ Danielle    ┆ 6.49  │
│ 10:21:56           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Latte       ┆ Almond    ┆ 12   ┆ false ┆ Danielle    ┆ 2.87  │
│ 10:56:38           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

### Lectura Adicional
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.or_.html

## Precedencia de Operadores
- Polars prioriza el operador AND (`&`) sobre el operador OR (`|`).

In [ ]:
coffees = pl.read_csv("coffee_sales.csv", try_parse_dates=True).sort("time_of_purchase")
coffees.head(2)

shape: (2, 8)
┌─────────────────────┬──────────────┬─────────────┬───────────┬──────┬──────┬─────────────┬───────┐
│ time_of_purchase    ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced ┆ barista     ┆ price │
│ ---                 ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---  ┆ ---         ┆ ---   │
│ datetime[μs]        ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool ┆ str         ┆ f64   │
╞═════════════════════╪══════════════╪═════════════╪═══════════╪══════╪══════╪═════════════╪═══════╡
│ 2025-01-01 01:53:30 ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true ┆ Christopher ┆ 3.1   │
│ 2025-01-01 02:39:54 ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 20   ┆ true ┆ Christopher ┆ 4.29  │
└─────────────────────┴──────────────┴─────────────┴───────────┴──────┴──────┴─────────────┴───────┘

- Comencemos definiendo algunas expresiones booleanas.

In [ ]:
is_almond_milk = pl.col("milk_type").eq("Almond")
is_iced = pl.col("iced")
is_cheap = pl.col("price").le(4)

- ¿Cómo interpreta Polars el filtro de abajo?
- Opción A ❌: Extraer filas que sean (leche de almendra O helado) Y barato
- Opción B ✅: Extraer filas que sean leche de almendra O (helado Y barato)
- El `&` prevalece, así que Polars agrupa `is_iced & is_cheap` juntos.

In [ ]:
coffees.filter(is_almond_milk | is_iced & is_cheap)

shape: (322, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true  ┆ Christopher ┆ 3.1   │
│ 01:53:30           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Downtown     ┆ Mocha       ┆ Almond    ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.85  │
│ 07:52:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 12   ┆ true  ┆ Joshua      ┆ 2.6   │
│ 01:50:26           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Uptown       ┆ Macchiato   ┆ Coconut   ┆ 16   ┆ true  ┆ Joshua      ┆ 3.89  │
│ 12:27:29           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-03         ┆ SoHo         ┆ Macchiato   ┆ Oat       ┆ 12   ┆ true  ┆ Christopher ┆ 2.9   │
│ 05:30:19           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-06         ┆ Uptown       ┆ Cappuccino  ┆ Soy       ┆ 16   ┆ true  ┆ Danielle    ┆ 3.33  │
│ 22:28:52           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-07         ┆ Midtown West ┆ Espresso    ┆ Almond    ┆ 12   ┆ true  ┆ Joshua      ┆ 4.54  │
│ 04:13:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Espresso    ┆ Almond    ┆ 16   ┆ false ┆ Danielle    ┆ 5.17  │
│ 06:12:20           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Latte       ┆ Almond    ┆ 12   ┆ false ┆ Danielle    ┆ 2.87  │
│ 10:56:38           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ Uptown       ┆ Espresso    ┆ Almond    ┆ 20   ┆ false ┆ Joshua      ┆ 3.45  │
│ 13:34:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

- Usa paréntesis para agrupar las expresiones relacionadas.
- Usa paréntesis incluso si la inferencia por defecto de Polars es correcta.

In [ ]:
coffees.filter(is_almond_milk | (is_iced & is_cheap))

shape: (322, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true  ┆ Christopher ┆ 3.1   │
│ 01:53:30           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Downtown     ┆ Mocha       ┆ Almond    ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.85  │
│ 07:52:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 12   ┆ true  ┆ Joshua      ┆ 2.6   │
│ 01:50:26           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Uptown       ┆ Macchiato   ┆ Coconut   ┆ 16   ┆ true  ┆ Joshua      ┆ 3.89  │
│ 12:27:29           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-03         ┆ SoHo         ┆ Macchiato   ┆ Oat       ┆ 12   ┆ true  ┆ Christopher ┆ 2.9   │
│ 05:30:19           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-06         ┆ Uptown       ┆ Cappuccino  ┆ Soy       ┆ 16   ┆ true  ┆ Danielle    ┆ 3.33  │
│ 22:28:52           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-07         ┆ Midtown West ┆ Espresso    ┆ Almond    ┆ 12   ┆ true  ┆ Joshua      ┆ 4.54  │
│ 04:13:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Espresso    ┆ Almond    ┆ 16   ┆ false ┆ Danielle    ┆ 5.17  │
│ 06:12:20           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Latte       ┆ Almond    ┆ 12   ┆ false ┆ Danielle    ┆ 2.87  │
│ 10:56:38           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ Uptown       ┆ Espresso    ┆ Almond    ┆ 20   ┆ false ┆ Joshua      ┆ 3.45  │
│ 13:34:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

- La ubicación de los paréntesis cambia el resultado.
- El siguiente ejemplo extrae filas que sean (leche de almendra O helado) Y barato.

In [ ]:
coffees.filter((is_almond_milk | is_iced) & is_cheap)

shape: (202, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true  ┆ Christopher ┆ 3.1   │
│ 01:53:30           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 12   ┆ true  ┆ Joshua      ┆ 2.6   │
│ 01:50:26           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Uptown       ┆ Macchiato   ┆ Coconut   ┆ 16   ┆ true  ┆ Joshua      ┆ 3.89  │
│ 12:27:29           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-03         ┆ SoHo         ┆ Macchiato   ┆ Oat       ┆ 12   ┆ true  ┆ Christopher ┆ 2.9   │
│ 05:30:19           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-03         ┆ Midtown West ┆ Flat White  ┆ Soy       ┆ 12   ┆ true  ┆ Anthony     ┆ 3.69  │
│ 10:57:47           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-04         ┆ Downtown     ┆ Espresso    ┆ Coconut   ┆ 20   ┆ true  ┆ Joshua      ┆ 2.98  │
│ 14:11:55           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-04         ┆ East Village ┆ Macchiato   ┆ Coconut   ┆ 12   ┆ true  ┆ Christopher ┆ 2.86  │
│ 14:41:15           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ Uptown       ┆ Cappuccino  ┆ Soy       ┆ 16   ┆ true  ┆ Danielle    ┆ 3.33  │
│ 22:28:52           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Latte       ┆ Almond    ┆ 12   ┆ false ┆ Danielle    ┆ 2.87  │
│ 10:56:38           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ Uptown       ┆ Espresso    ┆ Almond    ┆ 20   ┆ false ┆ Joshua      ┆ 3.45  │
│ 13:34:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

## OR Exclusivo
- El operador OR exclusivo (`^`) requiere que solo se cumpla una condición.
- Si una condición es verdadera, la otra debe ser falsa.
- Si ambas condiciones son verdaderas, la expresión `^` se evalúa como falsa.

In [ ]:
coffees = pl.read_csv("coffee_sales.csv", try_parse_dates=True).sort("time_of_purchase")
coffees.head(2)

shape: (2, 8)
┌─────────────────────┬──────────────┬─────────────┬───────────┬──────┬──────┬─────────────┬───────┐
│ time_of_purchase    ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced ┆ barista     ┆ price │
│ ---                 ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---  ┆ ---         ┆ ---   │
│ datetime[μs]        ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool ┆ str         ┆ f64   │
╞═════════════════════╪══════════════╪═════════════╪═══════════╪══════╪══════╪═════════════╪═══════╡
│ 2025-01-01 01:53:30 ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true ┆ Christopher ┆ 3.1   │
│ 2025-01-01 02:39:54 ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 20   ┆ true ┆ Christopher ┆ 4.29  │
└─────────────────────┴──────────────┴─────────────┴───────────┴──────┴──────┴─────────────┴───────┘

- Filtremos las filas con ubicación "Uptown" o leche "Oat".
- Polars _excluirá_ una fila si tiene tanto ubicación "Uptown" como leche "Oat".

In [ ]:
uptown = pl.col("location") == "Uptown"
oat_milk = pl.col("milk_type") == "Oat"

# coffees.filter(uptown | oat_milk)
# coffees.filter(uptown ^ oat_milk)

### Lectura Adicional
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.xor.html

## Filtrado de Valores Únicos y Duplicados

In [ ]:
import polars as pl
coffees = pl.read_csv("coffee_sales.csv", try_parse_dates=True).sort("time_of_purchase")
coffees.head(2)

shape: (2, 8)
┌─────────────────────┬──────────────┬─────────────┬───────────┬──────┬──────┬─────────────┬───────┐
│ time_of_purchase    ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced ┆ barista     ┆ price │
│ ---                 ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---  ┆ ---         ┆ ---   │
│ datetime[μs]        ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool ┆ str         ┆ f64   │
╞═════════════════════╪══════════════╪═════════════╪═══════════╪══════╪══════╪═════════════╪═══════╡
│ 2025-01-01 01:53:30 ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true ┆ Christopher ┆ 3.1   │
│ 2025-01-01 02:39:54 ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 20   ┆ true ┆ Christopher ┆ 4.29  │
└─────────────────────┴──────────────┴─────────────┴───────────┴──────┴──────┴─────────────┴───────┘

- El método `is_unique` identifica si un valor de fila es único (aparece solo una vez en la columna).
- El método `is_duplicated` identifica si un valor de fila está duplicado. Las primeras apariciones también cuentan como duplicados.

In [ ]:
coffees.filter(pl.col("coffee_name").is_unique())

# coffees.select(pl.col("coffee_name").value_counts(sort=True))

shape: (4, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-27         ┆ SoHo         ┆ Frappe      ┆ Soy       ┆ 16   ┆ true  ┆ Jeffrey     ┆ 4.3   │
│ 01:50:31           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-02-07         ┆ East Village ┆ Affogato    ┆ 2%        ┆ 16   ┆ false ┆ Christopher ┆ 2.98  │
│ 09:30:28           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-04-15         ┆ Uptown       ┆ Red eye     ┆ 2%        ┆ 12   ┆ false ┆ Anthony     ┆ 4.71  │
│ 13:22:05           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-04-26         ┆ Midtown West ┆ Cortado     ┆ Whole     ┆ 20   ┆ true  ┆ Joshua      ┆ 5.58  │
│ 01:07:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

In [ ]:
coffees.filter(pl.col("coffee_name").is_duplicated())

shape: (996, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true  ┆ Christopher ┆ 3.1   │
│ 01:53:30           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 20   ┆ true  ┆ Christopher ┆ 4.29  │
│ 02:39:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Downtown     ┆ Mocha       ┆ Almond    ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.85  │
│ 07:52:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Midtown West ┆ null        ┆ Soy       ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.05  │
│ 10:02:41           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ SoHo         ┆ Flat White  ┆ Oat       ┆ 12   ┆ false ┆ Danielle    ┆ 3.74  │
│ 15:07:27           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-07         ┆ Downtown     ┆ Macchiato   ┆ Oat       ┆ 20   ┆ false ┆ Danielle    ┆ 6.49  │
│ 10:21:56           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-07         ┆ East Village ┆ Americano   ┆ Coconut   ┆ 12   ┆ false ┆ Angel       ┆ 4.82  │
│ 10:28:12           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Espresso    ┆ Almond    ┆ 16   ┆ false ┆ Danielle    ┆ 5.17  │
│ 06:12:20           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Latte       ┆ Almond    ┆ 12   ┆ false ┆ Danielle    ┆ 2.87  │
│ 10:56:38           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ Uptown       ┆ Espresso    ┆ Almond    ┆ 20   ┆ false ┆ Joshua      ┆ 3.45  │
│ 13:34:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

- El método `is_first_distinct` identifica si una fila contiene la primera aparición de un valor, independientemente de si es duplicado o no.
- El método `is_last_distinct` identifica si una fila contiene la última aparición de un valor, independientemente de si es duplicado o no.

In [ ]:
coffees.filter(pl.col("coffee_name").is_first_distinct())

shape: (12, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true  ┆ Christopher ┆ 3.1   │
│ 01:53:30           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 20   ┆ true  ┆ Christopher ┆ 4.29  │
│ 02:39:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Downtown     ┆ Mocha       ┆ Almond    ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.85  │
│ 07:52:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Midtown West ┆ null        ┆ Soy       ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.05  │
│ 10:02:41           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Midtown West ┆ Americano   ┆ 2%        ┆ 20   ┆ false ┆ Erica       ┆ 4.83  │
│ 16:31:26           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-01-05         ┆ Downtown     ┆ Cappuccino  ┆ Oat       ┆ 12   ┆ false ┆ Erica       ┆ 3.71  │
│ 14:17:03           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-27         ┆ SoHo         ┆ Frappe      ┆ Soy       ┆ 16   ┆ true  ┆ Jeffrey     ┆ 4.3   │
│ 01:50:31           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-02-07         ┆ East Village ┆ Affogato    ┆ 2%        ┆ 16   ┆ false ┆ Christopher ┆ 2.98  │
│ 09:30:28           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-04-15         ┆ Uptown       ┆ Red eye     ┆ 2%        ┆ 12   ┆ false ┆ Anthony     ┆ 4.71  │
│ 13:22:05           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-04-26         ┆ Midtown West ┆ Cortado     ┆ Whole     ┆ 20   ┆ true  ┆ Joshua      ┆ 5.58  │
│ 01:07:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

In [ ]:
coffees.filter(pl.col("coffee_name").is_last_distinct())

shape: (12, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-27         ┆ SoHo         ┆ Frappe      ┆ Soy       ┆ 16   ┆ true  ┆ Jeffrey     ┆ 4.3   │
│ 01:50:31           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-02-07         ┆ East Village ┆ Affogato    ┆ 2%        ┆ 16   ┆ false ┆ Christopher ┆ 2.98  │
│ 09:30:28           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-04-15         ┆ Uptown       ┆ Red eye     ┆ 2%        ┆ 12   ┆ false ┆ Anthony     ┆ 4.71  │
│ 13:22:05           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-04-26         ┆ Midtown West ┆ Cortado     ┆ Whole     ┆ 20   ┆ true  ┆ Joshua      ┆ 5.58  │
│ 01:07:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-05-10         ┆ SoHo         ┆ null        ┆ 2%        ┆ 20   ┆ false ┆ Erica       ┆ 4.4   │
│ 16:28:05           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-06         ┆ Uptown       ┆ Cappuccino  ┆ Soy       ┆ 16   ┆ true  ┆ Danielle    ┆ 3.33  │
│ 22:28:52           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-07         ┆ Downtown     ┆ Macchiato   ┆ Oat       ┆ 20   ┆ false ┆ Danielle    ┆ 6.49  │
│ 10:21:56           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-07         ┆ East Village ┆ Americano   ┆ Coconut   ┆ 12   ┆ false ┆ Angel       ┆ 4.82  │
│ 10:28:12           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Latte       ┆ Almond    ┆ 12   ┆ false ┆ Danielle    ┆ 2.87  │
│ 10:56:38           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ Uptown       ┆ Espresso    ┆ Almond    ┆ 20   ┆ false ┆ Joshua      ┆ 3.45  │
│ 13:34:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

### Lectura Adicional
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.is_unique.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.is_duplicated.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.is_first_distinct.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.is_last_distinct.html

## Filtrado con Fechas y Horas
- El método `filter` soporta el filtrado de columnas de fecha, hora y fecha-hora.

In [ ]:
coffees = pl.read_csv("coffee_sales.csv", try_parse_dates=True).sort("time_of_purchase")
coffees.head(2)

shape: (2, 8)
┌─────────────────────┬──────────────┬─────────────┬───────────┬──────┬──────┬─────────────┬───────┐
│ time_of_purchase    ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced ┆ barista     ┆ price │
│ ---                 ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---  ┆ ---         ┆ ---   │
│ datetime[μs]        ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool ┆ str         ┆ f64   │
╞═════════════════════╪══════════════╪═════════════╪═══════════╪══════╪══════╪═════════════╪═══════╡
│ 2025-01-01 01:53:30 ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true ┆ Christopher ┆ 3.1   │
│ 2025-01-01 02:39:54 ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 20   ┆ true ┆ Christopher ┆ 4.29  │
└─────────────────────┴──────────────┴─────────────┴───────────┴──────┴──────┴─────────────┴───────┘

- Busquemos todos los cafés comprados en o después del 1 de junio de 2025.
- Polars es menos flexible que Pandas. No permitirá la comparación de fechas con cadenas de tiempo.

In [ ]:
# InvalidOperationError: cannot compare 'date/datetime/time' to a string value
# (create native python { 'date', 'datetime', 'time' } or compare to a temporal column)
# coffees.filter(pl.col("time_of_purchase") >= "2025-06-01")

- Para filtrar fechas-hora, necesitamos proporcionar un objeto de fecha/fecha-hora válido de Python o Polars.
- Polars tiene una función `date` que tiene la misma API que `dt.date` (año, mes y día).
- La función `date` devuelve una expresión que representa una fecha en el tiempo.
- `pl.date` es diferente de `pl.Date` que es el tipo `Date`.
- Al usar una fecha en una columna de fecha-hora, Polars asume la hora de medianoche (00:00:00).

In [ ]:
import datetime as dt

In [ ]:
coffees.filter(pl.col("time_of_purchase") >= dt.date(2025, 6, 1))
# coffees.filter(pl.col("time_of_purchase").ge(dt.date(2025, 6, 1)))

shape: (47, 8)
┌─────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬──────────┬───────┐
│ time_of_purchase    ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista  ┆ price │
│ ---                 ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---      ┆ ---   │
│ datetime[μs]        ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str      ┆ f64   │
╞═════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪══════════╪═══════╡
│ 2025-06-01 00:13:38 ┆ Midtown West ┆ Mocha       ┆ 2%        ┆ 12   ┆ false ┆ Patricia ┆ 3.03  │
│ 2025-06-01 00:46:22 ┆ SoHo         ┆ Macchiato   ┆ Oat       ┆ 12   ┆ false ┆ Danielle ┆ 3.67  │
│ 2025-06-01 03:42:07 ┆ Midtown West ┆ Flat White  ┆ Oat       ┆ 16   ┆ false ┆ Erica    ┆ 6.21  │
│ 2025-06-01 04:39:44 ┆ Downtown     ┆ Mocha       ┆ Oat       ┆ 20   ┆ false ┆ Erica    ┆ 5.66  │
│ 2025-06-01 11:36:18 ┆ Midtown West ┆ Cappuccino  ┆ Whole     ┆ 12   ┆ true  ┆ Angel    ┆ 4.51  │
│ …                   ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …        ┆ …     │
│ 2025-06-07 10:21:56 ┆ Downtown     ┆ Macchiato   ┆ Oat       ┆ 20   ┆ false ┆ Danielle ┆ 6.49  │
│ 2025-06-07 10:28:12 ┆ East Village ┆ Americano   ┆ Coconut   ┆ 12   ┆ false ┆ Angel    ┆ 4.82  │
│ 2025-06-08 06:12:20 ┆ East Village ┆ Espresso    ┆ Almond    ┆ 16   ┆ false ┆ Danielle ┆ 5.17  │
│ 2025-06-08 10:56:38 ┆ East Village ┆ Latte       ┆ Almond    ┆ 12   ┆ false ┆ Danielle ┆ 2.87  │
│ 2025-06-08 13:34:09 ┆ Uptown       ┆ Espresso    ┆ Almond    ┆ 20   ┆ false ┆ Joshua   ┆ 3.45  │
└─────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴──────────┴───────┘

In [ ]:
# También se pueden pl.date
# Cuando se usa para filtrar una columna de tipo datetime (fecha-hora),
# Polars asume por defecto la medianoche (00:00:00) de ese día
type(pl.date(2025, 6, 1))

polars.expr.expr.Expr

In [ ]:
coffees.filter(pl.col("time_of_purchase") >= pl.date(2025, 6, 1))

shape: (47, 8)
┌─────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬──────────┬───────┐
│ time_of_purchase    ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista  ┆ price │
│ ---                 ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---      ┆ ---   │
│ datetime[μs]        ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str      ┆ f64   │
╞═════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪══════════╪═══════╡
│ 2025-06-01 00:13:38 ┆ Midtown West ┆ Mocha       ┆ 2%        ┆ 12   ┆ false ┆ Patricia ┆ 3.03  │
│ 2025-06-01 00:46:22 ┆ SoHo         ┆ Macchiato   ┆ Oat       ┆ 12   ┆ false ┆ Danielle ┆ 3.67  │
│ 2025-06-01 03:42:07 ┆ Midtown West ┆ Flat White  ┆ Oat       ┆ 16   ┆ false ┆ Erica    ┆ 6.21  │
│ 2025-06-01 04:39:44 ┆ Downtown     ┆ Mocha       ┆ Oat       ┆ 20   ┆ false ┆ Erica    ┆ 5.66  │
│ 2025-06-01 11:36:18 ┆ Midtown West ┆ Cappuccino  ┆ Whole     ┆ 12   ┆ true  ┆ Angel    ┆ 4.51  │
│ …                   ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …        ┆ …     │
│ 2025-06-07 10:21:56 ┆ Downtown     ┆ Macchiato   ┆ Oat       ┆ 20   ┆ false ┆ Danielle ┆ 6.49  │
│ 2025-06-07 10:28:12 ┆ East Village ┆ Americano   ┆ Coconut   ┆ 12   ┆ false ┆ Angel    ┆ 4.82  │
│ 2025-06-08 06:12:20 ┆ East Village ┆ Espresso    ┆ Almond    ┆ 16   ┆ false ┆ Danielle ┆ 5.17  │
│ 2025-06-08 10:56:38 ┆ East Village ┆ Latte       ┆ Almond    ┆ 12   ┆ false ┆ Danielle ┆ 2.87  │
│ 2025-06-08 13:34:09 ┆ Uptown       ┆ Espresso    ┆ Almond    ┆ 20   ┆ false ┆ Joshua   ┆ 3.45  │
└─────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴──────────┴───────┘

- El constructor `dt.datetime` acepta las horas, minutos y segundos después del año, mes y día.
- Aquí filtramos los cafés comprados después del 1 de junio de 2025 a las 12:30:45pm.
- Polars tiene un constructor similar `pl.datetime`.

In [ ]:
coffees.filter(pl.col("time_of_purchase") >= dt.datetime(2025, 6, 1, 12, 30, 45))

shape: (42, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-06-01         ┆ SoHo         ┆ Cappuccino  ┆ Almond    ┆ 20   ┆ false ┆ Anthony     ┆ 4.68  │
│ 16:48:35           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-01         ┆ Downtown     ┆ Macchiato   ┆ Whole     ┆ 16   ┆ false ┆ Joshua      ┆ 2.86  │
│ 22:11:07           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-01         ┆ Downtown     ┆ Latte       ┆ Almond    ┆ 16   ┆ true  ┆ Christopher ┆ 4.86  │
│ 23:20:42           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-02         ┆ East Village ┆ Mocha       ┆ Soy       ┆ 16   ┆ true  ┆ Patricia    ┆ 5.81  │
│ 02:43:45           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-02         ┆ Midtown West ┆ Espresso    ┆ Coconut   ┆ 20   ┆ true  ┆ Danielle    ┆ 6.13  │
│ 06:02:01           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-07         ┆ Downtown     ┆ Macchiato   ┆ Oat       ┆ 20   ┆ false ┆ Danielle    ┆ 6.49  │
│ 10:21:56           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-07         ┆ East Village ┆ Americano   ┆ Coconut   ┆ 12   ┆ false ┆ Angel       ┆ 4.82  │
│ 10:28:12           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Espresso    ┆ Almond    ┆ 16   ┆ false ┆ Danielle    ┆ 5.17  │
│ 06:12:20           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Latte       ┆ Almond    ┆ 12   ┆ false ┆ Danielle    ┆ 2.87  │
│ 10:56:38           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ Uptown       ┆ Espresso    ┆ Almond    ┆ 20   ┆ false ┆ Joshua      ┆ 3.45  │
│ 13:34:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

In [ ]:
coffees.filter(pl.col("time_of_purchase") >= pl.datetime(2025, 6, 1, 12, 30, 45))

shape: (42, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-06-01         ┆ SoHo         ┆ Cappuccino  ┆ Almond    ┆ 20   ┆ false ┆ Anthony     ┆ 4.68  │
│ 16:48:35           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-01         ┆ Downtown     ┆ Macchiato   ┆ Whole     ┆ 16   ┆ false ┆ Joshua      ┆ 2.86  │
│ 22:11:07           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-01         ┆ Downtown     ┆ Latte       ┆ Almond    ┆ 16   ┆ true  ┆ Christopher ┆ 4.86  │
│ 23:20:42           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-02         ┆ East Village ┆ Mocha       ┆ Soy       ┆ 16   ┆ true  ┆ Patricia    ┆ 5.81  │
│ 02:43:45           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-02         ┆ Midtown West ┆ Espresso    ┆ Coconut   ┆ 20   ┆ true  ┆ Danielle    ┆ 6.13  │
│ 06:02:01           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-07         ┆ Downtown     ┆ Macchiato   ┆ Oat       ┆ 20   ┆ false ┆ Danielle    ┆ 6.49  │
│ 10:21:56           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-07         ┆ East Village ┆ Americano   ┆ Coconut   ┆ 12   ┆ false ┆ Angel       ┆ 4.82  │
│ 10:28:12           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Espresso    ┆ Almond    ┆ 16   ┆ false ┆ Danielle    ┆ 5.17  │
│ 06:12:20           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Latte       ┆ Almond    ┆ 12   ┆ false ┆ Danielle    ┆ 2.87  │
│ 10:56:38           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ Uptown       ┆ Espresso    ┆ Almond    ┆ 20   ┆ false ┆ Joshua      ┆ 3.45  │
│ 13:34:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

### Lectura Adicional
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.date.html
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.datetime.html

## El Método `is_between`

In [ ]:
coffees = pl.read_csv("coffee_sales.csv", try_parse_dates=True).sort("time_of_purchase")
coffees.head(2)

shape: (2, 8)
┌─────────────────────┬──────────────┬─────────────┬───────────┬──────┬──────┬─────────────┬───────┐
│ time_of_purchase    ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced ┆ barista     ┆ price │
│ ---                 ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---  ┆ ---         ┆ ---   │
│ datetime[μs]        ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool ┆ str         ┆ f64   │
╞═════════════════════╪══════════════╪═════════════╪═══════════╪══════╪══════╪═════════════╪═══════╡
│ 2025-01-01 01:53:30 ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true ┆ Christopher ┆ 3.1   │
│ 2025-01-01 02:39:54 ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 20   ┆ true ┆ Christopher ┆ 4.29  │
└─────────────────────┴──────────────┴─────────────┴───────────┴──────┴──────┴─────────────┴───────┘

- Supongamos que buscamos todas las transacciones con un precio entre 3 y 4 dólares.
- Al verificar la inclusión en un rango, una opción es declarar cada límite como una condición separada.

In [ ]:
coffees.filter(pl.col("price").ge(3) & pl.col("price").le(4))

shape: (243, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true  ┆ Christopher ┆ 3.1   │
│ 01:53:30           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ SoHo         ┆ Flat White  ┆ Oat       ┆ 12   ┆ false ┆ Danielle    ┆ 3.74  │
│ 15:07:27           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Uptown       ┆ Macchiato   ┆ Coconut   ┆ 16   ┆ true  ┆ Joshua      ┆ 3.89  │
│ 12:27:29           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-03         ┆ Midtown West ┆ Flat White  ┆ Soy       ┆ 12   ┆ true  ┆ Anthony     ┆ 3.69  │
│ 10:57:47           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-05         ┆ Downtown     ┆ Cappuccino  ┆ Oat       ┆ 12   ┆ false ┆ Erica       ┆ 3.71  │
│ 14:17:03           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-05         ┆ Downtown     ┆ Latte       ┆ Oat       ┆ 20   ┆ false ┆ Anthony     ┆ 3.56  │
│ 11:01:53           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 12   ┆ false ┆ Robert      ┆ 3.07  │
│ 03:25:24           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ SoHo         ┆ Flat White  ┆ Oat       ┆ 20   ┆ false ┆ Danielle    ┆ 3.47  │
│ 14:36:47           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ Uptown       ┆ Cappuccino  ┆ Soy       ┆ 16   ┆ true  ┆ Danielle    ┆ 3.33  │
│ 22:28:52           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ Uptown       ┆ Espresso    ┆ Almond    ┆ 20   ┆ false ┆ Joshua      ┆ 3.45  │
│ 13:34:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

- El método `is_between` devuelve una expresión booleana que indica si un valor de fila cae dentro de un rango.
- Tanto el límite inferior como el superior son inclusivos.

In [ ]:
coffees.filter(pl.col("price").is_between(3, 4))

shape: (243, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true  ┆ Christopher ┆ 3.1   │
│ 01:53:30           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ SoHo         ┆ Flat White  ┆ Oat       ┆ 12   ┆ false ┆ Danielle    ┆ 3.74  │
│ 15:07:27           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Uptown       ┆ Macchiato   ┆ Coconut   ┆ 16   ┆ true  ┆ Joshua      ┆ 3.89  │
│ 12:27:29           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-03         ┆ Midtown West ┆ Flat White  ┆ Soy       ┆ 12   ┆ true  ┆ Anthony     ┆ 3.69  │
│ 10:57:47           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-05         ┆ Downtown     ┆ Cappuccino  ┆ Oat       ┆ 12   ┆ false ┆ Erica       ┆ 3.71  │
│ 14:17:03           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-05         ┆ Downtown     ┆ Latte       ┆ Oat       ┆ 20   ┆ false ┆ Anthony     ┆ 3.56  │
│ 11:01:53           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 12   ┆ false ┆ Robert      ┆ 3.07  │
│ 03:25:24           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ SoHo         ┆ Flat White  ┆ Oat       ┆ 20   ┆ false ┆ Danielle    ┆ 3.47  │
│ 14:36:47           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ Uptown       ┆ Cappuccino  ┆ Soy       ┆ 16   ┆ true  ┆ Danielle    ┆ 3.33  │
│ 22:28:52           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ Uptown       ┆ Espresso    ┆ Almond    ┆ 20   ┆ false ┆ Joshua      ┆ 3.45  │
│ 13:34:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

In [ ]:
coffees.filter(pl.col("size").is_between(12, 16))

shape: (690, 8)
┌─────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬──────────┬───────┐
│ time_of_purchase    ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista  ┆ price │
│ ---                 ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---      ┆ ---   │
│ datetime[μs]        ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str      ┆ f64   │
╞═════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪══════════╪═══════╡
│ 2025-01-01 07:52:54 ┆ Downtown     ┆ Mocha       ┆ Almond    ┆ 12   ┆ false ┆ Jeffrey  ┆ 5.85  │
│ 2025-01-01 10:02:41 ┆ Midtown West ┆ null        ┆ Soy       ┆ 12   ┆ false ┆ Jeffrey  ┆ 5.05  │
│ 2025-01-01 15:07:27 ┆ SoHo         ┆ Flat White  ┆ Oat       ┆ 12   ┆ false ┆ Danielle ┆ 3.74  │
│ 2025-01-02 01:50:26 ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 12   ┆ true  ┆ Joshua   ┆ 2.6   │
│ 2025-01-02 09:30:42 ┆ East Village ┆ Macchiato   ┆ Whole     ┆ 12   ┆ false ┆ Robert   ┆ 6.24  │
│ …                   ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …        ┆ …     │
│ 2025-06-06 22:28:52 ┆ Uptown       ┆ Cappuccino  ┆ Soy       ┆ 16   ┆ true  ┆ Danielle ┆ 3.33  │
│ 2025-06-07 04:13:09 ┆ Midtown West ┆ Espresso    ┆ Almond    ┆ 12   ┆ true  ┆ Joshua   ┆ 4.54  │
│ 2025-06-07 10:28:12 ┆ East Village ┆ Americano   ┆ Coconut   ┆ 12   ┆ false ┆ Angel    ┆ 4.82  │
│ 2025-06-08 06:12:20 ┆ East Village ┆ Espresso    ┆ Almond    ┆ 16   ┆ false ┆ Danielle ┆ 5.17  │
│ 2025-06-08 10:56:38 ┆ East Village ┆ Latte       ┆ Almond    ┆ 12   ┆ false ┆ Danielle ┆ 2.87  │
└─────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴──────────┴───────┘

In [ ]:
coffees.filter(
    pl.col("time_of_purchase").is_between(pl.date(2025, 2, 1), pl.date(2025, 3, 1))
)

shape: (188, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-02-01         ┆ Midtown West ┆ Latte       ┆ Whole     ┆ 20   ┆ false ┆ Patricia    ┆ 3.13  │
│ 00:03:58           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-02-01         ┆ Downtown     ┆ Flat White  ┆ Soy       ┆ 20   ┆ false ┆ Christopher ┆ 4.15  │
│ 01:34:12           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-02-01         ┆ East Village ┆ Macchiato   ┆ Almond    ┆ 12   ┆ false ┆ Erica       ┆ 5.6   │
│ 08:52:23           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-02-01         ┆ Uptown       ┆ Mocha       ┆ Whole     ┆ 12   ┆ false ┆ Angel       ┆ 5.12  │
│ 09:01:35           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-02-01         ┆ Midtown West ┆ Cappuccino  ┆ Almond    ┆ 12   ┆ false ┆ Patricia    ┆ 4.47  │
│ 13:18:47           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-02-28         ┆ East Village ┆ Latte       ┆ Whole     ┆ 16   ┆ false ┆ Joshua      ┆ 4.76  │
│ 06:05:15           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-02-28         ┆ Midtown West ┆ Espresso    ┆ Whole     ┆ 16   ┆ true  ┆ Anthony     ┆ 3.68  │
│ 07:36:11           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-02-28         ┆ Downtown     ┆ Macchiato   ┆ Oat       ┆ 16   ┆ true  ┆ Christopher ┆ 3.29  │
│ 10:31:41           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-02-28         ┆ SoHo         ┆ Cappuccino  ┆ Coconut   ┆ 20   ┆ true  ┆ Patricia    ┆ 5.38  │
│ 13:28:37           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-02-28         ┆ East Village ┆ Latte       ┆ Almond    ┆ 12   ┆ false ┆ Erica       ┆ 3.17  │
│ 17:49:55           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

### Lectura Adicional
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.is_between.html

## El Método `is_in`
- El método `is_in` valida la inclusión de un valor de fila dentro de una colección de valores.

In [ ]:
coffees = pl.read_csv("coffee_sales.csv", try_parse_dates=True).sort("time_of_purchase")
coffees.head(2)

shape: (2, 8)
┌─────────────────────┬──────────────┬─────────────┬───────────┬──────┬──────┬─────────────┬───────┐
│ time_of_purchase    ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced ┆ barista     ┆ price │
│ ---                 ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---  ┆ ---         ┆ ---   │
│ datetime[μs]        ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool ┆ str         ┆ f64   │
╞═════════════════════╪══════════════╪═════════════╪═══════════╪══════╪══════╪═════════════╪═══════╡
│ 2025-01-01 01:53:30 ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true ┆ Christopher ┆ 3.1   │
│ 2025-01-01 02:39:54 ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 20   ┆ true ┆ Christopher ┆ 4.29  │
└─────────────────────┴──────────────┴─────────────┴───────────┴──────┴──────┴─────────────┴───────┘

- Digamos que queremos extraer filas donde `coffee_name` sea "Americano" o "Espresso".
- Podemos aplicar el operador `|` o el método `or_` para verificar múltiples expresiones independientes.

In [ ]:
coffees.filter(
    pl.col("coffee_name").eq("Americano") | pl.col("coffee_name").eq("Espresso")
)

shape: (281, 8)
┌─────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬──────────┬───────┐
│ time_of_purchase    ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista  ┆ price │
│ ---                 ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---      ┆ ---   │
│ datetime[μs]        ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str      ┆ f64   │
╞═════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪══════════╪═══════╡
│ 2025-01-01 16:31:26 ┆ Midtown West ┆ Americano   ┆ 2%        ┆ 20   ┆ false ┆ Erica    ┆ 4.83  │
│ 2025-01-02 03:28:39 ┆ East Village ┆ Espresso    ┆ 2%        ┆ 20   ┆ true  ┆ Joshua   ┆ 4.79  │
│ 2025-01-02 23:18:27 ┆ Uptown       ┆ Americano   ┆ Coconut   ┆ 20   ┆ false ┆ Anthony  ┆ 4.08  │
│ 2025-01-03 20:46:35 ┆ Midtown West ┆ Espresso    ┆ Coconut   ┆ 20   ┆ false ┆ Anthony  ┆ 4.81  │
│ 2025-01-04 08:21:33 ┆ Uptown       ┆ Americano   ┆ Oat       ┆ 16   ┆ true  ┆ Joshua   ┆ 4.52  │
│ …                   ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …        ┆ …     │
│ 2025-06-06 17:29:25 ┆ Midtown West ┆ Americano   ┆ 2%        ┆ 12   ┆ false ┆ Jeffrey  ┆ 5.96  │
│ 2025-06-07 04:13:09 ┆ Midtown West ┆ Espresso    ┆ Almond    ┆ 12   ┆ true  ┆ Joshua   ┆ 4.54  │
│ 2025-06-07 10:28:12 ┆ East Village ┆ Americano   ┆ Coconut   ┆ 12   ┆ false ┆ Angel    ┆ 4.82  │
│ 2025-06-08 06:12:20 ┆ East Village ┆ Espresso    ┆ Almond    ┆ 16   ┆ false ┆ Danielle ┆ 5.17  │
│ 2025-06-08 13:34:09 ┆ Uptown       ┆ Espresso    ┆ Almond    ┆ 20   ┆ false ┆ Joshua   ┆ 3.45  │
└─────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴──────────┴───────┘

- El método `is_in` acepta una colección (lista, tupla, etc.) u otra expresión.

In [ ]:
coffees.filter(pl.col("coffee_name").is_in(["Americano", "Espresso", "Latte"]))

shape: (420, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true  ┆ Christopher ┆ 3.1   │
│ 01:53:30           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Midtown West ┆ Americano   ┆ 2%        ┆ 20   ┆ false ┆ Erica       ┆ 4.83  │
│ 16:31:26           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ East Village ┆ Espresso    ┆ 2%        ┆ 20   ┆ true  ┆ Joshua      ┆ 4.79  │
│ 03:28:39           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 12   ┆ false ┆ Jill        ┆ 5.69  │
│ 19:24:47           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Downtown     ┆ Latte       ┆ Soy       ┆ 16   ┆ false ┆ Anthony     ┆ 2.53  │
│ 21:03:50           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-07         ┆ Midtown West ┆ Espresso    ┆ Almond    ┆ 12   ┆ true  ┆ Joshua      ┆ 4.54  │
│ 04:13:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-07         ┆ East Village ┆ Americano   ┆ Coconut   ┆ 12   ┆ false ┆ Angel       ┆ 4.82  │
│ 10:28:12           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Espresso    ┆ Almond    ┆ 16   ┆ false ┆ Danielle    ┆ 5.17  │
│ 06:12:20           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Latte       ┆ Almond    ┆ 12   ┆ false ┆ Danielle    ┆ 2.87  │
│ 10:56:38           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ Uptown       ┆ Espresso    ┆ Almond    ┆ 20   ┆ false ┆ Joshua      ┆ 3.45  │
│ 13:34:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

### Lectura Adicional
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.is_in.html

## El Método `remove`
- El método `filter` incluye filas que satisfacen una expresión.
- El método `remove` _excluye_ filas que satisfacen una expresión.
- El método `remove` realiza la lógica inversa del método `filter`.

In [ ]:
coffees = pl.read_csv("coffee_sales.csv", try_parse_dates=True).sort("time_of_purchase")
coffees.head(2)

shape: (2, 8)
┌─────────────────────┬──────────────┬─────────────┬───────────┬──────┬──────┬─────────────┬───────┐
│ time_of_purchase    ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced ┆ barista     ┆ price │
│ ---                 ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---  ┆ ---         ┆ ---   │
│ datetime[μs]        ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool ┆ str         ┆ f64   │
╞═════════════════════╪══════════════╪═════════════╪═══════════╪══════╪══════╪═════════════╪═══════╡
│ 2025-01-01 01:53:30 ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true ┆ Christopher ┆ 3.1   │
│ 2025-01-01 02:39:54 ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 20   ┆ true ┆ Christopher ┆ 4.29  │
└─────────────────────┴──────────────┴─────────────┴───────────┴──────┴──────┴─────────────┴───────┘

- Digamos que queremos extraer cualquier fila donde el valor de `size` no sea igual a 12.

In [ ]:
coffees.filter(pl.col("size") != 12)

shape: (659, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true  ┆ Christopher ┆ 3.1   │
│ 01:53:30           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 20   ┆ true  ┆ Christopher ┆ 4.29  │
│ 02:39:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Midtown West ┆ Americano   ┆ 2%        ┆ 20   ┆ false ┆ Erica       ┆ 4.83  │
│ 16:31:26           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ East Village ┆ Espresso    ┆ 2%        ┆ 20   ┆ true  ┆ Joshua      ┆ 4.79  │
│ 03:28:39           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ SoHo         ┆ Mocha       ┆ Coconut   ┆ 20   ┆ true  ┆ Joshua      ┆ 5.67  │
│ 06:17:11           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-06         ┆ SoHo         ┆ Latte       ┆ Coconut   ┆ 16   ┆ true  ┆ Erica       ┆ 4.96  │
│ 19:12:31           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ Uptown       ┆ Cappuccino  ┆ Soy       ┆ 16   ┆ true  ┆ Danielle    ┆ 3.33  │
│ 22:28:52           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-07         ┆ Downtown     ┆ Macchiato   ┆ Oat       ┆ 20   ┆ false ┆ Danielle    ┆ 6.49  │
│ 10:21:56           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Espresso    ┆ Almond    ┆ 16   ┆ false ┆ Danielle    ┆ 5.17  │
│ 06:12:20           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ Uptown       ┆ Espresso    ┆ Almond    ┆ 20   ┆ false ┆ Joshua      ┆ 3.45  │
│ 13:34:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

- Alternativamente, podríamos usar `remove` para eliminar cualquier fila donde el valor de `size` sea igual a 12.

In [ ]:
coffees.remove(pl.col("size") == 12)

shape: (659, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true  ┆ Christopher ┆ 3.1   │
│ 01:53:30           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 20   ┆ true  ┆ Christopher ┆ 4.29  │
│ 02:39:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Midtown West ┆ Americano   ┆ 2%        ┆ 20   ┆ false ┆ Erica       ┆ 4.83  │
│ 16:31:26           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ East Village ┆ Espresso    ┆ 2%        ┆ 20   ┆ true  ┆ Joshua      ┆ 4.79  │
│ 03:28:39           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ SoHo         ┆ Mocha       ┆ Coconut   ┆ 20   ┆ true  ┆ Joshua      ┆ 5.67  │
│ 06:17:11           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-06         ┆ SoHo         ┆ Latte       ┆ Coconut   ┆ 16   ┆ true  ┆ Erica       ┆ 4.96  │
│ 19:12:31           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-06         ┆ Uptown       ┆ Cappuccino  ┆ Soy       ┆ 16   ┆ true  ┆ Danielle    ┆ 3.33  │
│ 22:28:52           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-07         ┆ Downtown     ┆ Macchiato   ┆ Oat       ┆ 20   ┆ false ┆ Danielle    ┆ 6.49  │
│ 10:21:56           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Espresso    ┆ Almond    ┆ 16   ┆ false ┆ Danielle    ┆ 5.17  │
│ 06:12:20           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ Uptown       ┆ Espresso    ┆ Almond    ┆ 20   ┆ false ┆ Joshua      ┆ 3.45  │
│ 13:34:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

- Podemos validar la igualdad de `DataFrames` con el método `equals`.
- El método `equals` devuelve `True` si dos `DataFrames` son iguales (mismas columnas, filas, valores, etc.).

In [ ]:
coffees.filter(pl.col("size") != 12).equals(coffees.remove(pl.col("size") == 12))

True

- Si usas `&` o proporcionas múltiples argumentos, Polars confirmará que ambas condiciones se cumplan para excluir una fila.
- Polars eliminará las filas donde `size` sea 12 y `barista` sea "Christopher" o "Erica".
- Polars conservará las filas con tamaño 12 y un barista que no sea Christopher ni Erica.
- Polars conservará las filas con barista Christopher o Erica y un tamaño diferente de 12.

In [ ]:
coffees.remove(
    (pl.col("size") == 12) & pl.col("barista").is_in(["Christopher", "Erica"])
)

coffees.remove(pl.col("size") == 12, pl.col("barista").is_in(["Christopher", "Erica"]))

coffees.remove(
    (pl.col("size") == 12) | pl.col("barista").is_in(["Christopher", "Erica"])
)

shape: (511, 8)
┌─────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬──────────┬───────┐
│ time_of_purchase    ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista  ┆ price │
│ ---                 ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---      ┆ ---   │
│ datetime[μs]        ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str      ┆ f64   │
╞═════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪══════════╪═══════╡
│ 2025-01-02 03:28:39 ┆ East Village ┆ Espresso    ┆ 2%        ┆ 20   ┆ true  ┆ Joshua   ┆ 4.79  │
│ 2025-01-02 06:17:11 ┆ SoHo         ┆ Mocha       ┆ Coconut   ┆ 20   ┆ true  ┆ Joshua   ┆ 5.67  │
│ 2025-01-02 12:27:29 ┆ Uptown       ┆ Macchiato   ┆ Coconut   ┆ 16   ┆ true  ┆ Joshua   ┆ 3.89  │
│ 2025-01-02 21:03:50 ┆ Downtown     ┆ Latte       ┆ Soy       ┆ 16   ┆ false ┆ Anthony  ┆ 2.53  │
│ 2025-01-02 23:18:27 ┆ Uptown       ┆ Americano   ┆ Coconut   ┆ 20   ┆ false ┆ Anthony  ┆ 4.08  │
│ …                   ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …        ┆ …     │
│ 2025-06-06 15:50:35 ┆ SoHo         ┆ Americano   ┆ 2%        ┆ 16   ┆ false ┆ Jeffrey  ┆ 4.16  │
│ 2025-06-06 22:28:52 ┆ Uptown       ┆ Cappuccino  ┆ Soy       ┆ 16   ┆ true  ┆ Danielle ┆ 3.33  │
│ 2025-06-07 10:21:56 ┆ Downtown     ┆ Macchiato   ┆ Oat       ┆ 20   ┆ false ┆ Danielle ┆ 6.49  │
│ 2025-06-08 06:12:20 ┆ East Village ┆ Espresso    ┆ Almond    ┆ 16   ┆ false ┆ Danielle ┆ 5.17  │
│ 2025-06-08 13:34:09 ┆ Uptown       ┆ Espresso    ┆ Almond    ┆ 20   ┆ false ┆ Joshua   ┆ 3.45  │
└─────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴──────────┴───────┘

### Lectura Adicional
- https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.remove.html

## Negación con el Símbolo Tilde
- El símbolo tilde (`~`) invierte los valores de una expresión booleana.
- Un true se convierte en false, y un false se convierte en true.

In [ ]:
coffees = pl.read_csv("coffee_sales.csv", try_parse_dates=True).sort("time_of_purchase")
coffees.head(2)

shape: (2, 8)
┌─────────────────────┬──────────────┬─────────────┬───────────┬──────┬──────┬─────────────┬───────┐
│ time_of_purchase    ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced ┆ barista     ┆ price │
│ ---                 ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---  ┆ ---         ┆ ---   │
│ datetime[μs]        ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool ┆ str         ┆ f64   │
╞═════════════════════╪══════════════╪═════════════╪═══════════╪══════╪══════╪═════════════╪═══════╡
│ 2025-01-01 01:53:30 ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true ┆ Christopher ┆ 3.1   │
│ 2025-01-01 02:39:54 ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 20   ┆ true ┆ Christopher ┆ 4.29  │
└─────────────────────┴──────────────┴─────────────┴───────────┴──────┴──────┴─────────────┴───────┘

In [ ]:
coffees.select(
    pl.col("barista"),
    pl.col("barista").eq("Christopher").alias("is_chris"),
    ~pl.col("barista").eq("Christopher").alias("is_not_chris"),
)

shape: (1_000, 3)
┌─────────────┬──────────┬──────────────┐
│ barista     ┆ is_chris ┆ is_not_chris │
│ ---         ┆ ---      ┆ ---          │
│ str         ┆ bool     ┆ bool         │
╞═════════════╪══════════╪══════════════╡
│ Christopher ┆ true     ┆ false        │
│ Christopher ┆ true     ┆ false        │
│ Jeffrey     ┆ false    ┆ true         │
│ Jeffrey     ┆ false    ┆ true         │
│ Danielle    ┆ false    ┆ true         │
│ …           ┆ …        ┆ …            │
│ Danielle    ┆ false    ┆ true         │
│ Angel       ┆ false    ┆ true         │
│ Danielle    ┆ false    ┆ true         │
│ Danielle    ┆ false    ┆ true         │
│ Joshua      ┆ false    ┆ true         │
└─────────────┴──────────┴──────────────┘

- Extraigamos las filas con precios de café menores a `$3` y mayores a `$4`.

In [ ]:
coffees.filter(pl.col("price").lt(3) | pl.col("price").gt(4))

shape: (757, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 20   ┆ true  ┆ Christopher ┆ 4.29  │
│ 02:39:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Downtown     ┆ Mocha       ┆ Almond    ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.85  │
│ 07:52:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Midtown West ┆ null        ┆ Soy       ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.05  │
│ 10:02:41           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Midtown West ┆ Americano   ┆ 2%        ┆ 20   ┆ false ┆ Erica       ┆ 4.83  │
│ 16:31:26           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 12   ┆ true  ┆ Joshua      ┆ 2.6   │
│ 01:50:26           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-07         ┆ Midtown West ┆ Espresso    ┆ Almond    ┆ 12   ┆ true  ┆ Joshua      ┆ 4.54  │
│ 04:13:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-07         ┆ Downtown     ┆ Macchiato   ┆ Oat       ┆ 20   ┆ false ┆ Danielle    ┆ 6.49  │
│ 10:21:56           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-07         ┆ East Village ┆ Americano   ┆ Coconut   ┆ 12   ┆ false ┆ Angel       ┆ 4.82  │
│ 10:28:12           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Espresso    ┆ Almond    ┆ 16   ┆ false ┆ Danielle    ┆ 5.17  │
│ 06:12:20           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Latte       ┆ Almond    ┆ 12   ┆ false ┆ Danielle    ┆ 2.87  │
│ 10:56:38           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

- Alternativamente, podemos seleccionar todas las filas con precios que no estén entre `$3` y `$4`.

In [ ]:
coffees.filter(~pl.col("price").is_between(3, 4))

shape: (757, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-01-01         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 20   ┆ true  ┆ Christopher ┆ 4.29  │
│ 02:39:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Downtown     ┆ Mocha       ┆ Almond    ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.85  │
│ 07:52:54           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Midtown West ┆ null        ┆ Soy       ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.05  │
│ 10:02:41           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-01         ┆ Midtown West ┆ Americano   ┆ 2%        ┆ 20   ┆ false ┆ Erica       ┆ 4.83  │
│ 16:31:26           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 12   ┆ true  ┆ Joshua      ┆ 2.6   │
│ 01:50:26           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-06-07         ┆ Midtown West ┆ Espresso    ┆ Almond    ┆ 12   ┆ true  ┆ Joshua      ┆ 4.54  │
│ 04:13:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-07         ┆ Downtown     ┆ Macchiato   ┆ Oat       ┆ 20   ┆ false ┆ Danielle    ┆ 6.49  │
│ 10:21:56           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-07         ┆ East Village ┆ Americano   ┆ Coconut   ┆ 12   ┆ false ┆ Angel       ┆ 4.82  │
│ 10:28:12           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Espresso    ┆ Almond    ┆ 16   ┆ false ┆ Danielle    ┆ 5.17  │
│ 06:12:20           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-08         ┆ East Village ┆ Latte       ┆ Almond    ┆ 12   ┆ false ┆ Danielle    ┆ 2.87  │
│ 10:56:38           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

- Usa variables para dar contexto sobre lo que representa una expresión.

In [ ]:
three_dollar_coffees = pl.col("price").is_between(3, 4)
other_priced_coffees = ~three_dollar_coffees

# coffees.filter(three_dollar_coffees)
# coffees.filter(other_priced_coffees)

### Lectura Adicional
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.not_.html

## When, Then, Otherwise
- El método `when` crea una expresión condicional.
- El método `then` asigna un valor basado en que la condición se cumpla.
- El método `otherwise` proporciona un valor de respaldo opcional si la condición no se cumple.

In [ ]:
coffees = pl.read_csv("coffee_sales.csv", try_parse_dates=True).sort("time_of_purchase")
coffees.head(2)

shape: (2, 8)
┌─────────────────────┬──────────────┬─────────────┬───────────┬──────┬──────┬─────────────┬───────┐
│ time_of_purchase    ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced ┆ barista     ┆ price │
│ ---                 ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---  ┆ ---         ┆ ---   │
│ datetime[μs]        ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool ┆ str         ┆ f64   │
╞═════════════════════╪══════════════╪═════════════╪═══════════╪══════╪══════╪═════════════╪═══════╡
│ 2025-01-01 01:53:30 ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true ┆ Christopher ┆ 3.1   │
│ 2025-01-01 02:39:54 ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 20   ┆ true ┆ Christopher ┆ 4.29  │
└─────────────────────┴──────────────┴─────────────┴───────────┴──────┴──────┴─────────────┴───────┘

- Digamos que queremos proporcionar una descripción para cada café basada en el tipo de leche.
- Si la leche es "Oat", la descripción debería ser `"Creamy"`. De lo contrario, el valor de respaldo es `"Unknown"`.
- La función `pl.lit` devuelve una expresión que representa un valor literal (es decir, fijo, constante).
- Sin un valor de respaldo, Polars usa un valor faltante (`null`) para cualquier valor que no coincida.

In [ ]:
coffees.with_columns(
    pl.when(pl.col("milk_type") == "Oat").then(pl.lit("Creamy")).alias("description")
)

shape: (1_000, 9)
┌─────────────┬─────────────┬────────────┬───────────┬───┬───────┬────────────┬───────┬────────────┐
│ time_of_pur ┆ location    ┆ coffee_nam ┆ milk_type ┆ … ┆ iced  ┆ barista    ┆ price ┆ descriptio │
│ chase       ┆ ---         ┆ e          ┆ ---       ┆   ┆ ---   ┆ ---        ┆ ---   ┆ n          │
│ ---         ┆ str         ┆ ---        ┆ str       ┆   ┆ bool  ┆ str        ┆ f64   ┆ ---        │
│ datetime[μs ┆             ┆ str        ┆           ┆   ┆       ┆            ┆       ┆ str        │
│ ]           ┆             ┆            ┆           ┆   ┆       ┆            ┆       ┆            │
╞═════════════╪═════════════╪════════════╪═══════════╪═══╪═══════╪════════════╪═══════╪════════════╡
│ 2025-01-01  ┆ Midtown     ┆ Latte      ┆ Soy       ┆ … ┆ true  ┆ Christophe ┆ 3.1   ┆ null       │
│ 01:53:30    ┆ West        ┆            ┆           ┆   ┆       ┆ r          ┆       ┆            │
│ 2025-01-01  ┆ Uptown      ┆ Flat White ┆ Oat       ┆ … ┆ true  ┆ Christophe ┆ 4.29  ┆ Creamy     │
│ 02:39:54    ┆             ┆            ┆           ┆   ┆       ┆ r          ┆       ┆            │
│ 2025-01-01  ┆ Downtown    ┆ Mocha      ┆ Almond    ┆ … ┆ false ┆ Jeffrey    ┆ 5.85  ┆ null       │
│ 07:52:54    ┆             ┆            ┆           ┆   ┆       ┆            ┆       ┆            │
│ 2025-01-01  ┆ Midtown     ┆ null       ┆ Soy       ┆ … ┆ false ┆ Jeffrey    ┆ 5.05  ┆ null       │
│ 10:02:41    ┆ West        ┆            ┆           ┆   ┆       ┆            ┆       ┆            │
│ 2025-01-01  ┆ SoHo        ┆ Flat White ┆ Oat       ┆ … ┆ false ┆ Danielle   ┆ 3.74  ┆ Creamy     │
│ 15:07:27    ┆             ┆            ┆           ┆   ┆       ┆            ┆       ┆            │
│ …           ┆ …           ┆ …          ┆ …         ┆ … ┆ …     ┆ …          ┆ …     ┆ …          │
│ 2025-06-07  ┆ Downtown    ┆ Macchiato  ┆ Oat       ┆ … ┆ false ┆ Danielle   ┆ 6.49  ┆ Creamy     │
│ 10:21:56    ┆             ┆            ┆           ┆   ┆       ┆            ┆       ┆            │
│ 2025-06-07  ┆ East        ┆ Americano  ┆ Coconut   ┆ … ┆ false ┆ Angel      ┆ 4.82  ┆ null       │
│ 10:28:12    ┆ Village     ┆            ┆           ┆   ┆       ┆            ┆       ┆            │
│ 2025-06-08  ┆ East        ┆ Espresso   ┆ Almond    ┆ … ┆ false ┆ Danielle   ┆ 5.17  ┆ null       │
│ 06:12:20    ┆ Village     ┆            ┆           ┆   ┆       ┆            ┆       ┆            │
│ 2025-06-08  ┆ East        ┆ Latte      ┆ Almond    ┆ … ┆ false ┆ Danielle   ┆ 2.87  ┆ null       │
│ 10:56:38    ┆ Village     ┆            ┆           ┆   ┆       ┆            ┆       ┆            │
│ 2025-06-08  ┆ Uptown      ┆ Espresso   ┆ Almond    ┆ … ┆ false ┆ Joshua     ┆ 3.45  ┆ null       │
│ 13:34:09    ┆             ┆            ┆           ┆   ┆       ┆            ┆       ┆            │
└─────────────┴─────────────┴────────────┴───────────┴───┴───────┴────────────┴───────┴────────────┘

- Usa el método `otherwise` para proporcionar un valor de respaldo en lugar de `null`.

In [ ]:
coffees.with_columns(
    pl.when(pl.col("milk_type") == "Oat")
    .then(pl.lit("Creamy"))
    .otherwise(pl.lit("Delicious"))
    .alias("description")
)

shape: (1_000, 9)
┌─────────────┬─────────────┬────────────┬───────────┬───┬───────┬────────────┬───────┬────────────┐
│ time_of_pur ┆ location    ┆ coffee_nam ┆ milk_type ┆ … ┆ iced  ┆ barista    ┆ price ┆ descriptio │
│ chase       ┆ ---         ┆ e          ┆ ---       ┆   ┆ ---   ┆ ---        ┆ ---   ┆ n          │
│ ---         ┆ str         ┆ ---        ┆ str       ┆   ┆ bool  ┆ str        ┆ f64   ┆ ---        │
│ datetime[μs ┆             ┆ str        ┆           ┆   ┆       ┆            ┆       ┆ str        │
│ ]           ┆             ┆            ┆           ┆   ┆       ┆            ┆       ┆            │
╞═════════════╪═════════════╪════════════╪═══════════╪═══╪═══════╪════════════╪═══════╪════════════╡
│ 2025-01-01  ┆ Midtown     ┆ Latte      ┆ Soy       ┆ … ┆ true  ┆ Christophe ┆ 3.1   ┆ Delicious  │
│ 01:53:30    ┆ West        ┆            ┆           ┆   ┆       ┆ r          ┆       ┆            │
│ 2025-01-01  ┆ Uptown      ┆ Flat White ┆ Oat       ┆ … ┆ true  ┆ Christophe ┆ 4.29  ┆ Creamy     │
│ 02:39:54    ┆             ┆            ┆           ┆   ┆       ┆ r          ┆       ┆            │
│ 2025-01-01  ┆ Downtown    ┆ Mocha      ┆ Almond    ┆ … ┆ false ┆ Jeffrey    ┆ 5.85  ┆ Delicious  │
│ 07:52:54    ┆             ┆            ┆           ┆   ┆       ┆            ┆       ┆            │
│ 2025-01-01  ┆ Midtown     ┆ null       ┆ Soy       ┆ … ┆ false ┆ Jeffrey    ┆ 5.05  ┆ Delicious  │
│ 10:02:41    ┆ West        ┆            ┆           ┆   ┆       ┆            ┆       ┆            │
│ 2025-01-01  ┆ SoHo        ┆ Flat White ┆ Oat       ┆ … ┆ false ┆ Danielle   ┆ 3.74  ┆ Creamy     │
│ 15:07:27    ┆             ┆            ┆           ┆   ┆       ┆            ┆       ┆            │
│ …           ┆ …           ┆ …          ┆ …         ┆ … ┆ …     ┆ …          ┆ …     ┆ …          │
│ 2025-06-07  ┆ Downtown    ┆ Macchiato  ┆ Oat       ┆ … ┆ false ┆ Danielle   ┆ 6.49  ┆ Creamy     │
│ 10:21:56    ┆             ┆            ┆           ┆   ┆       ┆            ┆       ┆            │
│ 2025-06-07  ┆ East        ┆ Americano  ┆ Coconut   ┆ … ┆ false ┆ Angel      ┆ 4.82  ┆ Delicious  │
│ 10:28:12    ┆ Village     ┆            ┆           ┆   ┆       ┆            ┆       ┆            │
│ 2025-06-08  ┆ East        ┆ Espresso   ┆ Almond    ┆ … ┆ false ┆ Danielle   ┆ 5.17  ┆ Delicious  │
│ 06:12:20    ┆ Village     ┆            ┆           ┆   ┆       ┆            ┆       ┆            │
│ 2025-06-08  ┆ East        ┆ Latte      ┆ Almond    ┆ … ┆ false ┆ Danielle   ┆ 2.87  ┆ Delicious  │
│ 10:56:38    ┆ Village     ┆            ┆           ┆   ┆       ┆            ┆       ┆            │
│ 2025-06-08  ┆ Uptown      ┆ Espresso   ┆ Almond    ┆ … ┆ false ┆ Joshua     ┆ 3.45  ┆ Delicious  │
│ 13:34:09    ┆             ┆            ┆           ┆   ┆       ┆            ┆       ┆            │
└─────────────┴─────────────┴────────────┴───────────┴───┴───────┴────────────┴───────┴────────────┘

- Podemos encadenar múltiples invocaciones del método `when` en secuencia.
- Cada llamada al método `when` crea una condición separada para evaluar.
- El diseño es similar a una sentencia `switch case` en varios lenguajes de programación.

In [ ]:
coffees.with_columns(
    pl.when(pl.col("milk_type") == "Oat")
    .then(pl.lit("Creamy"))
    .when(pl.col("milk_type") == "Almond")
    .then(pl.lit("Watery"))
    .otherwise(pl.lit("Delicious"))
    .alias("description")
)

shape: (1_000, 9)
┌─────────────┬─────────────┬────────────┬───────────┬───┬───────┬────────────┬───────┬────────────┐
│ time_of_pur ┆ location    ┆ coffee_nam ┆ milk_type ┆ … ┆ iced  ┆ barista    ┆ price ┆ descriptio │
│ chase       ┆ ---         ┆ e          ┆ ---       ┆   ┆ ---   ┆ ---        ┆ ---   ┆ n          │
│ ---         ┆ str         ┆ ---        ┆ str       ┆   ┆ bool  ┆ str        ┆ f64   ┆ ---        │
│ datetime[μs ┆             ┆ str        ┆           ┆   ┆       ┆            ┆       ┆ str        │
│ ]           ┆             ┆            ┆           ┆   ┆       ┆            ┆       ┆            │
╞═════════════╪═════════════╪════════════╪═══════════╪═══╪═══════╪════════════╪═══════╪════════════╡
│ 2025-01-01  ┆ Midtown     ┆ Latte      ┆ Soy       ┆ … ┆ true  ┆ Christophe ┆ 3.1   ┆ Delicious  │
│ 01:53:30    ┆ West        ┆            ┆           ┆   ┆       ┆ r          ┆       ┆            │
│ 2025-01-01  ┆ Uptown      ┆ Flat White ┆ Oat       ┆ … ┆ true  ┆ Christophe ┆ 4.29  ┆ Creamy     │
│ 02:39:54    ┆             ┆            ┆           ┆   ┆       ┆ r          ┆       ┆            │
│ 2025-01-01  ┆ Downtown    ┆ Mocha      ┆ Almond    ┆ … ┆ false ┆ Jeffrey    ┆ 5.85  ┆ Watery     │
│ 07:52:54    ┆             ┆            ┆           ┆   ┆       ┆            ┆       ┆            │
│ 2025-01-01  ┆ Midtown     ┆ null       ┆ Soy       ┆ … ┆ false ┆ Jeffrey    ┆ 5.05  ┆ Delicious  │
│ 10:02:41    ┆ West        ┆            ┆           ┆   ┆       ┆            ┆       ┆            │
│ 2025-01-01  ┆ SoHo        ┆ Flat White ┆ Oat       ┆ … ┆ false ┆ Danielle   ┆ 3.74  ┆ Creamy     │
│ 15:07:27    ┆             ┆            ┆           ┆   ┆       ┆            ┆       ┆            │
│ …           ┆ …           ┆ …          ┆ …         ┆ … ┆ …     ┆ …          ┆ …     ┆ …          │
│ 2025-06-07  ┆ Downtown    ┆ Macchiato  ┆ Oat       ┆ … ┆ false ┆ Danielle   ┆ 6.49  ┆ Creamy     │
│ 10:21:56    ┆             ┆            ┆           ┆   ┆       ┆            ┆       ┆            │
│ 2025-06-07  ┆ East        ┆ Americano  ┆ Coconut   ┆ … ┆ false ┆ Angel      ┆ 4.82  ┆ Delicious  │
│ 10:28:12    ┆ Village     ┆            ┆           ┆   ┆       ┆            ┆       ┆            │
│ 2025-06-08  ┆ East        ┆ Espresso   ┆ Almond    ┆ … ┆ false ┆ Danielle   ┆ 5.17  ┆ Watery     │
│ 06:12:20    ┆ Village     ┆            ┆           ┆   ┆       ┆            ┆       ┆            │
│ 2025-06-08  ┆ East        ┆ Latte      ┆ Almond    ┆ … ┆ false ┆ Danielle   ┆ 2.87  ┆ Watery     │
│ 10:56:38    ┆ Village     ┆            ┆           ┆   ┆       ┆            ┆       ┆            │
│ 2025-06-08  ┆ Uptown      ┆ Espresso   ┆ Almond    ┆ … ┆ false ┆ Joshua     ┆ 3.45  ┆ Watery     │
│ 13:34:09    ┆             ┆            ┆           ┆   ┆       ┆            ┆       ┆            │
└─────────────┴─────────────┴────────────┴───────────┴───┴───────┴────────────┴───────┴────────────┘

### Lectura Adicional
- https://docs.pola.rs/user-guide/expressions/basic-operations/#conditionals
- https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.when.html

## Particionando DataFrames
- Supongamos que queremos extraer un `DataFrame` para cada café único (`"Flat White"`, `"Latte"`).

In [ ]:
coffees = pl.read_csv("coffee_sales.csv", try_parse_dates=True)
coffees.head(3)

shape: (3, 8)
┌─────────────────────┬──────────────┬─────────────┬───────────┬──────┬──────┬──────────┬───────┐
│ time_of_purchase    ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced ┆ barista  ┆ price │
│ ---                 ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---  ┆ ---      ┆ ---   │
│ datetime[μs]        ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool ┆ str      ┆ f64   │
╞═════════════════════╪══════════════╪═════════════╪═══════════╪══════╪══════╪══════════╪═══════╡
│ 2025-02-12 10:55:36 ┆ Downtown     ┆ Flat White  ┆ Oat       ┆ 12   ┆ true ┆ Danielle ┆ 5.47  │
│ 2025-02-15 04:16:42 ┆ SoHo         ┆ Flat White  ┆ Oat       ┆ 12   ┆ true ┆ Robert   ┆ 2.85  │
│ 2025-04-09 03:07:34 ┆ Midtown West ┆ Latte       ┆ Almond    ┆ 20   ┆ true ┆ Jeffrey  ┆ 4.52  │
└─────────────────────┴──────────────┴─────────────┴───────────┴──────┴──────┴──────────┴───────┘

- Usa el método `unique` para devolver una columna de valores únicos de una columna objetivo.
- Escribir 12 sentencias `filter` es verboso y no es escalable.

In [ ]:
coffees.select(pl.col("coffee_name").unique())

shape: (12, 1)
┌─────────────┐
│ coffee_name │
│ ---         │
│ str         │
╞═════════════╡
│ Americano   │
│ Frappe      │
│ Cortado     │
│ Affogato    │
│ Flat White  │
│ …           │
│ null        │
│ Mocha       │
│ Espresso    │
│ Red eye     │
│ Latte       │
└─────────────┘

- El método `partition_by` usa los valores únicos de una columna para devolver una lista de `DataFrames`.
- El método `partition_by` acepta una cadena con el nombre de la columna (una expresión no es válida).
- La palabra __partición__ significa "dividir en partes".
- Si tenemos 12 cafés diferentes, entonces `partition_by` devolverá una lista de 12 `DataFrames`.

In [ ]:
coffees.partition_by("coffee_name")

[shape: (155, 8)
 ┌─────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬──────────┬───────┐
 │ time_of_purchase    ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista  ┆ price │
 │ ---                 ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---      ┆ ---   │
 │ datetime[μs]        ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str      ┆ f64   │
 ╞═════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪══════════╪═══════╡
 │ 2025-02-12 10:55:36 ┆ Downtown     ┆ Flat White  ┆ Oat       ┆ 12   ┆ true  ┆ Danielle ┆ 5.47  │
 │ 2025-02-15 04:16:42 ┆ SoHo         ┆ Flat White  ┆ Oat       ┆ 12   ┆ true  ┆ Robert   ┆ 2.85  │
 │ 2025-04-27 21:36:38 ┆ SoHo         ┆ Flat White  ┆ Coconut   ┆ 20   ┆ false ┆ Robert   ┆ 4.18  │
 │ 2025-05-07 04:40:51 ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 12   ┆ true  ┆ Danielle ┆ 5.15  │
 │ 2025-02-12 19:19:39 ┆ Midtown West ┆ Flat White  ┆ Whole     ┆ 16   ┆ false ┆ Danielle ┆ 3.42  │
 │ …                   ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …        ┆ …     │
 │ 2025-05-09 22:16:40 ┆ Downtown     ┆ Flat White  ┆ Coconut   ┆ 20   ┆ false ┆ Patricia ┆ 4.4   │
 │ 2025-04-14 02:16:31 ┆ Midtown West ┆ Flat White  ┆ Coconut   ┆ 20   ┆ true  ┆ Joshua   ┆ 3.75  │
 │ 2025-03-06 05:35:57 ┆ Midtown West ┆ Flat White  ┆ Almond    ┆ 20   ┆ false ┆ Jill     ┆ 3.68  │
 │ 2025-01-24 10:17:49 ┆ East Village ┆ Flat White  ┆ Whole     ┆ 20   ┆ false ┆ Patricia ┆ 4.8   │
 │ 2025-03-03 06:33:36 ┆ Midtown West ┆ Flat White  ┆ Whole     ┆ 16   ┆ false ┆ Patricia ┆ 2.72  │
 └─────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴──────────┴───────┘,
 shape: (139, 8)
 ┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
 │ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
 │ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
 │ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
 ╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
 │ 2025-04-09         ┆ Midtown West ┆ Latte       ┆ Almond    ┆ 20   ┆ true  ┆ Jeffrey     ┆ 4.52  │
 │ 03:07:34           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-05-20         ┆ East Village ┆ Latte       ┆ Soy       ┆ 16   ┆ true  ┆ Jill        ┆ 5.82  │
 │ 00:53:35           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-02-01         ┆ Midtown West ┆ Latte       ┆ Whole     ┆ 20   ┆ false ┆ Patricia    ┆ 3.13  │
 │ 00:03:58           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-03-07         ┆ Downtown     ┆ Latte       ┆ Soy       ┆ 12   ┆ true  ┆ Robert      ┆ 3.42  │
 │ 08:38:39           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-01-19         ┆ SoHo         ┆ Latte       ┆ Oat       ┆ 16   ┆ true  ┆ Patricia    ┆ 3.92  │
 │ 18:43:51           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
 │ 2025-04-23         ┆ Uptown       ┆ Latte       ┆ Whole     ┆ 20   ┆ true  ┆ Christopher ┆ 4.03  │
 │ 22:14:43           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-03-13         ┆ SoHo         ┆ Latte       ┆ Soy       ┆ 20   ┆ false ┆ Erica       ┆ 6.32  │
 │ 15:45:35           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-05-25         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true  ┆ Jeffrey     ┆ 6.3   │
 │ 20:18:39           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-04-17         ┆ East Village ┆ Latte       ┆ Soy       ┆ 12   ┆ true  ┆ Joshua      ┆ 4.0   │
 │ 20:59:46           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-02-18         ┆ SoHo         ┆ Latte       ┆ Oat       ┆ 12   ┆ false ┆ Anthony     ┆ 5.41  │
 │ 19:37:33           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 └────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘,
 shape: (152, 8)
 ┌─────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬──────────┬───────┐
 │ time_of_purchase    ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista  ┆ price │
 │ ---                 ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---      ┆ ---   │
 │ datetime[μs]        ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str      ┆ f64   │
 ╞═════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪══════════╪═══════╡
 │ 2025-01-06 03:39:59 ┆ Uptown       ┆ Macchiato   ┆ Oat       ┆ 16   ┆ true  ┆ Joshua   ┆ 5.29  │
 │ 2025-05-17 04:24:40 ┆ Uptown       ┆ Macchiato   ┆ Oat       ┆ 12   ┆ false ┆ Patricia ┆ 3.61  │
 │ 2025-01-14 12:09:01 ┆ Downtown     ┆ Macchiato   ┆ Whole     ┆ 20   ┆ false ┆ Danielle ┆ 2.51  │
 │ 2025-01-16 11:51:27 ┆ Midtown West ┆ Macchiato   ┆ 2%        ┆ 16   ┆ true  ┆ Jeffrey  ┆ 3.57  │
 │ 2025-02-15 04:53:02 ┆ SoHo         ┆ Macchiato   ┆ 2%        ┆ 16   ┆ false ┆ Jeffrey  ┆ 3.3   │
 │ …                   ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …        ┆ …     │
 │ 2025-02-05 07:26:06 ┆ East Village ┆ Macchiato   ┆ Whole     ┆ 16   ┆ true  ┆ Robert   ┆ 4.34  │
 │ 2025-02-24 07:18:10 ┆ Uptown       ┆ Macchiato   ┆ Almond    ┆ 16   ┆ false ┆ Joshua   ┆ 4.31  │
 │ 2025-02-23 15:30:17 ┆ East Village ┆ Macchiato   ┆ Whole     ┆ 12   ┆ true  ┆ Danielle ┆ 3.98  │
 │ 2025-05-15 07:57:42 ┆ Downtown     ┆ Macchiato   ┆ 2%        ┆ 12   ┆ false ┆ Jeffrey  ┆ 5.14  │
 │ 2025-03-08 18:01:32 ┆ East Village ┆ Macchiato   ┆ Oat       ┆ 12   ┆ false ┆ Danielle ┆ 4.14  │
 └─────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴──────────┴───────┘,
 shape: (134, 8)
 ┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
 │ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
 │ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
 │ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
 ╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
 │ 2025-04-19         ┆ Midtown West ┆ Mocha       ┆ Whole     ┆ 16   ┆ false ┆ Angel       ┆ 2.87  │
 │ 23:35:29           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-04-25         ┆ SoHo         ┆ Mocha       ┆ Coconut   ┆ 12   ┆ false ┆ Christopher ┆ 4.08  │
 │ 10:10:37           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-02-24         ┆ East Village ┆ Mocha       ┆ Almond    ┆ 16   ┆ false ┆ Robert      ┆ 4.66  │
 │ 00:27:45           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-01-02         ┆ SoHo         ┆ Mocha       ┆ Coconut   ┆ 20   ┆ true  ┆ Joshua      ┆ 5.67  │
 │ 06:17:11           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-03-24         ┆ East Village ┆ Mocha       ┆ Whole     ┆ 12   ┆ false ┆ Joshua      ┆ 4.66  │
 │ 01:31:33           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
 │ 2025-02-07         ┆ Uptown       ┆ Mocha       ┆ Soy       ┆ 16   ┆ true  ┆ Patricia    ┆ 5.87  │
 │ 02:23:14           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-02-16         ┆ Downtown     ┆ Mocha       ┆ Coconut   ┆ 12   ┆ true  ┆ Christopher ┆ 5.13  │
 │ 20:48:02           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-04-05         ┆ East Village ┆ Mocha       ┆ Almond    ┆ 16   ┆ true  ┆ Patricia    ┆ 4.92  │
 │ 20:56:16           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-02-22         ┆ East Village ┆ Mocha       ┆ Coconut   ┆ 16   ┆ true  ┆ Christopher ┆ 2.93  │
 │ 14:33:43           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-02-14         ┆ SoHo         ┆ Mocha       ┆ Coconut   ┆ 16   ┆ true  ┆ Danielle    ┆ 6.23  │
 │ 18:23:06           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 └────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘,
 shape: (129, 8)
 ┌─────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬──────────┬───────┐
 │ time_of_purchase    ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista  ┆ price │
 │ ---                 ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---      ┆ ---   │
 │ datetime[μs]        ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str      ┆ f64   │
 ╞═════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪══════════╪═══════╡
 │ 2025-02-08 14:39:02 ┆ East Village ┆ Cappuccino  ┆ Whole     ┆ 12   ┆ false ┆ Danielle ┆ 5.42  │
 │ 2025-03-23 11:06:14 ┆ SoHo         ┆ Cappuccino  ┆ Coconut   ┆ 16   ┆ true  ┆ Jeffrey  ┆ 3.15  │
 │ 2025-05-16 13:33:55 ┆ Uptown       ┆ Cappuccino  ┆ Almond    ┆ 20   ┆ true  ┆ Robert   ┆ 6.15  │
 │ 2025-01-19 00:13:37 ┆ Downtown     ┆ Cappuccino  ┆ Almond    ┆ 20   ┆ true  ┆ Jill     ┆ 5.18  │
 │ 2025-01-25 05:43:55 ┆ Midtown West ┆ Cappuccino  ┆ Oat       ┆ 20   ┆ true  ┆ Joshua   ┆ 2.77  │
 │ …                   ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …        ┆ …     │
 │ 2025-05-19 05:25:33 ┆ SoHo         ┆ Cappuccino  ┆ 2%        ┆ 16   ┆ false ┆ Anthony  ┆ 5.44  │
 │ 2025-06-03 23:20:06 ┆ East Village ┆ Cappuccino  ┆ Oat       ┆ 12   ┆ false ┆ Jill     ┆ 5.74  │
 │ 2025-01-19 01:39:36 ┆ Midtown West ┆ Cappuccino  ┆ Whole     ┆ 20   ┆ true  ┆ Jill     ┆ 5.93  │
 │ 2025-02-27 03:14:13 ┆ SoHo         ┆ Cappuccino  ┆ Almond    ┆ 16   ┆ true  ┆ Anthony  ┆ 5.46  │
 │ 2025-03-01 12:58:00 ┆ Uptown       ┆ Cappuccino  ┆ Coconut   ┆ 12   ┆ true  ┆ Angel    ┆ 6.15  │
 └─────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴──────────┴───────┘,
 shape: (151, 8)
 ┌─────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬──────────┬───────┐
 │ time_of_purchase    ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista  ┆ price │
 │ ---                 ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---      ┆ ---   │
 │ datetime[μs]        ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str      ┆ f64   │
 ╞═════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪══════════╪═══════╡
 │ 2025-04-16 19:36:40 ┆ Midtown West ┆ Espresso    ┆ Almond    ┆ 20   ┆ true  ┆ Jill     ┆ 5.31  │
 │ 2025-03-29 05:27:57 ┆ East Village ┆ Espresso    ┆ Oat       ┆ 20   ┆ false ┆ Jeffrey  ┆ 6.15  │
 │ 2025-06-07 04:13:09 ┆ Midtown West ┆ Espresso    ┆ Almond    ┆ 12   ┆ true  ┆ Joshua   ┆ 4.54  │
 │ 2025-03-31 05:04:30 ┆ East Village ┆ Espresso    ┆ Almond    ┆ 12   ┆ false ┆ Danielle ┆ 4.82  │
 │ 2025-02-07 08:07:47 ┆ Downtown     ┆ Espresso    ┆ Soy       ┆ 20   ┆ false ┆ Jeffrey  ┆ 5.37  │
 │ …                   ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …        ┆ …     │
 │ 2025-04-06 07:23:35 ┆ East Village ┆ Espresso    ┆ Almond    ┆ 20   ┆ false ┆ Danielle ┆ 5.28  │
 │ 2025-02-13 00:42:50 ┆ East Village ┆ Espresso    ┆ Coconut   ┆ 12   ┆ false ┆ Jeffrey  ┆ 4.44  │
 │ 2025-04-02 21:33:13 ┆ Uptown       ┆ Espresso    ┆ Whole     ┆ 20   ┆ false ┆ Jill     ┆ 5.71  │
 │ 2025-03-24 14:59:29 ┆ Midtown West ┆ Espresso    ┆ Almond    ┆ 12   ┆ true  ┆ Jill     ┆ 3.51  │
 │ 2025-03-10 07:33:21 ┆ Midtown West ┆ Espresso    ┆ 2%        ┆ 16   ┆ true  ┆ Erica    ┆ 3.53  │
 └─────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴──────────┴───────┘,
 shape: (130, 8)
 ┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
 │ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
 │ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
 │ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
 ╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
 │ 2025-05-28         ┆ East Village ┆ Americano   ┆ 2%        ┆ 16   ┆ true  ┆ Anthony     ┆ 6.48  │
 │ 08:17:55           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-03-08         ┆ Uptown       ┆ Americano   ┆ Oat       ┆ 12   ┆ true  ┆ Angel       ┆ 6.22  │
 │ 01:40:56           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-05-29         ┆ Downtown     ┆ Americano   ┆ Soy       ┆ 12   ┆ false ┆ Christopher ┆ 2.98  │
 │ 06:08:25           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-04-28         ┆ East Village ┆ Americano   ┆ Almond    ┆ 12   ┆ true  ┆ Angel       ┆ 4.27  │
 │ 05:34:02           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-06-06         ┆ Midtown West ┆ Americano   ┆ 2%        ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.96  │
 │ 17:29:25           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
 │ 2025-03-01         ┆ East Village ┆ Americano   ┆ 2%        ┆ 12   ┆ false ┆ Christopher ┆ 3.71  │
 │ 11:01:24           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-04-18         ┆ East Village ┆ Americano   ┆ Coconut   ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.44  │
 │ 11:22:15           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-05-17         ┆ Uptown       ┆ Americano   ┆ 2%        ┆ 16   ┆ true  ┆ Erica       ┆ 6.48  │
 │ 11:32:29           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-03-30         ┆ Downtown     ┆ Americano   ┆ Oat       ┆ 20   ┆ false ┆ Christopher ┆ 6.42  │
 │ 02:36:22           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-05-21         ┆ Midtown West ┆ Americano   ┆ 2%        ┆ 20   ┆ true  ┆ Patricia    ┆ 5.88  │
 │ 01:25:43           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 └────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘,
 shape: (6, 8)
 ┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
 │ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
 │ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
 │ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
 ╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
 │ 2025-01-01         ┆ Midtown West ┆ null        ┆ Soy       ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.05  │
 │ 10:02:41           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-05-10         ┆ SoHo         ┆ null        ┆ 2%        ┆ 20   ┆ false ┆ Erica       ┆ 4.4   │
 │ 16:28:05           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-04-09         ┆ Downtown     ┆ null        ┆ Whole     ┆ 16   ┆ true  ┆ Angel       ┆ 2.8   │
 │ 22:00:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-01-29         ┆ Downtown     ┆ null        ┆ Oat       ┆ 16   ┆ true  ┆ Jill        ┆ 6.09  │
 │ 15:43:56           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-02-22         ┆ SoHo         ┆ null        ┆ 2%        ┆ 20   ┆ true  ┆ Robert      ┆ 2.72  │
 │ 23:58:14           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-01-07         ┆ Downtown     ┆ null        ┆ Oat       ┆ 16   ┆ false ┆ Christopher ┆ 3.92  │
 │ 00:36:36           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 └────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘,
 shape: (1, 8)
 ┌─────────────────────┬──────────┬─────────────┬───────────┬──────┬──────┬─────────┬───────┐
 │ time_of_purchase    ┆ location ┆ coffee_name ┆ milk_type ┆ size ┆ iced ┆ barista ┆ price │
 │ ---                 ┆ ---      ┆ ---         ┆ ---       ┆ ---  ┆ ---  ┆ ---     ┆ ---   │
 │ datetime[μs]        ┆ str      ┆ str         ┆ str       ┆ i64  ┆ bool ┆ str     ┆ f64   │
 ╞═════════════════════╪══════════╪═════════════╪═══════════╪══════╪══════╪═════════╪═══════╡
 │ 2025-01-27 01:50:31 ┆ SoHo     ┆ Frappe      ┆ Soy       ┆ 16   ┆ true ┆ Jeffrey ┆ 4.3   │
 └─────────────────────┴──────────┴─────────────┴───────────┴──────┴──────┴─────────┴───────┘,
 shape: (1, 8)
 ┌─────────────────────┬──────────┬─────────────┬───────────┬──────┬───────┬─────────┬───────┐
 │ time_of_purchase    ┆ location ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista ┆ price │
 │ ---                 ┆ ---      ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---     ┆ ---   │
 │ datetime[μs]        ┆ str      ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str     ┆ f64   │
 ╞═════════════════════╪══════════╪═════════════╪═══════════╪══════╪═══════╪═════════╪═══════╡
 │ 2025-04-15 13:22:05 ┆ Uptown   ┆ Red eye     ┆ 2%        ┆ 12   ┆ false ┆ Anthony ┆ 4.71  │
 └─────────────────────┴──────────┴─────────────┴───────────┴──────┴───────┴─────────┴───────┘,
 shape: (1, 8)
 ┌─────────────────────┬──────────────┬─────────────┬───────────┬──────┬──────┬─────────┬───────┐
 │ time_of_purchase    ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced ┆ barista ┆ price │
 │ ---                 ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---  ┆ ---     ┆ ---   │
 │ datetime[μs]        ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool ┆ str     ┆ f64   │
 ╞═════════════════════╪══════════════╪═════════════╪═══════════╪══════╪══════╪═════════╪═══════╡
 │ 2025-04-26 01:07:54 ┆ Midtown West ┆ Cortado     ┆ Whole     ┆ 20   ┆ true ┆ Joshua  ┆ 5.58  │
 └─────────────────────┴──────────────┴─────────────┴───────────┴──────┴──────┴─────────┴───────┘,
 shape: (1, 8)
 ┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
 │ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
 │ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
 │ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
 ╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
 │ 2025-02-07         ┆ East Village ┆ Affogato    ┆ 2%        ┆ 16   ┆ false ┆ Christopher ┆ 2.98  │
 │ 09:30:28           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 └────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘]

- La lista no es particularmente útil porque los `DataFrames` son accesibles por posición de índice.
- Polars almacenará los `DataFrames` en el orden en que encuentra los valores únicos en el `DataFrame` original.
- En este ejemplo, "Flat White" viene primero, luego "Latte", luego "Macchiato", etc.
- El parámetro `as_dict` devuelve un diccionario donde las claves son tuplas con los valores únicos de la columna y los valores son los `DataFrames`.

In [ ]:
# Se animan a explicar por que las claves del diccionario son tuplas? Ej. ('Flat White',)
coffees_dict = coffees.partition_by("coffee_name", as_dict=True)
coffees_dict

{('Flat White',): shape: (155, 8)
 ┌─────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬──────────┬───────┐
 │ time_of_purchase    ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista  ┆ price │
 │ ---                 ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---      ┆ ---   │
 │ datetime[μs]        ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str      ┆ f64   │
 ╞═════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪══════════╪═══════╡
 │ 2025-02-12 10:55:36 ┆ Downtown     ┆ Flat White  ┆ Oat       ┆ 12   ┆ true  ┆ Danielle ┆ 5.47  │
 │ 2025-02-15 04:16:42 ┆ SoHo         ┆ Flat White  ┆ Oat       ┆ 12   ┆ true  ┆ Robert   ┆ 2.85  │
 │ 2025-04-27 21:36:38 ┆ SoHo         ┆ Flat White  ┆ Coconut   ┆ 20   ┆ false ┆ Robert   ┆ 4.18  │
 │ 2025-05-07 04:40:51 ┆ Uptown       ┆ Flat White  ┆ Oat       ┆ 12   ┆ true  ┆ Danielle ┆ 5.15  │
 │ 2025-02-12 19:19:39 ┆ Midtown West ┆ Flat White  ┆ Whole     ┆ 16   ┆ false ┆ Danielle ┆ 3.42  │
 │ …                   ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …        ┆ …     │
 │ 2025-05-09 22:16:40 ┆ Downtown     ┆ Flat White  ┆ Coconut   ┆ 20   ┆ false ┆ Patricia ┆ 4.4   │
 │ 2025-04-14 02:16:31 ┆ Midtown West ┆ Flat White  ┆ Coconut   ┆ 20   ┆ true  ┆ Joshua   ┆ 3.75  │
 │ 2025-03-06 05:35:57 ┆ Midtown West ┆ Flat White  ┆ Almond    ┆ 20   ┆ false ┆ Jill     ┆ 3.68  │
 │ 2025-01-24 10:17:49 ┆ East Village ┆ Flat White  ┆ Whole     ┆ 20   ┆ false ┆ Patricia ┆ 4.8   │
 │ 2025-03-03 06:33:36 ┆ Midtown West ┆ Flat White  ┆ Whole     ┆ 16   ┆ false ┆ Patricia ┆ 2.72  │
 └─────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴──────────┴───────┘,
 ('Latte',): shape: (139, 8)
 ┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
 │ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
 │ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
 │ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
 ╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
 │ 2025-04-09         ┆ Midtown West ┆ Latte       ┆ Almond    ┆ 20   ┆ true  ┆ Jeffrey     ┆ 4.52  │
 │ 03:07:34           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-05-20         ┆ East Village ┆ Latte       ┆ Soy       ┆ 16   ┆ true  ┆ Jill        ┆ 5.82  │
 │ 00:53:35           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-02-01         ┆ Midtown West ┆ Latte       ┆ Whole     ┆ 20   ┆ false ┆ Patricia    ┆ 3.13  │
 │ 00:03:58           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-03-07         ┆ Downtown     ┆ Latte       ┆ Soy       ┆ 12   ┆ true  ┆ Robert      ┆ 3.42  │
 │ 08:38:39           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-01-19         ┆ SoHo         ┆ Latte       ┆ Oat       ┆ 16   ┆ true  ┆ Patricia    ┆ 3.92  │
 │ 18:43:51           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
 │ 2025-04-23         ┆ Uptown       ┆ Latte       ┆ Whole     ┆ 20   ┆ true  ┆ Christopher ┆ 4.03  │
 │ 22:14:43           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-03-13         ┆ SoHo         ┆ Latte       ┆ Soy       ┆ 20   ┆ false ┆ Erica       ┆ 6.32  │
 │ 15:45:35           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-05-25         ┆ Midtown West ┆ Latte       ┆ Soy       ┆ 20   ┆ true  ┆ Jeffrey     ┆ 6.3   │
 │ 20:18:39           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-04-17         ┆ East Village ┆ Latte       ┆ Soy       ┆ 12   ┆ true  ┆ Joshua      ┆ 4.0   │
 │ 20:59:46           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-02-18         ┆ SoHo         ┆ Latte       ┆ Oat       ┆ 12   ┆ false ┆ Anthony     ┆ 5.41  │
 │ 19:37:33           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 └────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘,
 ('Macchiato',): shape: (152, 8)
 ┌─────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬──────────┬───────┐
 │ time_of_purchase    ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista  ┆ price │
 │ ---                 ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---      ┆ ---   │
 │ datetime[μs]        ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str      ┆ f64   │
 ╞═════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪══════════╪═══════╡
 │ 2025-01-06 03:39:59 ┆ Uptown       ┆ Macchiato   ┆ Oat       ┆ 16   ┆ true  ┆ Joshua   ┆ 5.29  │
 │ 2025-05-17 04:24:40 ┆ Uptown       ┆ Macchiato   ┆ Oat       ┆ 12   ┆ false ┆ Patricia ┆ 3.61  │
 │ 2025-01-14 12:09:01 ┆ Downtown     ┆ Macchiato   ┆ Whole     ┆ 20   ┆ false ┆ Danielle ┆ 2.51  │
 │ 2025-01-16 11:51:27 ┆ Midtown West ┆ Macchiato   ┆ 2%        ┆ 16   ┆ true  ┆ Jeffrey  ┆ 3.57  │
 │ 2025-02-15 04:53:02 ┆ SoHo         ┆ Macchiato   ┆ 2%        ┆ 16   ┆ false ┆ Jeffrey  ┆ 3.3   │
 │ …                   ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …        ┆ …     │
 │ 2025-02-05 07:26:06 ┆ East Village ┆ Macchiato   ┆ Whole     ┆ 16   ┆ true  ┆ Robert   ┆ 4.34  │
 │ 2025-02-24 07:18:10 ┆ Uptown       ┆ Macchiato   ┆ Almond    ┆ 16   ┆ false ┆ Joshua   ┆ 4.31  │
 │ 2025-02-23 15:30:17 ┆ East Village ┆ Macchiato   ┆ Whole     ┆ 12   ┆ true  ┆ Danielle ┆ 3.98  │
 │ 2025-05-15 07:57:42 ┆ Downtown     ┆ Macchiato   ┆ 2%        ┆ 12   ┆ false ┆ Jeffrey  ┆ 5.14  │
 │ 2025-03-08 18:01:32 ┆ East Village ┆ Macchiato   ┆ Oat       ┆ 12   ┆ false ┆ Danielle ┆ 4.14  │
 └─────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴──────────┴───────┘,
 ('Mocha',): shape: (134, 8)
 ┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
 │ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
 │ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
 │ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
 ╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
 │ 2025-04-19         ┆ Midtown West ┆ Mocha       ┆ Whole     ┆ 16   ┆ false ┆ Angel       ┆ 2.87  │
 │ 23:35:29           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-04-25         ┆ SoHo         ┆ Mocha       ┆ Coconut   ┆ 12   ┆ false ┆ Christopher ┆ 4.08  │
 │ 10:10:37           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-02-24         ┆ East Village ┆ Mocha       ┆ Almond    ┆ 16   ┆ false ┆ Robert      ┆ 4.66  │
 │ 00:27:45           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-01-02         ┆ SoHo         ┆ Mocha       ┆ Coconut   ┆ 20   ┆ true  ┆ Joshua      ┆ 5.67  │
 │ 06:17:11           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-03-24         ┆ East Village ┆ Mocha       ┆ Whole     ┆ 12   ┆ false ┆ Joshua      ┆ 4.66  │
 │ 01:31:33           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
 │ 2025-02-07         ┆ Uptown       ┆ Mocha       ┆ Soy       ┆ 16   ┆ true  ┆ Patricia    ┆ 5.87  │
 │ 02:23:14           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-02-16         ┆ Downtown     ┆ Mocha       ┆ Coconut   ┆ 12   ┆ true  ┆ Christopher ┆ 5.13  │
 │ 20:48:02           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-04-05         ┆ East Village ┆ Mocha       ┆ Almond    ┆ 16   ┆ true  ┆ Patricia    ┆ 4.92  │
 │ 20:56:16           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-02-22         ┆ East Village ┆ Mocha       ┆ Coconut   ┆ 16   ┆ true  ┆ Christopher ┆ 2.93  │
 │ 14:33:43           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-02-14         ┆ SoHo         ┆ Mocha       ┆ Coconut   ┆ 16   ┆ true  ┆ Danielle    ┆ 6.23  │
 │ 18:23:06           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 └────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘,
 ('Cappuccino',): shape: (129, 8)
 ┌─────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬──────────┬───────┐
 │ time_of_purchase    ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista  ┆ price │
 │ ---                 ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---      ┆ ---   │
 │ datetime[μs]        ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str      ┆ f64   │
 ╞═════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪══════════╪═══════╡
 │ 2025-02-08 14:39:02 ┆ East Village ┆ Cappuccino  ┆ Whole     ┆ 12   ┆ false ┆ Danielle ┆ 5.42  │
 │ 2025-03-23 11:06:14 ┆ SoHo         ┆ Cappuccino  ┆ Coconut   ┆ 16   ┆ true  ┆ Jeffrey  ┆ 3.15  │
 │ 2025-05-16 13:33:55 ┆ Uptown       ┆ Cappuccino  ┆ Almond    ┆ 20   ┆ true  ┆ Robert   ┆ 6.15  │
 │ 2025-01-19 00:13:37 ┆ Downtown     ┆ Cappuccino  ┆ Almond    ┆ 20   ┆ true  ┆ Jill     ┆ 5.18  │
 │ 2025-01-25 05:43:55 ┆ Midtown West ┆ Cappuccino  ┆ Oat       ┆ 20   ┆ true  ┆ Joshua   ┆ 2.77  │
 │ …                   ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …        ┆ …     │
 │ 2025-05-19 05:25:33 ┆ SoHo         ┆ Cappuccino  ┆ 2%        ┆ 16   ┆ false ┆ Anthony  ┆ 5.44  │
 │ 2025-06-03 23:20:06 ┆ East Village ┆ Cappuccino  ┆ Oat       ┆ 12   ┆ false ┆ Jill     ┆ 5.74  │
 │ 2025-01-19 01:39:36 ┆ Midtown West ┆ Cappuccino  ┆ Whole     ┆ 20   ┆ true  ┆ Jill     ┆ 5.93  │
 │ 2025-02-27 03:14:13 ┆ SoHo         ┆ Cappuccino  ┆ Almond    ┆ 16   ┆ true  ┆ Anthony  ┆ 5.46  │
 │ 2025-03-01 12:58:00 ┆ Uptown       ┆ Cappuccino  ┆ Coconut   ┆ 12   ┆ true  ┆ Angel    ┆ 6.15  │
 └─────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴──────────┴───────┘,
 ('Espresso',): shape: (151, 8)
 ┌─────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬──────────┬───────┐
 │ time_of_purchase    ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista  ┆ price │
 │ ---                 ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---      ┆ ---   │
 │ datetime[μs]        ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str      ┆ f64   │
 ╞═════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪══════════╪═══════╡
 │ 2025-04-16 19:36:40 ┆ Midtown West ┆ Espresso    ┆ Almond    ┆ 20   ┆ true  ┆ Jill     ┆ 5.31  │
 │ 2025-03-29 05:27:57 ┆ East Village ┆ Espresso    ┆ Oat       ┆ 20   ┆ false ┆ Jeffrey  ┆ 6.15  │
 │ 2025-06-07 04:13:09 ┆ Midtown West ┆ Espresso    ┆ Almond    ┆ 12   ┆ true  ┆ Joshua   ┆ 4.54  │
 │ 2025-03-31 05:04:30 ┆ East Village ┆ Espresso    ┆ Almond    ┆ 12   ┆ false ┆ Danielle ┆ 4.82  │
 │ 2025-02-07 08:07:47 ┆ Downtown     ┆ Espresso    ┆ Soy       ┆ 20   ┆ false ┆ Jeffrey  ┆ 5.37  │
 │ …                   ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …        ┆ …     │
 │ 2025-04-06 07:23:35 ┆ East Village ┆ Espresso    ┆ Almond    ┆ 20   ┆ false ┆ Danielle ┆ 5.28  │
 │ 2025-02-13 00:42:50 ┆ East Village ┆ Espresso    ┆ Coconut   ┆ 12   ┆ false ┆ Jeffrey  ┆ 4.44  │
 │ 2025-04-02 21:33:13 ┆ Uptown       ┆ Espresso    ┆ Whole     ┆ 20   ┆ false ┆ Jill     ┆ 5.71  │
 │ 2025-03-24 14:59:29 ┆ Midtown West ┆ Espresso    ┆ Almond    ┆ 12   ┆ true  ┆ Jill     ┆ 3.51  │
 │ 2025-03-10 07:33:21 ┆ Midtown West ┆ Espresso    ┆ 2%        ┆ 16   ┆ true  ┆ Erica    ┆ 3.53  │
 └─────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴──────────┴───────┘,
 ('Americano',): shape: (130, 8)
 ┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
 │ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
 │ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
 │ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
 ╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
 │ 2025-05-28         ┆ East Village ┆ Americano   ┆ 2%        ┆ 16   ┆ true  ┆ Anthony     ┆ 6.48  │
 │ 08:17:55           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-03-08         ┆ Uptown       ┆ Americano   ┆ Oat       ┆ 12   ┆ true  ┆ Angel       ┆ 6.22  │
 │ 01:40:56           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-05-29         ┆ Downtown     ┆ Americano   ┆ Soy       ┆ 12   ┆ false ┆ Christopher ┆ 2.98  │
 │ 06:08:25           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-04-28         ┆ East Village ┆ Americano   ┆ Almond    ┆ 12   ┆ true  ┆ Angel       ┆ 4.27  │
 │ 05:34:02           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-06-06         ┆ Midtown West ┆ Americano   ┆ 2%        ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.96  │
 │ 17:29:25           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
 │ 2025-03-01         ┆ East Village ┆ Americano   ┆ 2%        ┆ 12   ┆ false ┆ Christopher ┆ 3.71  │
 │ 11:01:24           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-04-18         ┆ East Village ┆ Americano   ┆ Coconut   ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.44  │
 │ 11:22:15           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-05-17         ┆ Uptown       ┆ Americano   ┆ 2%        ┆ 16   ┆ true  ┆ Erica       ┆ 6.48  │
 │ 11:32:29           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-03-30         ┆ Downtown     ┆ Americano   ┆ Oat       ┆ 20   ┆ false ┆ Christopher ┆ 6.42  │
 │ 02:36:22           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-05-21         ┆ Midtown West ┆ Americano   ┆ 2%        ┆ 20   ┆ true  ┆ Patricia    ┆ 5.88  │
 │ 01:25:43           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 └────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘,
 (None,): shape: (6, 8)
 ┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
 │ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
 │ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
 │ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
 ╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
 │ 2025-01-01         ┆ Midtown West ┆ null        ┆ Soy       ┆ 12   ┆ false ┆ Jeffrey     ┆ 5.05  │
 │ 10:02:41           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-05-10         ┆ SoHo         ┆ null        ┆ 2%        ┆ 20   ┆ false ┆ Erica       ┆ 4.4   │
 │ 16:28:05           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-04-09         ┆ Downtown     ┆ null        ┆ Whole     ┆ 16   ┆ true  ┆ Angel       ┆ 2.8   │
 │ 22:00:09           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-01-29         ┆ Downtown     ┆ null        ┆ Oat       ┆ 16   ┆ true  ┆ Jill        ┆ 6.09  │
 │ 15:43:56           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-02-22         ┆ SoHo         ┆ null        ┆ 2%        ┆ 20   ┆ true  ┆ Robert      ┆ 2.72  │
 │ 23:58:14           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 │ 2025-01-07         ┆ Downtown     ┆ null        ┆ Oat       ┆ 16   ┆ false ┆ Christopher ┆ 3.92  │
 │ 00:36:36           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
 └────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘,
 ('Frappe',): shape: (1, 8)
 ┌─────────────────────┬──────────┬─────────────┬───────────┬──────┬──────┬─────────┬───────┐
 │ time_of_purchase    ┆ location ┆ coffee_name ┆ milk_type ┆ size ┆ iced ┆ barista ┆ price │
 │ ---                 ┆ ---      ┆ ---         ┆ ---       ┆ ---  ┆ ---  ┆ ---     ┆ ---   │
 │ datetime[μs]        ┆ str      ┆ str         ┆ str       ┆ i64  ┆ bool ┆ str     ┆ f64   │
 ╞═════════════════════╪══════════╪═════════════╪═══════════╪══════╪══════╪═════════╪═══════╡
 │ 2025-01-27 01:50:31 ┆ SoHo     ┆ Frappe      ┆ Soy       ┆ 16   ┆ true ┆ Jeffrey ┆ 4.3   │
 └─────────────────────┴──────────┴─────────────┴───────────┴──────┴──────┴─────────┴───────┘,
 ('Red eye',): shape: (1, 8)
 ┌─────────────────────┬──────────┬─────────────┬───────────┬──────┬───────┬─────────┬───────┐
 │ time_of_purchase    ┆ location ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista ┆ price │
 │ ---                 ┆ ---      ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---     ┆ ---   │
 │ datetime[μs]        ┆ str      ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str     ┆ f64   │
 ╞═════════════════════╪══════════╪═════════════╪═══════════╪══════╪═══════╪═════════╪═══════╡
 │ 2025-04-15 13:22:05 ┆ Uptown   ┆ Red eye     ┆ 2%        ┆ 12   ┆ false ┆ Anthony ┆ 4.71  │
 └─────────────────────┴──────────┴─────────────┴───────────┴──────┴───────┴─────────┴───────┘,
 ('Cortado',): shape: (1, 8)
 ┌─────────────────────┬──────────────┬─────────────┬───────────┬──────┬──────┬─────────┬───────┐
 │ time_of_purchase    ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced ┆ barista ┆ price │
 │ ---                 ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---  ┆ ---     ┆ ---   │
 │ datetime[μs]        ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool ┆ str     ┆ f64   │
 ╞═════════════════════╪══════════════╪═════════════╪═══════════╪══════╪══════╪═════════╪═══════╡
 │ 2025-04-26 01:07:54 ┆ Midtown West ┆ Cortado     ┆ Whole     ┆ 20   ┆ true ┆ Joshua  ┆ 5.58  │
 └─────────────────────┴──────────────┴─────────────┴───────────┴──────┴──────┴─────────┴───────┘,
 ('Affogato',): shape: (1, 8)
 ┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
 │ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
 │ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
 │ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
 ╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
 │ 2025-02-07         ┆ East Village ┆ Affogato    ┆ 2%        ┆ 16   ┆ false ┆ Christopher ┆ 2.98  │
 │ 09:30:28           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │

- Usa corchetes para indexar el diccionario y proporciona una clave de tupla para acceder al `DataFrame` correspondiente.

In [ ]:
coffees_dict[("Mocha",)]

# coffees_dict[("Affogato",)]

shape: (134, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-04-19         ┆ Midtown West ┆ Mocha       ┆ Whole     ┆ 16   ┆ false ┆ Angel       ┆ 2.87  │
│ 23:35:29           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-04-25         ┆ SoHo         ┆ Mocha       ┆ Coconut   ┆ 12   ┆ false ┆ Christopher ┆ 4.08  │
│ 10:10:37           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-02-24         ┆ East Village ┆ Mocha       ┆ Almond    ┆ 16   ┆ false ┆ Robert      ┆ 4.66  │
│ 00:27:45           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-01-02         ┆ SoHo         ┆ Mocha       ┆ Coconut   ┆ 20   ┆ true  ┆ Joshua      ┆ 5.67  │
│ 06:17:11           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-03-24         ┆ East Village ┆ Mocha       ┆ Whole     ┆ 12   ┆ false ┆ Joshua      ┆ 4.66  │
│ 01:31:33           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-02-07         ┆ Uptown       ┆ Mocha       ┆ Soy       ┆ 16   ┆ true  ┆ Patricia    ┆ 5.87  │
│ 02:23:14           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-02-16         ┆ Downtown     ┆ Mocha       ┆ Coconut   ┆ 12   ┆ true  ┆ Christopher ┆ 5.13  │
│ 20:48:02           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-04-05         ┆ East Village ┆ Mocha       ┆ Almond    ┆ 16   ┆ true  ┆ Patricia    ┆ 4.92  │
│ 20:56:16           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-02-22         ┆ East Village ┆ Mocha       ┆ Coconut   ┆ 16   ┆ true  ┆ Christopher ┆ 2.93  │
│ 14:33:43           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-02-14         ┆ SoHo         ┆ Mocha       ┆ Coconut   ┆ 16   ┆ true  ┆ Danielle    ┆ 6.23  │
│ 18:23:06           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

- La razón por la que el diccionario almacena claves de tupla es para soportar particionamiento con múltiples claves.
- En su lugar, dividamos el `DataFrame` por cada combinación de café y leche.

In [ ]:
coffee_and_milk = coffees.partition_by(["coffee_name", "milk_type"], as_dict=True)

- Pasa una tupla con la entrada de café y leche para extraer el `DataFrame` objetivo.
- Un solo valor (por ejemplo, "Americano") producirá un error.

In [ ]:
coffee_and_milk[("Americano", "Soy")]

shape: (22, 8)
┌────────────────────┬──────────────┬─────────────┬───────────┬──────┬───────┬─────────────┬───────┐
│ time_of_purchase   ┆ location     ┆ coffee_name ┆ milk_type ┆ size ┆ iced  ┆ barista     ┆ price │
│ ---                ┆ ---          ┆ ---         ┆ ---       ┆ ---  ┆ ---   ┆ ---         ┆ ---   │
│ datetime[μs]       ┆ str          ┆ str         ┆ str       ┆ i64  ┆ bool  ┆ str         ┆ f64   │
╞════════════════════╪══════════════╪═════════════╪═══════════╪══════╪═══════╪═════════════╪═══════╡
│ 2025-05-29         ┆ Downtown     ┆ Americano   ┆ Soy       ┆ 12   ┆ false ┆ Christopher ┆ 2.98  │
│ 06:08:25           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-05-04         ┆ SoHo         ┆ Americano   ┆ Soy       ┆ 12   ┆ true  ┆ Jeffrey     ┆ 3.52  │
│ 10:30:15           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-02-12         ┆ Midtown West ┆ Americano   ┆ Soy       ┆ 20   ┆ false ┆ Anthony     ┆ 5.15  │
│ 15:28:51           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-05-08         ┆ SoHo         ┆ Americano   ┆ Soy       ┆ 16   ┆ true  ┆ Jeffrey     ┆ 5.26  │
│ 06:33:56           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-03-18         ┆ East Village ┆ Americano   ┆ Soy       ┆ 16   ┆ false ┆ Robert      ┆ 3.88  │
│ 19:46:41           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ …                  ┆ …            ┆ …           ┆ …         ┆ …    ┆ …     ┆ …           ┆ …     │
│ 2025-05-08         ┆ SoHo         ┆ Americano   ┆ Soy       ┆ 20   ┆ false ┆ Erica       ┆ 3.53  │
│ 15:34:51           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-03-01         ┆ SoHo         ┆ Americano   ┆ Soy       ┆ 20   ┆ true  ┆ Angel       ┆ 3.74  │
│ 20:35:16           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-06-04         ┆ SoHo         ┆ Americano   ┆ Soy       ┆ 16   ┆ false ┆ Christopher ┆ 2.85  │
│ 03:04:30           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-04-14         ┆ Downtown     ┆ Americano   ┆ Soy       ┆ 16   ┆ true  ┆ Patricia    ┆ 2.68  │
│ 10:46:22           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
│ 2025-03-20         ┆ SoHo         ┆ Americano   ┆ Soy       ┆ 16   ┆ false ┆ Patricia    ┆ 4.71  │
│ 22:05:32           ┆              ┆             ┆           ┆      ┆       ┆             ┆       │
└────────────────────┴──────────────┴─────────────┴───────────┴──────┴───────┴─────────────┴───────┘

### Lectura Adicional
- https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.partition_by.html

---
# Ejercicios de práctica

In [ ]:
import polars as pl

coffees = pl.read_csv("coffee_sales.csv", try_parse_dates=True).sort("time_of_purchase")

### Ejercicio 1
Filtra todas las filas donde el `coffee_name` sea `"Latte"` y el `price` sea mayor a `4`.

### Ejercicio 2
Filtra las filas donde el `coffee_name` sea `"Americano"`, `"Espresso"` o `"Mocha"` usando el método `is_in`, y que además la bebida sea helada (`iced` sea `true`).

### Ejercicio 3
Filtra las transacciones realizadas entre el 1 de marzo de 2025 y el 30 de abril de 2025 (inclusive) donde el `price` esté entre `3` y `5` dólares. Usa `is_between` para ambas condiciones.

### Ejercicio 4
Usa `when`/`then`/`otherwise` para crear una nueva columna llamada `"categoria_precio"` con las siguientes reglas:
- Si el `price` es menor a `3`, asignar `"Barato"`
- Si el `price` está entre `3` y `5` (inclusive), asignar `"Normal"`
- En cualquier otro caso, asignar `"Caro"`

### Ejercicio 5
Usa `remove` para eliminar todas las filas donde el `coffee_name` sea nulo o donde la `location` sea `"SoHo"`. Luego, particiona el resultado por `milk_type` usando `partition_by` con `as_dict=True` y muestra el DataFrame correspondiente a la leche `"Oat"`.